<dec f='linux-5.3.1/include/linux/mod_devicetable.h' l='213' type='__u32'/>
<offset>192</offset>
<use f='linux-5.3.1/drivers/acpi/bus.c' l='709' u='r' c='__acpi_match_device_cls'/>
<use f='linux-5.3.1/drivers/acpi/bus.c' l='719' u='r' c='__acpi_match_device_cls'/>
<use f='linux-5.3.1/drivers/acpi/bus.c' l='745' u='r' c='__acpi_match_device'/>
<use f='linux-5.3.1/drivers/acpi/bus.c' l='748' u='r' c='__acpi_match_device'/>
<use f='linux-5.3.1/scripts/mod/file2alias.c' l='540' c='do_acpi_entry'/>
