<dec f='linux-5.3.1/include/crypto/internal/hash.h' l='33' type='struct ahash_alg'/>
<use f='linux-5.3.1/include/crypto/internal/hash.h' l='146' u='m' c='ahash_crypto_instance'/>
<use f='linux-5.3.1/include/crypto/internal/hash.h' l='146' u='m' c='ahash_crypto_instance'/>
<use f='linux-5.3.1/include/crypto/internal/hash.h' l='146' u='m' c='ahash_crypto_instance'/>
<use f='linux-5.3.1/include/crypto/internal/hash.h' l='152' u='m' c='ahash_instance'/>
<use f='linux-5.3.1/crypto/ahash.c' l='641' u='a' c='ahash_register_instance'/>
<offset>0</offset>
