<dec f='linux-5.3.1/drivers/input/mouse/alps.h' l='238' type='struct input_mt_pos'/>
<use f='linux-5.3.1/drivers/input/mouse/alps.c' l='483' u='m' c='alps_process_bitmap'/>
<use f='linux-5.3.1/drivers/input/mouse/alps.c' l='484' u='m' c='alps_process_bitmap'/>
<use f='linux-5.3.1/drivers/input/mouse/alps.c' l='496' u='r' c='alps_process_bitmap'/>
<use f='linux-5.3.1/drivers/input/mouse/alps.c' l='532' u='m' c='alps_report_semi_mt_data'/>
<use f='linux-5.3.1/drivers/input/mouse/alps.c' l='533' u='m' c='alps_report_semi_mt_data'/>
<use f='linux-5.3.1/drivers/input/mouse/alps.c' l='649' u='m' c='alps_decode_pinnacle'/>
<use f='linux-5.3.1/drivers/input/mouse/alps.c' l='651' u='m' c='alps_decode_pinnacle'/>
<use f='linux-5.3.1/drivers/input/mouse/alps.c' l='677' u='m' c='alps_decode_rushmore'/>
<use f='linux-5.3.1/drivers/input/mouse/alps.c' l='679' u='m' c='alps_decode_rushmore'/>
<use f='linux-5.3.1/drivers/input/mouse/alps.c' l='698' u='m' c='alps_decode_dolphin'/>
<use f='linux-5.3.1/drivers/input/mouse/alps.c' l='699' u='m' c='alps_decode_dolphin'/>
<use f='linux-5.3.1/drivers/input/mouse/alps.c' l='789' u='m' c='alps_process_touchpad_packet_v3_v5'/>
<use f='linux-5.3.1/drivers/input/mouse/alps.c' l='789' u='m' c='alps_process_touchpad_packet_v3_v5'/>
<use f='linux-5.3.1/drivers/input/mouse/alps.c' l='916' u='m' c='alps_process_packet_v4'/>
<use f='linux-5.3.1/drivers/input/mouse/alps.c' l='918' u='m' c='alps_process_packet_v4'/>
<offset>128</offset>
