<dec f='linux-5.3.1/include/crypto/arc4.h' l='16' type='u32 [256]'/>
<use f='linux-5.3.1/lib/crypto/arc4.c' l='21' u='w' c='arc4_setkey'/>
<use f='linux-5.3.1/lib/crypto/arc4.c' l='24' u='r' c='arc4_setkey'/>
<use f='linux-5.3.1/lib/crypto/arc4.c' l='27' u='w' c='arc4_setkey'/>
<use f='linux-5.3.1/lib/crypto/arc4.c' l='27' u='r' c='arc4_setkey'/>
<use f='linux-5.3.1/lib/crypto/arc4.c' l='28' u='w' c='arc4_setkey'/>
<use f='linux-5.3.1/lib/crypto/arc4.c' l='39' u='r' c='arc4_crypt'/>
<offset>0</offset>
