<dec f='linux-5.3.1/include/linux/libata.h' l='620' type='struct ata_taskfile'/>
<use f='linux-5.3.1/include/linux/libata.h' l='1662' u='m' c='ata_qc_set_polling'/>
<use f='linux-5.3.1/include/linux/libata.h' l='1720' u='a' c='ata_qc_reinit'/>
<offset>256</offset>
<use f='linux-5.3.1/drivers/ata/libahci.c' l='1632' u='m' c='ahci_qc_prep'/>
<use f='linux-5.3.1/drivers/ata/libahci.c' l='1644' u='a' c='ahci_qc_prep'/>
<use f='linux-5.3.1/drivers/ata/libahci.c' l='1658' u='m' c='ahci_qc_prep'/>
<use f='linux-5.3.1/drivers/ata/libahci.c' l='1998' u='m' c='ahci_qc_issue'/>
<use f='linux-5.3.1/drivers/ata/libahci.c' l='2031' u='m' c='ahci_qc_fill_rtf'/>
<use f='linux-5.3.1/include/trace/events/libata.h' l='182' u='m' c='trace_event_raw_event_ata_qc_issue'/>
<use f='linux-5.3.1/include/trace/events/libata.h' l='183' u='m' c='trace_event_raw_event_ata_qc_issue'/>
<use f='linux-5.3.1/include/trace/events/libata.h' l='184' u='m' c='trace_event_raw_event_ata_qc_issue'/>
<use f='linux-5.3.1/include/trace/events/libata.h' l='185' u='m' c='trace_event_raw_event_ata_qc_issue'/>
<use f='linux-5.3.1/include/trace/events/libata.h' l='186' u='m' c='trace_event_raw_event_ata_qc_issue'/>
<use f='linux-5.3.1/include/trace/events/libata.h' l='187' u='m' c='trace_event_raw_event_ata_qc_issue'/>
<use f='linux-5.3.1/include/trace/events/libata.h' l='188' u='m' c='trace_event_raw_event_ata_qc_issue'/>
<use f='linux-5.3.1/include/trace/events/libata.h' l='189' u='m' c='trace_event_raw_event_ata_qc_issue'/>
<use f='linux-5.3.1/include/trace/events/libata.h' l='190' u='m' c='trace_event_raw_event_ata_qc_issue'/>
<use f='linux-5.3.1/include/trace/events/libata.h' l='191' u='m' c='trace_event_raw_event_ata_qc_issue'/>
<use f='linux-5.3.1/include/trace/events/libata.h' l='192' u='m' c='trace_event_raw_event_ata_qc_issue'/>
<use f='linux-5.3.1/include/trace/events/libata.h' l='193' u='m' c='trace_event_raw_event_ata_qc_issue'/>
<use f='linux-5.3.1/include/trace/events/libata.h' l='194' u='m' c='trace_event_raw_event_ata_qc_issue'/>
<use f='linux-5.3.1/include/trace/events/libata.h' l='182' u='m' c='perf_trace_ata_qc_issue'/>
<use f='linux-5.3.1/include/trace/events/libata.h' l='183' u='m' c='perf_trace_ata_qc_issue'/>
<use f='linux-5.3.1/include/trace/events/libata.h' l='184' u='m' c='perf_trace_ata_qc_issue'/>
<use f='linux-5.3.1/include/trace/events/libata.h' l='185' u='m' c='perf_trace_ata_qc_issue'/>
<use f='linux-5.3.1/include/trace/events/libata.h' l='186' u='m' c='perf_trace_ata_qc_issue'/>
<use f='linux-5.3.1/include/trace/events/libata.h' l='187' u='m' c='perf_trace_ata_qc_issue'/>
<use f='linux-5.3.1/include/trace/events/libata.h' l='188' u='m' c='perf_trace_ata_qc_issue'/>
<use f='linux-5.3.1/include/trace/events/libata.h' l='189' u='m' c='perf_trace_ata_qc_issue'/>
<use f='linux-5.3.1/include/trace/events/libata.h' l='190' u='m' c='perf_trace_ata_qc_issue'/>
<use f='linux-5.3.1/include/trace/events/libata.h' l='191' u='m' c='perf_trace_ata_qc_issue'/>
<use f='linux-5.3.1/include/trace/events/libata.h' l='192' u='m' c='perf_trace_ata_qc_issue'/>
<use f='linux-5.3.1/include/trace/events/libata.h' l='193' u='m' c='perf_trace_ata_qc_issue'/>
<use f='linux-5.3.1/include/trace/events/libata.h' l='194' u='m' c='perf_trace_ata_qc_issue'/>
<use f='linux-5.3.1/drivers/ata/libata-core.c' l='1594' u='w' c='ata_exec_internal_sg'/>
<use f='linux-5.3.1/drivers/ata/libata-core.c' l='1601' u='m' c='ata_exec_internal_sg'/>
<use f='linux-5.3.1/drivers/ata/libata-core.c' l='1680' u='m' c='ata_exec_internal_sg'/>
<use f='linux-5.3.1/drivers/ata/libata-core.c' l='4972' u='m' c='ata_std_qc_defer'/>
<use f='linux-5.3.1/drivers/ata/libata-core.c' l='5172' u='m' c='__ata_qc_complete'/>
<use f='linux-5.3.1/drivers/ata/libata-core.c' l='5201' u='m' c='fill_result_tf'/>
<use f='linux-5.3.1/drivers/ata/libata-core.c' l='5209' u='m' c='ata_verify_xfer'/>
<use f='linux-5.3.1/drivers/ata/libata-core.c' l='5212' u='m' c='ata_verify_xfer'/>
<use f='linux-5.3.1/drivers/ata/libata-core.c' l='5238' u='m' c='ata_qc_complete'/>
<use f='linux-5.3.1/drivers/ata/libata-core.c' l='5292' u='m' c='ata_qc_complete'/>
<use f='linux-5.3.1/drivers/ata/libata-core.c' l='5294' u='m' c='ata_qc_complete'/>
<use f='linux-5.3.1/drivers/ata/libata-core.c' l='5295' u='m' c='ata_qc_complete'/>
<use f='linux-5.3.1/drivers/ata/libata-core.c' l='5296' u='m' c='ata_qc_complete'/>
<use f='linux-5.3.1/drivers/ata/libata-core.c' l='5297' u='m' c='ata_qc_complete'/>
<use f='linux-5.3.1/drivers/ata/libata-core.c' l='5402' u='m' c='ata_qc_issue'/>
<use f='linux-5.3.1/drivers/ata/libata-eh.c' l='2489' u='a' c='ata_eh_link_report'/>
<use f='linux-5.3.1/drivers/ata/libata-eh.c' l='2505' u='m' c='ata_eh_link_report'/>
<use f='linux-5.3.1/drivers/ata/libata-eh.c' l='2538' u='m' c='ata_eh_link_report'/>
<use f='linux-5.3.1/drivers/ata/libata-eh.c' l='3364' u='m' c='ata_eh_maybe_retry_flush'/>
<use f='linux-5.3.1/drivers/ata/libata-eh.c' l='3365' u='m' c='ata_eh_maybe_retry_flush'/>
<use f='linux-5.3.1/drivers/ata/libata-eh.c' l='3375' u='m' c='ata_eh_maybe_retry_flush'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='1461' u='a' c='ata_scsi_start_stop_xlat'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='1554' u='a' c='ata_scsi_flush_xlat'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='1676' u='a' c='ata_scsi_verify_xlat'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='1899' u='a' c='ata_scsi_rw_xlat'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='2820' u='a' c='atapi_request_sense'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='2825' u='m' c='atapi_request_sense'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='2838' u='m' c='atapi_request_sense'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='2839' u='m' c='atapi_request_sense'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='2842' u='m' c='atapi_request_sense'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='2843' u='m' c='atapi_request_sense'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='2845' u='m' c='atapi_request_sense'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='2846' u='m' c='atapi_request_sense'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='2847' u='m' c='atapi_request_sense'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='2962' u='m' c='atapi_xlat'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='2964' u='m' c='atapi_xlat'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='2968' u='m' c='atapi_xlat'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='3009' u='m' c='atapi_xlat'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='3010' u='m' c='atapi_xlat'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='3013' u='m' c='atapi_xlat'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='3015' u='m' c='atapi_xlat'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='3018' u='m' c='atapi_xlat'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='3019' u='m' c='atapi_xlat'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='3024' u='m' c='atapi_xlat'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='3144' u='a' c='ata_scsi_pass_thru'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='3451' u='a' c='ata_scsi_write_same_xlat'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='3696' u='a' c='ata_scsi_zbc_in_xlat'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='3779' u='a' c='ata_scsi_zbc_out_xlat'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='3870' u='a' c='ata_mselect_caching'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='4139' u='a' c='ata_scsi_security_inout_xlat'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='655' u='m' c='ata_pio_sector'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='708' u='a' c='ata_pio_sectors'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='745' u='m' c='atapi_send_cdb'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='777' u='m' c='__atapi_pio_bytes'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='850' u='m' c='atapi_pio_bytes'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='903' u='m' c='ata_hsm_ok_in_wq'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='907' u='m' c='ata_hsm_ok_in_wq'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='908' u='m' c='ata_hsm_ok_in_wq'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='911' u='m' c='ata_hsm_ok_in_wq'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='1001' u='m' c='ata_sff_hsm_move'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='1042' u='m' c='ata_sff_hsm_move'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='1064' u='m' c='ata_sff_hsm_move'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='1141' u='m' c='ata_sff_hsm_move'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='1174' u='m' c='ata_sff_hsm_move'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='1353' u='m' c='ata_sff_qc_issue'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='1359' u='m' c='ata_sff_qc_issue'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='1361' u='m' c='ata_sff_qc_issue'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='1364' u='a' c='ata_sff_qc_issue'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='1367' u='m' c='ata_sff_qc_issue'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='1373' u='m' c='ata_sff_qc_issue'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='1376' u='a' c='ata_sff_qc_issue'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='1378' u='m' c='ata_sff_qc_issue'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='1390' u='m' c='ata_sff_qc_issue'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='1403' u='m' c='ata_sff_qc_issue'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='1406' u='a' c='ata_sff_qc_issue'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='1412' u='m' c='ata_sff_qc_issue'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='1548' u='m' c='__ata_sff_interrupt'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='1641' u='m' c='ata_sff_lost_interrupt'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='2729' u='m' c='ata_bmdma_qc_issue'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='2736' u='m' c='ata_bmdma_qc_issue'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='2738' u='m' c='ata_bmdma_qc_issue'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='2740' u='a' c='ata_bmdma_qc_issue'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='2747' u='m' c='ata_bmdma_qc_issue'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='2749' u='a' c='ata_bmdma_qc_issue'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='2787' u='m' c='ata_bmdma_port_intr'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='2809' u='m' c='ata_bmdma_port_intr'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='2861' u='m' c='ata_bmdma_error_handler'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='2907' u='m' c='ata_bmdma_post_internal_cmd'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='2947' u='m' c='ata_bmdma_setup'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='2962' u='a' c='ata_bmdma_setup'/>
