<dec f='linux-5.3.1/include/linux/libata.h' l='558' type='u8'/>
<use f='linux-5.3.1/include/linux/libata.h' l='1724' u='w' c='ata_qc_reinit'/>
<offset>120</offset>
<use f='linux-5.3.1/drivers/ata/libata-acpi.c' l='557' u='w' c='ata_acpi_gtf_to_tf'/>
<use f='linux-5.3.1/drivers/ata/libata-acpi.c' l='575' u='r' c='ata_acpi_filter_tf'/>
<use f='linux-5.3.1/drivers/ata/libata-acpi.c' l='586' u='r' c='ata_acpi_filter_tf'/>
<use f='linux-5.3.1/drivers/ata/libata-acpi.c' l='596' u='r' c='ata_acpi_filter_tf'/>
<use f='linux-5.3.1/drivers/ata/libata-acpi.c' l='597' u='r' c='ata_acpi_filter_tf'/>
<use f='linux-5.3.1/drivers/ata/libata-acpi.c' l='602' u='r' c='ata_acpi_filter_tf'/>
<use f='linux-5.3.1/drivers/ata/libata-acpi.c' l='684' u='r' c='ata_acpi_run_tf'/>
<use f='linux-5.3.1/drivers/ata/libata-acpi.c' l='692' u='r' c='ata_acpi_run_tf'/>
<use f='linux-5.3.1/drivers/ata/libata-acpi.c' l='705' u='r' c='ata_acpi_run_tf'/>
<use f='linux-5.3.1/include/trace/events/libata.h' l='191' u='r' c='trace_event_raw_event_ata_qc_issue'/>
<use f='linux-5.3.1/include/trace/events/libata.h' l='248' u='r' c='trace_event_raw_event_ata_qc_complete_template'/>
<use f='linux-5.3.1/include/trace/events/libata.h' l='191' u='r' c='perf_trace_ata_qc_issue'/>
<use f='linux-5.3.1/include/trace/events/libata.h' l='248' u='r' c='perf_trace_ata_qc_complete_template'/>
<use f='linux-5.3.1/drivers/ata/libata-core.c' l='546' u='r' c='ata_tf_to_fis'/>
<use f='linux-5.3.1/drivers/ata/libata-core.c' l='583' u='w' c='ata_tf_from_fis'/>
<use f='linux-5.3.1/drivers/ata/libata-core.c' l='761' u='w' c='ata_build_rw_tf'/>
<use f='linux-5.3.1/drivers/ata/libata-core.c' l='1241' u='r' c='ata_read_native_max_address'/>
<use f='linux-5.3.1/drivers/ata/libata-core.c' l='1305' u='r' c='ata_set_max_sectors'/>
<use f='linux-5.3.1/drivers/ata/libata-core.c' l='1601' u='w' c='ata_exec_internal_sg'/>
<use f='linux-5.3.1/drivers/ata/libata-core.c' l='1902' u='r' c='ata_dev_read_id'/>
<use f='linux-5.3.1/drivers/ata/libata-core.c' l='4819' u='w' c='ata_dev_set_xfermode'/>
<use f='linux-5.3.1/drivers/ata/libata-core.c' l='4864' u='w' c='ata_dev_set_feature'/>
<use f='linux-5.3.1/drivers/ata/libata-core.c' l='4915' u='r' c='ata_dev_init_params'/>
<use f='linux-5.3.1/drivers/ata/libata-core.c' l='5294' u='r' c='ata_qc_complete'/>
<use f='linux-5.3.1/drivers/ata/libata-core.c' l='5295' u='r' c='ata_qc_complete'/>
<use f='linux-5.3.1/drivers/ata/libata-core.c' l='5296' u='r' c='ata_qc_complete'/>
<use f='linux-5.3.1/drivers/ata/libata-core.c' l='5297' u='r' c='ata_qc_complete'/>
<use f='linux-5.3.1/drivers/ata/libata-eh.c' l='1462' u='w' c='ata_eh_read_log_10h'/>
<use f='linux-5.3.1/drivers/ata/libata-eh.c' l='1505' u='r' c='atapi_eh_tur'/>
<use f='linux-5.3.1/drivers/ata/libata-eh.c' l='1601' u='w' c='atapi_eh_request_sense'/>
<use f='linux-5.3.1/drivers/ata/libata-eh.c' l='1754' u='r' c='ata_eh_analyze_tf'/>
<use f='linux-5.3.1/drivers/ata/libata-eh.c' l='1791' u='r' c='ata_eh_analyze_tf'/>
<use f='linux-5.3.1/drivers/ata/libata-eh.c' l='2560' u='r' c='ata_eh_link_report'/>
<use f='linux-5.3.1/drivers/ata/libata-eh.c' l='2565' u='r' c='ata_eh_link_report'/>
<use f='linux-5.3.1/drivers/ata/libata-eh.c' l='2587' u='r' c='ata_eh_link_report'/>
<use f='linux-5.3.1/drivers/ata/libata-eh.c' l='2590' u='r' c='ata_eh_link_report'/>
<use f='linux-5.3.1/drivers/ata/libata-eh.c' l='2591' u='r' c='ata_eh_link_report'/>
<use f='linux-5.3.1/drivers/ata/libata-eh.c' l='2592' u='r' c='ata_eh_link_report'/>
<use f='linux-5.3.1/drivers/ata/libata-eh.c' l='2593' u='r' c='ata_eh_link_report'/>
<use f='linux-5.3.1/drivers/ata/libata-eh.c' l='2594' u='r' c='ata_eh_link_report'/>
<use f='linux-5.3.1/drivers/ata/libata-eh.c' l='3086' u='w' c='ata_eh_park_issue_cmd'/>
<use f='linux-5.3.1/drivers/ata/libata-pmp.c' l='49' u='w' c='sata_pmp_read'/>
<use f='linux-5.3.1/drivers/ata/libata-pmp.c' l='85' u='w' c='sata_pmp_write'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='888' u='r' c='ata_dump_status'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='1087' u='r' c='ata_gen_passthru_sense'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='1117' u='r' c='ata_gen_passthru_sense'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='1138' u='r' c='ata_gen_passthru_sense'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='1191' u='r' c='ata_gen_ata_sense'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='2825' u='r' c='atapi_request_sense'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='2843' u='w' c='atapi_request_sense'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='3019' u='w' c='atapi_xlat'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='3024' u='w' c='atapi_xlat'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='3190' u='w' c='ata_scsi_pass_thru'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='3203' u='w' c='ata_scsi_pass_thru'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='3226' u='w' c='ata_scsi_pass_thru'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='3352' u='r' c='ata_scsi_pass_thru'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='3520' u='w' c='ata_scsi_write_same_xlat'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='3526' u='w' c='ata_scsi_write_same_xlat'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='3739' u='w' c='ata_scsi_zbc_in_xlat'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='3744' u='w' c='ata_scsi_zbc_in_xlat'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='3826' u='w' c='ata_scsi_zbc_out_xlat'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='3832' u='w' c='ata_scsi_zbc_out_xlat'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='3908' u='w' c='ata_mselect_caching'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='4174' u='w' c='ata_scsi_security_inout_xlat'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='425' u='r' c='ata_sff_tf_load'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='465' u='w' c='ata_sff_tf_read'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='1825' u='r' c='ata_sff_dev_classify'/>
