<dec f='linux-5.3.1/kernel/audit.h' l='193' type='struct (anonymous struct at /home/woboq/linux-5.3.1/kernel/audit.h:191:3)'/>
<offset>0</offset>
<use f='linux-5.3.1/kernel/auditsc.c' l='857' u='m' c='audit_free_module'/>
<use f='linux-5.3.1/kernel/auditsc.c' l='858' u='m' c='audit_free_module'/>
<use f='linux-5.3.1/kernel/auditsc.c' l='1287' u='m' c='show_special'/>
<use f='linux-5.3.1/kernel/auditsc.c' l='1288' u='m' c='show_special'/>
<use f='linux-5.3.1/kernel/auditsc.c' l='2507' u='m' c='__audit_log_kern_module'/>
<use f='linux-5.3.1/kernel/auditsc.c' l='2508' u='m' c='__audit_log_kern_module'/>
