<dec f='linux-5.3.1/include/linux/audit.h' l='42' type='u32'/>
<offset>96</offset>
<use f='linux-5.3.1/kernel/auditfilter.c' l='274' u='w' c='audit_to_entry_common'/>
<use f='linux-5.3.1/kernel/auditfilter.c' l='631' u='r' c='audit_krule_to_data'/>
<use f='linux-5.3.1/kernel/auditfilter.c' l='696' u='r' c='audit_compare_rule'/>
<use f='linux-5.3.1/kernel/auditfilter.c' l='696' u='r' c='audit_compare_rule'/>
<use f='linux-5.3.1/kernel/auditfilter.c' l='820' u='w' c='audit_dupe_rule'/>
<use f='linux-5.3.1/kernel/auditfilter.c' l='820' u='r' c='audit_dupe_rule'/>
<use f='linux-5.3.1/kernel/auditfilter.c' l='1376' u='r' c='audit_filter'/>
<use f='linux-5.3.1/kernel/auditsc.c' l='725' u='r' c='audit_filter_rules'/>
<use f='linux-5.3.1/kernel/auditsc.c' l='1966' u='r' c='__audit_inode'/>
<use f='linux-5.3.1/kernel/auditsc.c' l='2084' u='r' c='__audit_inode_child'/>
