<dec f='linux-5.3.1/kernel/audit.h' l='55' type='unsigned int'/>
<offset>0</offset>
<doc f='linux-5.3.1/kernel/audit.h' l='55'>/* effective bit of file cap */</doc>
<use f='linux-5.3.1/kernel/auditsc.c' l='1184' u='r' c='audit_log_fcaps'/>
<use f='linux-5.3.1/kernel/auditsc.c' l='1491' u='r' c='audit_log_exit'/>
<use f='linux-5.3.1/kernel/auditsc.c' l='1911' u='w' c='audit_copy_fcaps'/>
<use f='linux-5.3.1/kernel/auditsc.c' l='2460' u='w' c='__audit_log_bprm_fcaps'/>
