<dec f='linux-5.3.1/include/linux/usb/storage.h' l='56' type='__u32'/>
<use f='linux-5.3.1/drivers/usb/storage/initializers.c' l='62' u='w' c='usb_stor_ucr61s2b_init'/>
<offset>32</offset>
<doc f='linux-5.3.1/include/linux/usb/storage.h' l='56'>/* unique per command id */</doc>
<use f='linux-5.3.1/drivers/usb/storage/transport.c' l='1125' u='w' c='usb_stor_Bulk_transport'/>
<use f='linux-5.3.1/drivers/usb/storage/transport.c' l='1137' u='r' c='usb_stor_Bulk_transport'/>
