<dec f='linux-5.3.1/include/linux/device.h' l='143' type='struct subsys_private *'/>
<offset>1216</offset>
<use f='linux-5.3.1/drivers/base/bus.c' l='44' u='r' c='bus_get'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='53' u='r' c='bus_put'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='134' u='r' c='bus_create_file'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='145' u='r' c='bus_remove_file'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='157' u='w' c='bus_release'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='231' u='r' c='drivers_autoprobe_show'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='238' u='r' c='drivers_autoprobe_store'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='240' u='r' c='drivers_autoprobe_store'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='298' u='r' c='bus_for_each_dev'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='301' u='r' c='bus_for_each_dev'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='332' u='r' c='bus_find_device'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='335' u='r' c='bus_find_device'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='389' u='r' c='subsys_find_device_by_id'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='398' u='r' c='subsys_find_device_by_id'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='451' u='r' c='bus_for_each_drv'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='478' u='r' c='bus_add_device'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='483' u='r' c='bus_add_device'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='486' u='r' c='bus_add_device'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='491' u='r' c='bus_add_device'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='513' u='r' c='bus_probe_device'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='516' u='r' c='bus_probe_device'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='517' u='r' c='bus_probe_device'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='517' u='r' c='bus_probe_device'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='517' u='r' c='bus_probe_device'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='517' u='r' c='bus_probe_device'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='520' u='r' c='bus_probe_device'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='541' u='r' c='bus_remove_device'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='542' u='r' c='bus_remove_device'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='542' u='r' c='bus_remove_device'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='542' u='r' c='bus_remove_device'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='542' u='r' c='bus_remove_device'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='545' u='r' c='bus_remove_device'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='548' u='r' c='bus_remove_device'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='637' u='r' c='bus_add_driver'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='643' u='r' c='bus_add_driver'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='644' u='r' c='bus_add_driver'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='775' u='r' c='bus_add_groups'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='781' u='r' c='bus_remove_groups'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='805' u='r' c='bus_uevent_store'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='836' u='w' c='bus_register'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='889' u='r' c='bus_register'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='891' u='r' c='bus_register'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='895' u='r' c='bus_register'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='897' u='r' c='bus_register'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='898' u='w' c='bus_register'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='917' u='r' c='bus_unregister'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='918' u='r' c='bus_unregister'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='920' u='r' c='bus_unregister'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='926' u='r' c='bus_register_notifier'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='932' u='r' c='bus_unregister_notifier'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='938' u='r' c='bus_get_kset'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='944' u='r' c='bus_get_device_klist'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='1017' u='r' c='subsys_dev_iter_init'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='1076' u='r' c='subsys_interface_register'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='1077' u='r' c='subsys_interface_register'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='1084' u='r' c='subsys_interface_register'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='1101' u='r' c='subsys_interface_unregister'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='1109' u='r' c='subsys_interface_unregister'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2161' u='r' c='device_add'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2313' u='r' c='device_del'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2347' u='r' c='device_del'/>
<use f='linux-5.3.1/drivers/base/dd.c' l='391' u='r' c='driver_bound'/>
<use f='linux-5.3.1/drivers/base/dd.c' l='413' u='r' c='driver_sysfs_add'/>
<use f='linux-5.3.1/drivers/base/dd.c' l='474' u='r' c='device_bind_driver'/>
<use f='linux-5.3.1/drivers/base/dd.c' l='589' u='r' c='really_probe'/>
<use f='linux-5.3.1/drivers/base/dd.c' l='1111' u='r' c='__device_release_driver'/>
<use f='linux-5.3.1/drivers/base/dd.c' l='1136' u='r' c='__device_release_driver'/>
<use f='linux-5.3.1/drivers/base/driver.c' l='151' u='r' c='driver_register'/>
<use f='linux-5.3.1/drivers/base/driver.c' l='215' u='r' c='driver_find'/>
<use f='linux-5.3.1/drivers/base/platform.c' l='747' u='r' c='__platform_driver_probe'/>
<use f='linux-5.3.1/drivers/base/platform.c' l='752' u='r' c='__platform_driver_probe'/>
