<dec f='linux-5.3.1/include/linux/sunrpc/cache.h' l='91' type='void (*)(struct cache_head *, struct cache_head *)'/>
<offset>832</offset>
<use f='linux-5.3.1/net/sunrpc/auth_gss/svcauth_gss.c' l='285' u='w'/>
<use f='linux-5.3.1/net/sunrpc/auth_gss/svcauth_gss.c' l='556' u='w'/>
<use f='linux-5.3.1/net/sunrpc/cache.c' l='98' u='r' c='sunrpc_cache_add_entry'/>
<use f='linux-5.3.1/net/sunrpc/cache.c' l='200' u='r' c='sunrpc_cache_update'/>
<use f='linux-5.3.1/net/sunrpc/svcauth_unix.c' l='591' u='w'/>
<use f='linux-5.3.1/net/sunrpc/svcauth_unix.c' l='888' u='w'/>
