<dec f='linux-5.3.1/include/linux/device.h' l='430' type='struct subsys_private *'/>
<offset>896</offset>
<use f='linux-5.3.1/drivers/base/class.c' l='93' u='r' c='class_create_file_ns'/>
<use f='linux-5.3.1/drivers/base/class.c' l='104' u='r' c='class_remove_file_ns'/>
<use f='linux-5.3.1/drivers/base/class.c' l='110' u='r' c='class_get'/>
<use f='linux-5.3.1/drivers/base/class.c' l='117' u='r' c='class_put'/>
<use f='linux-5.3.1/drivers/base/class.c' l='143' u='r' c='class_add_groups'/>
<use f='linux-5.3.1/drivers/base/class.c' l='149' u='r' c='class_remove_groups'/>
<use f='linux-5.3.1/drivers/base/class.c' l='185' u='w' c='__class_register'/>
<use f='linux-5.3.1/drivers/base/class.c' l='202' u='r' c='class_unregister'/>
<use f='linux-5.3.1/drivers/base/class.c' l='287' u='r' c='class_dev_iter_init'/>
<use f='linux-5.3.1/drivers/base/class.c' l='360' u='r' c='class_for_each_device'/>
<use f='linux-5.3.1/drivers/base/class.c' l='407' u='r' c='class_find_device'/>
<use f='linux-5.3.1/drivers/base/class.c' l='439' u='r' c='class_interface_register'/>
<use f='linux-5.3.1/drivers/base/class.c' l='440' u='r' c='class_interface_register'/>
<use f='linux-5.3.1/drivers/base/class.c' l='447' u='r' c='class_interface_register'/>
<use f='linux-5.3.1/drivers/base/class.c' l='461' u='r' c='class_interface_unregister'/>
<use f='linux-5.3.1/drivers/base/class.c' l='469' u='r' c='class_interface_unregister'/>
<use f='linux-5.3.1/drivers/base/core.c' l='1733' u='r' c='class_dir_create_and_add'/>
<use f='linux-5.3.1/drivers/base/core.c' l='1758' u='r' c='get_device_parent'/>
<use f='linux-5.3.1/drivers/base/core.c' l='1777' u='r' c='get_device_parent'/>
<use f='linux-5.3.1/drivers/base/core.c' l='1778' u='r' c='get_device_parent'/>
<use f='linux-5.3.1/drivers/base/core.c' l='1778' u='r' c='get_device_parent'/>
<use f='linux-5.3.1/drivers/base/core.c' l='1778' u='r' c='get_device_parent'/>
<use f='linux-5.3.1/drivers/base/core.c' l='1778' u='r' c='get_device_parent'/>
<use f='linux-5.3.1/drivers/base/core.c' l='1783' u='r' c='get_device_parent'/>
<use f='linux-5.3.1/drivers/base/core.c' l='1809' u='r' c='live_in_glue_dir'/>
<use f='linux-5.3.1/drivers/base/core.c' l='1904' u='r' c='device_add_class_symlinks'/>
<use f='linux-5.3.1/drivers/base/core.c' l='1923' u='r' c='device_add_class_symlinks'/>
<use f='linux-5.3.1/drivers/base/core.c' l='1955' u='r' c='device_remove_class_symlinks'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2171' u='r' c='device_add'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2174' u='r' c='device_add'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2178' u='r' c='device_add'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2178' u='r' c='device_add'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2178' u='r' c='device_add'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2178' u='r' c='device_add'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2181' u='r' c='device_add'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2327' u='r' c='device_del'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2330' u='r' c='device_del'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2330' u='r' c='device_del'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2330' u='r' c='device_del'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2330' u='r' c='device_del'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2335' u='r' c='device_del'/>
<use f='linux-5.3.1/drivers/base/core.c' l='3020' u='r' c='device_rename'/>
