<dec f='linux-5.3.1/include/linux/cpufreq.h' l='283' type='int (*)(struct cpufreq_policy *)'/>
<offset>256</offset>
<doc f='linux-5.3.1/include/linux/cpufreq.h' l='282'>/* needed by all drivers */</doc>
<use f='linux-5.3.1/drivers/cpufreq/acpi-cpufreq.c' l='887' u='w'/>
<use f='linux-5.3.1/drivers/cpufreq/cpufreq.c' l='1327' u='r' c='cpufreq_online'/>
<use f='linux-5.3.1/drivers/cpufreq/cpufreq.c' l='2644' u='r' c='cpufreq_register_driver'/>
<use f='linux-5.3.1/drivers/cpufreq/intel_pstate.c' l='2218' u='w'/>
<use f='linux-5.3.1/drivers/cpufreq/intel_pstate.c' l='2353' u='w'/>
