<dec f='linux-5.3.1/include/linux/cpufreq.h' l='531' type='int (*)(struct cpufreq_policy *)'/>
<offset>128</offset>
<use f='linux-5.3.1/drivers/cpufreq/cpufreq.c' l='2193' u='r' c='cpufreq_init_governor'/>
<use f='linux-5.3.1/drivers/cpufreq/cpufreq.c' l='2194' u='r' c='cpufreq_init_governor'/>
<use f='linux-5.3.1/drivers/cpufreq/cpufreq_ondemand.c' l='401' macro='1' u='w'/>
<use f='linux-5.3.1/drivers/cpufreq/cpufreq_ondemand.c' l='401' macro='1' u='w'/>
<use f='linux-5.3.1/drivers/cpufreq/cpufreq_userspace.c' l='119' u='w'/>
