<dec f='linux-5.3.1/include/crypto/algapi.h' l='58' type='struct module *'/>
<use f='linux-5.3.1/crypto/internal.h' l='103' u='r' c='crypto_tmpl_get'/>
<use f='linux-5.3.1/crypto/internal.h' l='108' u='r' c='crypto_tmpl_put'/>
<offset>192</offset>
<use f='linux-5.3.1/crypto/algapi.c' l='463' u='r' c='crypto_register_template'/>
<use f='linux-5.3.1/crypto/algapi.c' l='570' u='r' c='crypto_register_instance'/>
<use f='linux-5.3.1/crypto/authenc.c' l='493' u='w'/>
<use f='linux-5.3.1/crypto/authencesn.c' l='508' u='w'/>
<use f='linux-5.3.1/crypto/cbc.c' l='83' u='w'/>
<use f='linux-5.3.1/crypto/ccm.c' l='976' u='w'/>
<use f='linux-5.3.1/crypto/ccm.c' l='980' u='w'/>
<use f='linux-5.3.1/crypto/ccm.c' l='984' u='w'/>
<use f='linux-5.3.1/crypto/ccm.c' l='988' u='w'/>
<use f='linux-5.3.1/crypto/ccm.c' l='976' u='w'/>
<use f='linux-5.3.1/crypto/ccm.c' l='980' u='w'/>
<use f='linux-5.3.1/crypto/ccm.c' l='984' u='w'/>
<use f='linux-5.3.1/crypto/ccm.c' l='988' u='w'/>
<use f='linux-5.3.1/crypto/cmac.c' l='298' u='w'/>
<use f='linux-5.3.1/crypto/ctr.c' l='362' u='w'/>
<use f='linux-5.3.1/crypto/ctr.c' l='366' u='w'/>
<use f='linux-5.3.1/crypto/ctr.c' l='362' u='w'/>
<use f='linux-5.3.1/crypto/ctr.c' l='366' u='w'/>
<use f='linux-5.3.1/crypto/echainiv.c' l='159' u='w'/>
<use f='linux-5.3.1/crypto/gcm.c' l='1205' u='w'/>
<use f='linux-5.3.1/crypto/gcm.c' l='1209' u='w'/>
<use f='linux-5.3.1/crypto/gcm.c' l='1213' u='w'/>
<use f='linux-5.3.1/crypto/gcm.c' l='1217' u='w'/>
<use f='linux-5.3.1/crypto/gcm.c' l='1205' u='w'/>
<use f='linux-5.3.1/crypto/gcm.c' l='1209' u='w'/>
<use f='linux-5.3.1/crypto/gcm.c' l='1213' u='w'/>
<use f='linux-5.3.1/crypto/gcm.c' l='1217' u='w'/>
<use f='linux-5.3.1/crypto/hmac.c' l='246' u='w'/>
<use f='linux-5.3.1/crypto/rsa-pkcs1pad.c' l='707' u='w'/>
<use f='linux-5.3.1/crypto/seqiv.c' l='196' u='w'/>
