<dec f='linux-5.3.1/include/linux/device.h' l='991' type='struct device_private *'/>
<offset>576</offset>
<use f='linux-5.3.1/drivers/base/bus.c' l='302' u='r' c='bus_for_each_dev'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='336' u='r' c='bus_find_device'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='389' u='r' c='subsys_find_device_by_id'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='486' u='r' c='bus_add_device'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='551' u='r' c='bus_remove_device'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='552' u='r' c='bus_remove_device'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='967' u='r' c='device_insertion_sort_klist'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='968' u='r' c='device_insertion_sort_klist'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='972' u='r' c='device_insertion_sort_klist'/>
<use f='linux-5.3.1/drivers/base/bus.c' l='1016' u='r' c='subsys_dev_iter_init'/>
<use f='linux-5.3.1/drivers/base/class.c' l='286' u='r' c='class_dev_iter_init'/>
<use f='linux-5.3.1/drivers/base/core.c' l='1046' u='r' c='device_release'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2025' u='w' c='device_private_init'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2025' u='r' c='device_private_init'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2026' u='r' c='device_private_init'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2028' u='r' c='device_private_init'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2029' u='r' c='device_private_init'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2031' u='r' c='device_private_init'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2074' u='r' c='device_add'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2167' u='r' c='device_add'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2168' u='r' c='device_add'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2173' u='r' c='device_add'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2211' u='r' c='device_add'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2212' u='w' c='device_add'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2279' u='r' c='kill_device'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2281' u='r' c='kill_device'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2318' u='r' c='device_del'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2334' u='r' c='device_del'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2466' u='r' c='device_for_each_child'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2469' u='r' c='device_for_each_child'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2496' u='r' c='device_for_each_child_reverse'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2499' u='r' c='device_for_each_child_reverse'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2533' u='r' c='device_find_child'/>
<use f='linux-5.3.1/drivers/base/core.c' l='2561' u='r' c='device_find_child_by_name'/>
<use f='linux-5.3.1/drivers/base/core.c' l='3091' u='r' c='device_move'/>
<use f='linux-5.3.1/drivers/base/core.c' l='3093' u='r' c='device_move'/>
<use f='linux-5.3.1/drivers/base/core.c' l='3094' u='r' c='device_move'/>
<use f='linux-5.3.1/drivers/base/core.c' l='3105' u='r' c='device_move'/>
<use f='linux-5.3.1/drivers/base/core.c' l='3108' u='r' c='device_move'/>
<use f='linux-5.3.1/drivers/base/core.c' l='3109' u='r' c='device_move'/>
<use f='linux-5.3.1/drivers/base/dd.c' l='93' u='r' c='deferred_probe_work_func'/>
<use f='linux-5.3.1/drivers/base/dd.c' l='93' u='r' c='deferred_probe_work_func'/>
<use f='linux-5.3.1/drivers/base/dd.c' l='93' u='r' c='deferred_probe_work_func'/>
<use f='linux-5.3.1/drivers/base/dd.c' l='126' u='r' c='driver_deferred_probe_add'/>
<use f='linux-5.3.1/drivers/base/dd.c' l='128' u='r' c='driver_deferred_probe_add'/>
<use f='linux-5.3.1/drivers/base/dd.c' l='136' u='r' c='driver_deferred_probe_del'/>
<use f='linux-5.3.1/drivers/base/dd.c' l='138' u='r' c='driver_deferred_probe_del'/>
<use f='linux-5.3.1/drivers/base/dd.c' l='364' u='r' c='device_is_bound'/>
<use f='linux-5.3.1/drivers/base/dd.c' l='364' u='r' c='device_is_bound'/>
<use f='linux-5.3.1/drivers/base/dd.c' l='378' u='r' c='driver_bound'/>
<use f='linux-5.3.1/drivers/base/dd.c' l='836' u='r' c='__device_attach_async_helper'/>
<use f='linux-5.3.1/drivers/base/dd.c' l='982' u='r' c='device_driver_attach'/>
<use f='linux-5.3.1/drivers/base/dd.c' l='998' u='r' c='__driver_attach_async_helper'/>
<use f='linux-5.3.1/drivers/base/dd.c' l='1004' u='r' c='__driver_attach_async_helper'/>
<use f='linux-5.3.1/drivers/base/dd.c' l='1053' u='r' c='__driver_attach'/>
<use f='linux-5.3.1/drivers/base/dd.c' l='1133' u='r' c='__device_release_driver'/>
<use f='linux-5.3.1/drivers/base/driver.c' l='52' u='r' c='driver_for_each_device'/>
<use f='linux-5.3.1/drivers/base/driver.c' l='86' u='r' c='driver_find_device'/>
