<dec f='linux-5.3.1/include/crypto/drbg.h' l='110' type='unsigned char *'/>
<use f='linux-5.3.1/crypto/drbg.c' l='664' u='r' c='drbg_hmac_update'/>
<use f='linux-5.3.1/crypto/drbg.c' l='668' u='r' c='drbg_hmac_update'/>
<use f='linux-5.3.1/crypto/drbg.c' l='677' u='r' c='drbg_hmac_update'/>
<use f='linux-5.3.1/crypto/drbg.c' l='692' u='r' c='drbg_hmac_update'/>
<use f='linux-5.3.1/crypto/drbg.c' l='722' u='r' c='drbg_hmac_generate'/>
<use f='linux-5.3.1/crypto/drbg.c' l='727' u='r' c='drbg_hmac_generate'/>
<use f='linux-5.3.1/crypto/drbg.c' l='734' u='r' c='drbg_hmac_generate'/>
<use f='linux-5.3.1/crypto/drbg.c' l='1192' u='r' c='drbg_seed'/>
<use f='linux-5.3.1/crypto/drbg.c' l='1211' u='w' c='drbg_dealloc_state'/>
<use f='linux-5.3.1/crypto/drbg.c' l='1266' u='w' c='drbg_alloc_state'/>
<offset>256</offset>
<doc f='linux-5.3.1/include/crypto/drbg.h' l='110'>/* internal state 10.1.1.1 1a) */</doc>
