<dec f='linux-5.3.1/include/drm/drm_fourcc.h' l='81' type='u8 [3]'/>
<offset>0</offset>
<doc f='linux-5.3.1/include/drm/drm_fourcc.h' l='73'>/**
		 * @cpp:
		 *
		 * Number of bytes per pixel (per plane), this is aliased with
		 * @char_per_block. It is deprecated in favour of using the
		 * triplet @char_per_block, @block_w, @block_h for better
		 * describing the pixel format.
		 */</doc>
<use f='linux-5.3.1/drivers/gpu/drm/drm_client.c' l='267' u='r' c='drm_client_buffer_create'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_client.c' l='370' u='r' c='drm_client_buffer_addfb'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fb_helper.c' l='385' u='r' c='drm_fb_helper_dirty_blit_real'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fb_helper.c' l='1323' u='r' c='drm_fb_helper_check_var'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fb_helper.c' l='1330' u='r' c='drm_fb_helper_check_var'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fb_helper.c' l='1681' u='r' c='drm_fb_helper_fill_var'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_format_helper.c' l='39' u='r' c='drm_fb_memcpy'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_format_helper.c' l='66' u='r' c='drm_fb_memcpy_dstclip'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='160' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='161' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='162' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='163' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='164' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='165' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='166' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='167' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='168' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='169' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='170' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='171' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='172' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='173' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='174' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='175' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='176' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='177' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='178' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='179' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='180' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='181' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='182' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='183' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='184' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='185' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='186' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='187' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='188' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='189' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='190' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='191' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='192' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='193' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='194' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='195' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='196' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='197' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='198' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='199' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='200' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='201' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='202' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='203' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='204' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='205' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='206' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='207' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='208' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='209' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='210' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='211' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='212' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='213' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='214' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='215' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='216' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='217' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='218' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='219' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='220' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='221' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='222' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='223' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='224' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='225' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='226' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='227' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='228' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='229' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='230' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='231' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='232' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='233' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='234' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='235' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='236' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='237' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='238' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='239' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='240' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='241' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='242' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='269' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='272' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='275' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='160' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='161' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='162' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='163' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='164' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='165' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='166' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='167' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='168' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='169' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='170' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='171' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='172' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='173' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='174' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='175' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='176' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='177' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='178' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='179' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='180' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='181' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='182' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='183' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='184' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='185' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='186' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='187' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='188' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='189' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='190' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='191' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='192' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='193' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='194' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='195' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='196' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='197' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='198' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='199' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='200' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='201' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='202' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='203' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='204' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='205' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='206' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='207' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='208' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='209' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='210' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='211' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='212' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='213' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='214' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='215' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='216' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='217' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='218' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='219' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='220' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='221' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='222' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='223' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='224' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='225' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='226' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='227' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='228' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='229' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='230' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='231' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='232' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='233' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='234' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='235' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='236' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='237' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='238' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='239' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='240' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='241' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='242' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='269' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='272' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_fourcc.c' l='275' u='w' c='__drm_format_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/drm_framebuffer.c' l='533' u='r' c='drm_mode_getfb'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_atomic_plane.c' l='126' u='r' c='intel_plane_data_rate'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_display.c' l='1915' u='r' c='intel_tile_width_bytes'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_display.c' l='1972' u='r' c='intel_tile_dims'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_display.c' l='2210' u='r' c='intel_fb_xy_to_linear'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_display.c' l='2270' u='r' c='intel_adjust_aligned_offset'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_display.c' l='2338' u='r' c='intel_compute_aligned_offset'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_display.c' l='2468' u='w'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_display.c' l='2470' u='w'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_display.c' l='2472' u='w'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_display.c' l='2474' u='w'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_display.c' l='2468' u='w'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_display.c' l='2470' u='w'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_display.c' l='2472' u='w'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_display.c' l='2474' u='w'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_display.c' l='2658' u='r' c='intel_fill_fb_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_display.c' l='2843' u='r' c='intel_plane_remap_gtt'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_display.c' l='3289' u='r' c='skl_max_plane_width'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_display.c' l='3314' u='r' c='glk_max_plane_width'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_display.c' l='3429' u='r' c='skl_check_main_surface'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_display.c' l='8516' u='r' c='i9xx_get_initial_plane_config'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_display.c' l='9756' u='r' c='skylake_get_initial_plane_config'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_display.c' l='10353' u='r' c='intel_cursor_base'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_display.c' l='10731' u='r' c='i9xx_check_cursor'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_fbc.c' l='175' u='r' c='g4x_fbc_activate'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_fbc.c' l='222' u='r' c='ilk_fbc_activate'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_fbc.c' l='305' u='r' c='gen7_fbc_activate'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_fbc.c' l='501' u='r' c='intel_fbc_alloc_cfb'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_fbdev.c' l='376' u='r' c='intel_fbdev_init_bios'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_fbdev.c' l='392' u='r' c='intel_fbdev_init_bios'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_fbdev.c' l='413' u='r' c='intel_fbdev_init_bios'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_sprite.c' l='339' u='r' c='skl_plane_max_stride'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_sprite.c' l='1353' u='r' c='g4x_sprite_check_scaling'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_debugfs.c' l='1634' u='r' c='i915_gem_framebuffer_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_debugfs.c' l='1652' u='r' c='i915_gem_framebuffer_info'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/intel_pm.c' l='876' u='r' c='pineview_update_wm'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/intel_pm.c' l='1134' u='r' c='g4x_compute_wm'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/intel_pm.c' l='1627' u='r' c='vlv_compute_wm_level'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/intel_pm.c' l='2219' u='r' c='i965_update_wm'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/intel_pm.c' l='2302' u='r' c='i9xx_update_wm'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/intel_pm.c' l='2329' u='r' c='i9xx_update_wm'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/intel_pm.c' l='2381' u='r' c='i9xx_update_wm'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/intel_pm.c' l='2509' u='r' c='ilk_compute_pri_wm'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/intel_pm.c' l='2541' u='r' c='ilk_compute_spr_wm'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/intel_pm.c' l='2567' u='r' c='ilk_compute_cur_wm'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/intel_pm.c' l='2584' u='r' c='ilk_compute_fbc_wm'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/intel_pm.c' l='4171' u='r' c='skl_check_pipe_max_pixel_rate'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/intel_pm.c' l='4243' u='r' c='skl_plane_relative_data_rate'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/intel_pm.c' l='4674' u='r' c='skl_compute_wm_params'/>
