<dec f='linux-5.3.1/include/linux/edac.h' l='547' type='const char *'/>
<offset>4800</offset>
<use f='linux-5.3.1/drivers/edac/edac_mc.c' l='1066' u='r' c='edac_raw_mc_handle_error'/>
<use f='linux-5.3.1/drivers/edac/edac_mc.c' l='1074' u='r' c='edac_raw_mc_handle_error'/>
<use f='linux-5.3.1/drivers/edac/edac_mc.c' l='1112' u='w' c='edac_mc_handle_error'/>
<use f='linux-5.3.1/drivers/edac/edac_mc.c' l='1242' u='r' c='edac_mc_handle_error'/>
