<dec f='linux-5.3.1/kernel/trace/trace.h' l='1706' type='int (*)(struct event_trigger_ops *, struct event_trigger_data *)'/>
<offset>64</offset>
<use f='linux-5.3.1/kernel/trace/trace_events_trigger.c' l='540' u='r' c='register_trigger'/>
<use f='linux-5.3.1/kernel/trace/trace_events_trigger.c' l='541' u='r' c='register_trigger'/>
<use f='linux-5.3.1/kernel/trace/trace_events_trigger.c' l='985' u='w'/>
<use f='linux-5.3.1/kernel/trace/trace_events_trigger.c' l='992' u='w'/>
<use f='linux-5.3.1/kernel/trace/trace_events_trigger.c' l='999' u='w'/>
<use f='linux-5.3.1/kernel/trace/trace_events_trigger.c' l='1006' u='w'/>
<use f='linux-5.3.1/kernel/trace/trace_events_trigger.c' l='1188' u='w'/>
<use f='linux-5.3.1/kernel/trace/trace_events_trigger.c' l='1195' u='w'/>
<use f='linux-5.3.1/kernel/trace/trace_events_trigger.c' l='1313' u='w'/>
<use f='linux-5.3.1/kernel/trace/trace_events_trigger.c' l='1320' u='w'/>
<use f='linux-5.3.1/kernel/trace/trace_events_trigger.c' l='1327' u='w'/>
<use f='linux-5.3.1/kernel/trace/trace_events_trigger.c' l='1334' u='w'/>
<use f='linux-5.3.1/kernel/trace/trace_events_trigger.c' l='1505' u='r' c='event_enable_register_trigger'/>
<use f='linux-5.3.1/kernel/trace/trace_events_trigger.c' l='1506' u='r' c='event_enable_register_trigger'/>
