<dec f='linux-5.3.1/security/selinux/include/security.h' l='206' type='u32 [8]'/>
<use f='linux-5.3.1/security/selinux/avc.c' l='204' u='r' c='avc_xperms_has_perm'/>
<use f='linux-5.3.1/security/selinux/avc.c' l='207' u='r' c='avc_xperms_has_perm'/>
<use f='linux-5.3.1/security/selinux/avc.c' l='210' u='r' c='avc_xperms_has_perm'/>
<use f='linux-5.3.1/security/selinux/avc.c' l='218' u='w' c='avc_xperms_allow_perm'/>
<use f='linux-5.3.1/security/selinux/avc.c' l='221' u='w' c='avc_xperms_allow_perm'/>
<use f='linux-5.3.1/security/selinux/avc.c' l='258' u='r' c='avc_copy_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/avc.c' l='258' u='r' c='avc_copy_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/avc.c' l='259' u='r' c='avc_copy_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/avc.c' l='261' u='r' c='avc_copy_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/avc.c' l='261' u='r' c='avc_copy_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/avc.c' l='262' u='r' c='avc_copy_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/avc.c' l='264' u='r' c='avc_copy_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/avc.c' l='264' u='r' c='avc_copy_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/avc.c' l='265' u='r' c='avc_copy_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/avc.c' l='284' u='w' c='avc_quick_copy_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/avc.c' l='284' u='r' c='avc_quick_copy_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/avc.c' l='286' u='w' c='avc_quick_copy_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/avc.c' l='286' u='r' c='avc_quick_copy_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/avc.c' l='288' u='w' c='avc_quick_copy_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/avc.c' l='288' u='r' c='avc_quick_copy_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/avc.c' l='364' u='r' c='avc_xperms_populate'/>
<use f='linux-5.3.1/security/selinux/avc.c' l='364' u='r' c='avc_xperms_populate'/>
<use f='linux-5.3.1/security/selinux/avc.c' l='364' u='r' c='avc_xperms_populate'/>
<use f='linux-5.3.1/security/selinux/avc.c' l='1091' u='r' c='avc_has_extended_perms'/>
<offset>0</offset>
<use f='linux-5.3.1/security/selinux/ss/avtab.c' l='398' u='r' c='avtab_read_item'/>
<use f='linux-5.3.1/security/selinux/ss/avtab.c' l='398' u='r' c='avtab_read_item'/>
<use f='linux-5.3.1/security/selinux/ss/avtab.c' l='525' u='r' c='avtab_read_item'/>
<use f='linux-5.3.1/security/selinux/ss/avtab.c' l='525' u='r' c='avtab_read_item'/>
<use f='linux-5.3.1/security/selinux/ss/avtab.c' l='530' u='r' c='avtab_read_item'/>
<use f='linux-5.3.1/security/selinux/ss/avtab.c' l='530' u='r' c='avtab_read_item'/>
<use f='linux-5.3.1/security/selinux/ss/avtab.c' l='531' u='w' c='avtab_read_item'/>
<use f='linux-5.3.1/security/selinux/ss/avtab.c' l='602' u='r' c='avtab_write_item'/>
<use f='linux-5.3.1/security/selinux/ss/avtab.c' l='602' u='r' c='avtab_write_item'/>
<use f='linux-5.3.1/security/selinux/ss/avtab.c' l='621' u='r' c='avtab_write_item'/>
<use f='linux-5.3.1/security/selinux/ss/avtab.c' l='621' u='r' c='avtab_write_item'/>
<use f='linux-5.3.1/security/selinux/ss/avtab.c' l='622' u='r' c='avtab_write_item'/>
<use f='linux-5.3.1/security/selinux/ss/avtab.c' l='624' u='r' c='avtab_write_item'/>
<use f='linux-5.3.1/security/selinux/ss/avtab.c' l='624' u='r' c='avtab_write_item'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='596' u='r' c='services_compute_xperms_drivers'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='596' u='r' c='services_compute_xperms_drivers'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='597' u='w' c='services_compute_xperms_drivers'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='597' u='r' c='services_compute_xperms_drivers'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='600' u='w' c='services_compute_xperms_drivers'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='953' u='r' c='services_compute_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='963' u='r' c='services_compute_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='964' u='r' c='services_compute_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='967' u='r' c='services_compute_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='967' u='r' c='services_compute_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='968' u='w' c='services_compute_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='969' u='r' c='services_compute_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='974' u='r' c='services_compute_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='975' u='r' c='services_compute_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='978' u='r' c='services_compute_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='978' u='r' c='services_compute_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='979' u='w' c='services_compute_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='980' u='r' c='services_compute_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='985' u='r' c='services_compute_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='986' u='r' c='services_compute_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='989' u='r' c='services_compute_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='989' u='r' c='services_compute_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='990' u='w' c='services_compute_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='991' u='r' c='services_compute_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='1017' u='r' c='security_compute_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='1017' u='r' c='security_compute_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='1018' u='r' c='security_compute_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='1018' u='r' c='security_compute_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='1019' u='r' c='security_compute_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='1019' u='r' c='security_compute_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='1077' u='r' c='security_compute_xperms_decision'/>
<use f='linux-5.3.1/security/selinux/ss/services.c' l='1077' u='r' c='security_compute_xperms_decision'/>
