<dec f='linux-5.3.1/include/net/fib_rules.h' l='68' type='int (*)(struct fib_rule *, struct flowi *, int, struct fib_lookup_arg *)'/>
<offset>384</offset>
<use f='linux-5.3.1/net/core/fib_rules.c' l='133' u='r' c='__fib_rules_register'/>
<use f='linux-5.3.1/net/core/fib_rules.c' l='301' u='r' c='fib_rules_lookup'/>
<use f='linux-5.3.1/net/ipv4/fib_rules.c' l='373' u='w'/>
