<dec f='linux-5.3.1/include/net/flow_offload.h' l='216' type='struct flow_action'/>
<offset>192</offset>
<use f='linux-5.3.1/net/core/ethtool.c' l='3081' u='m' c='ethtool_rx_flow_rule_create'/>
<use f='linux-5.3.1/net/core/flow_offload.c' l='10' u='m' c='flow_rule_alloc'/>
<use f='linux-5.3.1/net/core/flow_offload.c' l='15' u='m' c='flow_rule_alloc'/>
