<dec f='linux-5.3.1/include/net/genetlink.h' l='75' type='struct module *'/>
<use f='linux-5.3.1/drivers/acpi/event.c' l='87' u='w'/>
<offset>960</offset>
<use f='linux-5.3.1/drivers/thermal/thermal_core.c' l='1463' u='w'/>
<use f='linux-5.3.1/fs/quota/netlink.c' l='17' u='w'/>
<use f='linux-5.3.1/kernel/taskstats.c' l='681' u='w'/>
<use f='linux-5.3.1/net/ipv4/tcp_metrics.c' l='963' u='w'/>
<use f='linux-5.3.1/net/ipv6/seg6.c' l='432' u='w'/>
<use f='linux-5.3.1/net/netlabel/netlabel_calipso.c' l='344' u='w'/>
<use f='linux-5.3.1/net/netlabel/netlabel_cipso_v4.c' l='764' u='w'/>
<use f='linux-5.3.1/net/netlabel/netlabel_mgmt.c' l='825' u='w'/>
<use f='linux-5.3.1/net/netlabel/netlabel_unlabeled.c' l='1368' u='w'/>
<use f='linux-5.3.1/net/netlink/genetlink.c' l='563' u='r' c='genl_family_rcv_msg'/>
<use f='linux-5.3.1/net/netlink/genetlink.c' l='563' u='r' c='genl_family_rcv_msg'/>
<use f='linux-5.3.1/net/netlink/genetlink.c' l='577' u='r' c='genl_family_rcv_msg'/>
<use f='linux-5.3.1/net/netlink/genetlink.c' l='577' u='r' c='genl_family_rcv_msg'/>
<use f='linux-5.3.1/net/netlink/genetlink.c' l='979' u='w'/>
<use f='linux-5.3.1/net/wireless/nl80211.c' l='14559' u='w'/>
