<dec f='linux-5.3.1/include/sound/hda_codec.h' l='107' type='int (*)(struct hda_codec *)'/>
<offset>128</offset>
<use f='linux-5.3.1/sound/pci/hda/hda_codec.c' l='2900' u='r' c='hda_call_codec_resume'/>
<use f='linux-5.3.1/sound/pci/hda/hda_codec.c' l='2901' u='r' c='hda_call_codec_resume'/>
<use f='linux-5.3.1/sound/pci/hda/hda_codec.c' l='3051' u='r' c='snd_hda_codec_build_controls'/>
<use f='linux-5.3.1/sound/pci/hda/hda_codec.c' l='3052' u='r' c='snd_hda_codec_build_controls'/>
