<dec f='linux-5.3.1/include/linux/hw_random.h' l='41' type='int (*)(struct hwrng *)'/>
<use f='linux-5.3.1/drivers/char/hw_random/core.c' l='146' u='r' c='hwrng_init'/>
<use f='linux-5.3.1/drivers/char/hw_random/core.c' l='149' u='r' c='hwrng_init'/>
<use f='linux-5.3.1/drivers/char/hw_random/core.c' l='499' u='r' c='hwrng_register'/>
<offset>64</offset>
<use f='linux-5.3.1/drivers/char/hw_random/via-rng.c' l='189' u='w'/>
