<dec f='linux-5.3.1/net/mac80211/ieee80211_i.h' l='428' type='enum (anonymous enum at /home/woboq/linux-5.3.1/net/mac80211/ieee80211_i.h:424:2)'/>
<offset>160</offset>
<use f='linux-5.3.1/net/mac80211/cfg.c' l='3737' u='w' c='ieee80211_del_tx_ts'/>
<use f='linux-5.3.1/net/mac80211/mlme.c' l='1848' u='r' c='__ieee80211_sta_handle_tspec_ac_params'/>
<use f='linux-5.3.1/net/mac80211/mlme.c' l='1855' u='w' c='__ieee80211_sta_handle_tspec_ac_params'/>
<use f='linux-5.3.1/net/mac80211/mlme.c' l='1859' u='r' c='__ieee80211_sta_handle_tspec_ac_params'/>
<use f='linux-5.3.1/net/mac80211/mlme.c' l='1866' u='w' c='__ieee80211_sta_handle_tspec_ac_params'/>
<use f='linux-5.3.1/net/mac80211/mlme.c' l='1872' u='w' c='__ieee80211_sta_handle_tspec_ac_params'/>
<use f='linux-5.3.1/net/mac80211/mlme.c' l='1896' u='w' c='__ieee80211_sta_handle_tspec_ac_params'/>
<use f='linux-5.3.1/net/mac80211/mlme.c' l='2437' u='w' c='ieee80211_sta_tx_wmm_ac_notify'/>
<use f='linux-5.3.1/net/mac80211/mlme.c' l='2449' u='w' c='ieee80211_sta_tx_wmm_ac_notify'/>
