<dec f='linux-5.3.1/include/linux/ieee80211.h' l='1042' type='struct (anonymous struct at /home/woboq/linux-5.3.1/./include/linux/ieee80211.h:945:3)'/>
<use f='linux-5.3.1/include/linux/ieee80211.h' l='3157' u='m' c='ieee80211_is_public_action'/>
<use f='linux-5.3.1/include/linux/ieee80211.h' l='3173' u='m' c='_ieee80211_is_group_privacy_action'/>
<use f='linux-5.3.1/include/linux/ieee80211.h' l='3174' u='m' c='_ieee80211_is_group_privacy_action'/>
<use f='linux-5.3.1/include/linux/ieee80211.h' l='3272' u='m' c='ieee80211_action_contains_tpc'/>
<use f='linux-5.3.1/include/linux/ieee80211.h' l='3286' u='m' c='ieee80211_action_contains_tpc'/>
<use f='linux-5.3.1/include/linux/ieee80211.h' l='3287' u='m' c='ieee80211_action_contains_tpc'/>
<use f='linux-5.3.1/include/linux/ieee80211.h' l='3291' u='m' c='ieee80211_action_contains_tpc'/>
<use f='linux-5.3.1/include/linux/ieee80211.h' l='3295' u='m' c='ieee80211_action_contains_tpc'/>
<use f='linux-5.3.1/include/linux/ieee80211.h' l='3296' u='m' c='ieee80211_action_contains_tpc'/>
<offset>0</offset>
<use f='linux-5.3.1/net/mac80211/agg-rx.c' l='211' u='m' c='ieee80211_send_addba_resp'/>
<use f='linux-5.3.1/net/mac80211/agg-rx.c' l='212' u='m' c='ieee80211_send_addba_resp'/>
<use f='linux-5.3.1/net/mac80211/agg-rx.c' l='213' u='m' c='ieee80211_send_addba_resp'/>
<use f='linux-5.3.1/net/mac80211/agg-rx.c' l='214' u='m' c='ieee80211_send_addba_resp'/>
<use f='linux-5.3.1/net/mac80211/agg-rx.c' l='221' u='m' c='ieee80211_send_addba_resp'/>
<use f='linux-5.3.1/net/mac80211/agg-rx.c' l='222' u='m' c='ieee80211_send_addba_resp'/>
<use f='linux-5.3.1/net/mac80211/agg-rx.c' l='223' u='m' c='ieee80211_send_addba_resp'/>
<use f='linux-5.3.1/net/mac80211/agg-rx.c' l='440' u='m' c='ieee80211_process_addba_request'/>
<use f='linux-5.3.1/net/mac80211/agg-rx.c' l='441' u='m' c='ieee80211_process_addba_request'/>
<use f='linux-5.3.1/net/mac80211/agg-rx.c' l='443' u='m' c='ieee80211_process_addba_request'/>
<use f='linux-5.3.1/net/mac80211/agg-rx.c' l='445' u='m' c='ieee80211_process_addba_request'/>
<use f='linux-5.3.1/net/mac80211/agg-tx.c' l='92' u='m' c='ieee80211_send_addba_request'/>
<use f='linux-5.3.1/net/mac80211/agg-tx.c' l='94' u='m' c='ieee80211_send_addba_request'/>
<use f='linux-5.3.1/net/mac80211/agg-tx.c' l='95' u='m' c='ieee80211_send_addba_request'/>
<use f='linux-5.3.1/net/mac80211/agg-tx.c' l='97' u='m' c='ieee80211_send_addba_request'/>
<use f='linux-5.3.1/net/mac80211/agg-tx.c' l='103' u='m' c='ieee80211_send_addba_request'/>
<use f='linux-5.3.1/net/mac80211/agg-tx.c' l='105' u='m' c='ieee80211_send_addba_request'/>
<use f='linux-5.3.1/net/mac80211/agg-tx.c' l='106' u='m' c='ieee80211_send_addba_request'/>
<use f='linux-5.3.1/net/mac80211/agg-tx.c' l='922' u='m' c='ieee80211_process_addba_resp'/>
<use f='linux-5.3.1/net/mac80211/agg-tx.c' l='938' u='m' c='ieee80211_process_addba_resp'/>
<use f='linux-5.3.1/net/mac80211/agg-tx.c' l='968' u='m' c='ieee80211_process_addba_resp'/>
<use f='linux-5.3.1/net/mac80211/agg-tx.c' l='985' u='m' c='ieee80211_process_addba_resp'/>
<use f='linux-5.3.1/net/mac80211/ht.c' l='437' u='m' c='ieee80211_send_delba'/>
<use f='linux-5.3.1/net/mac80211/ht.c' l='439' u='m' c='ieee80211_send_delba'/>
<use f='linux-5.3.1/net/mac80211/ht.c' l='440' u='m' c='ieee80211_send_delba'/>
<use f='linux-5.3.1/net/mac80211/ht.c' l='444' u='m' c='ieee80211_send_delba'/>
<use f='linux-5.3.1/net/mac80211/ht.c' l='445' u='m' c='ieee80211_send_delba'/>
<use f='linux-5.3.1/net/mac80211/ht.c' l='457' u='m' c='ieee80211_process_delba'/>
<use f='linux-5.3.1/net/mac80211/ht.c' l='464' u='m' c='ieee80211_process_delba'/>
<use f='linux-5.3.1/net/mac80211/ht.c' l='508' u='m' c='ieee80211_send_smps_action'/>
<use f='linux-5.3.1/net/mac80211/ht.c' l='509' u='m' c='ieee80211_send_smps_action'/>
<use f='linux-5.3.1/net/mac80211/ht.c' l='516' u='m' c='ieee80211_send_smps_action'/>
<use f='linux-5.3.1/net/mac80211/ht.c' l='520' u='m' c='ieee80211_send_smps_action'/>
<use f='linux-5.3.1/net/mac80211/ht.c' l='524' u='m' c='ieee80211_send_smps_action'/>
<use f='linux-5.3.1/net/mac80211/ibss.c' l='926' u='m' c='ieee80211_rx_mgmt_spectrum_mgmt'/>
<use f='linux-5.3.1/net/mac80211/ibss.c' l='931' u='m' c='ieee80211_rx_mgmt_spectrum_mgmt'/>
<use f='linux-5.3.1/net/mac80211/ibss.c' l='1643' u='m' c='ieee80211_ibss_rx_queued_mgmt'/>
<use f='linux-5.3.1/net/mac80211/ibss.c' l='1653' u='m' c='ieee80211_ibss_rx_queued_mgmt'/>
<use f='linux-5.3.1/net/mac80211/iface.c' l='1250' u='m' c='ieee80211_iface_work'/>
<use f='linux-5.3.1/net/mac80211/iface.c' l='1256' u='m' c='ieee80211_iface_work'/>
<use f='linux-5.3.1/net/mac80211/iface.c' l='1276' u='m' c='ieee80211_iface_work'/>
<use f='linux-5.3.1/net/mac80211/iface.c' l='1277' u='m' c='ieee80211_iface_work'/>
<use f='linux-5.3.1/net/mac80211/iface.c' l='1285' u='m' c='ieee80211_iface_work'/>
<use f='linux-5.3.1/net/mac80211/mlme.c' l='4093' u='m' c='ieee80211_sta_rx_queued_mgmt'/>
<use f='linux-5.3.1/net/mac80211/mlme.c' l='4103' u='m' c='ieee80211_sta_rx_queued_mgmt'/>
<use f='linux-5.3.1/net/mac80211/mlme.c' l='4113' u='m' c='ieee80211_sta_rx_queued_mgmt'/>
<use f='linux-5.3.1/net/mac80211/mlme.c' l='4126' u='m' c='ieee80211_sta_rx_queued_mgmt'/>
<use f='linux-5.3.1/net/mac80211/mlme.c' l='4134' u='m' c='ieee80211_sta_rx_queued_mgmt'/>
<use f='linux-5.3.1/net/mac80211/offchannel.c' l='821' u='m' c='ieee80211_mgmt_tx'/>
<use f='linux-5.3.1/net/mac80211/offchannel.c' l='822' u='m' c='ieee80211_mgmt_tx'/>
<use f='linux-5.3.1/net/mac80211/offchannel.c' l='823' u='m' c='ieee80211_mgmt_tx'/>
<use f='linux-5.3.1/net/mac80211/rx.c' l='1084' u='m' c='ieee80211_rx_mesh_check'/>
<use f='linux-5.3.1/net/mac80211/rx.c' l='2979' u='m' c='ieee80211_process_sa_query_req'/>
<use f='linux-5.3.1/net/mac80211/rx.c' l='2995' u='m' c='ieee80211_process_sa_query_req'/>
<use f='linux-5.3.1/net/mac80211/rx.c' l='2996' u='m' c='ieee80211_process_sa_query_req'/>
<use f='linux-5.3.1/net/mac80211/rx.c' l='2997' u='m' c='ieee80211_process_sa_query_req'/>
<use f='linux-5.3.1/net/mac80211/rx.c' l='2998' u='m' c='ieee80211_process_sa_query_req'/>
<use f='linux-5.3.1/net/mac80211/rx.c' l='2999' u='m' c='ieee80211_process_sa_query_req'/>
<use f='linux-5.3.1/net/mac80211/rx.c' l='3059' u='m' c='ieee80211_rx_h_action'/>
<use f='linux-5.3.1/net/mac80211/rx.c' l='3060' u='m' c='ieee80211_rx_h_action'/>
<use f='linux-5.3.1/net/mac80211/rx.c' l='3061' u='m' c='ieee80211_rx_h_action'/>
<use f='linux-5.3.1/net/mac80211/rx.c' l='3064' u='m' c='ieee80211_rx_h_action'/>
<use f='linux-5.3.1/net/mac80211/rx.c' l='3081' u='m' c='ieee80211_rx_h_action'/>
<use f='linux-5.3.1/net/mac80211/rx.c' l='3088' u='m' c='ieee80211_rx_h_action'/>
<use f='linux-5.3.1/net/mac80211/rx.c' l='3122' u='m' c='ieee80211_rx_h_action'/>
<use f='linux-5.3.1/net/mac80211/rx.c' l='3171' u='m' c='ieee80211_rx_h_action'/>
<use f='linux-5.3.1/net/mac80211/rx.c' l='3190' u='m' c='ieee80211_rx_h_action'/>
<use f='linux-5.3.1/net/mac80211/rx.c' l='3218' u='m' c='ieee80211_rx_h_action'/>
<use f='linux-5.3.1/net/mac80211/rx.c' l='3221' u='m' c='ieee80211_rx_h_action'/>
<use f='linux-5.3.1/net/mac80211/rx.c' l='3226' u='m' c='ieee80211_rx_h_action'/>
<use f='linux-5.3.1/net/mac80211/rx.c' l='3231' u='m' c='ieee80211_rx_h_action'/>
<use f='linux-5.3.1/net/mac80211/rx.c' l='3244' u='m' c='ieee80211_rx_h_action'/>
<use f='linux-5.3.1/net/mac80211/rx.c' l='3250' u='m' c='ieee80211_rx_h_action'/>
<use f='linux-5.3.1/net/mac80211/rx.c' l='3261' u='m' c='ieee80211_rx_h_action'/>
<use f='linux-5.3.1/net/mac80211/rx.c' l='3287' u='m' c='ieee80211_rx_h_action'/>
<use f='linux-5.3.1/net/mac80211/rx.c' l='3290' u='m' c='ieee80211_rx_h_action'/>
<use f='linux-5.3.1/net/mac80211/rx.c' l='3300' u='m' c='ieee80211_rx_h_action'/>
<use f='linux-5.3.1/net/mac80211/rx.c' l='3303' u='m' c='ieee80211_rx_h_action'/>
<use f='linux-5.3.1/net/mac80211/rx.c' l='3322' u='m' c='ieee80211_rx_h_action'/>
<use f='linux-5.3.1/net/mac80211/rx.c' l='3417' u='m' c='ieee80211_rx_h_action_return'/>
<use f='linux-5.3.1/net/mac80211/rx.c' l='3425' u='m' c='ieee80211_rx_h_action_return'/>
<use f='linux-5.3.1/net/mac80211/spectmgmt.c' l='208' u='m' c='ieee80211_send_refuse_measurement_request'/>
<use f='linux-5.3.1/net/mac80211/spectmgmt.c' l='209' u='m' c='ieee80211_send_refuse_measurement_request'/>
<use f='linux-5.3.1/net/mac80211/spectmgmt.c' l='210' u='m' c='ieee80211_send_refuse_measurement_request'/>
<use f='linux-5.3.1/net/mac80211/spectmgmt.c' l='212' u='m' c='ieee80211_send_refuse_measurement_request'/>
<use f='linux-5.3.1/net/mac80211/spectmgmt.c' l='214' u='m' c='ieee80211_send_refuse_measurement_request'/>
<use f='linux-5.3.1/net/mac80211/spectmgmt.c' l='215' u='m' c='ieee80211_send_refuse_measurement_request'/>
<use f='linux-5.3.1/net/mac80211/spectmgmt.c' l='218' u='m' c='ieee80211_send_refuse_measurement_request'/>
<use f='linux-5.3.1/net/mac80211/spectmgmt.c' l='220' u='m' c='ieee80211_send_refuse_measurement_request'/>
<use f='linux-5.3.1/net/mac80211/spectmgmt.c' l='221' u='m' c='ieee80211_send_refuse_measurement_request'/>
<use f='linux-5.3.1/net/mac80211/spectmgmt.c' l='223' u='m' c='ieee80211_send_refuse_measurement_request'/>
<use f='linux-5.3.1/net/mac80211/spectmgmt.c' l='240' u='m' c='ieee80211_process_measurement_req'/>
<use f='linux-5.3.1/net/mac80211/spectmgmt.c' l='242' u='m' c='ieee80211_process_measurement_req'/>
<use f='linux-5.3.1/net/mac80211/status.c' l='210' u='m' c='ieee80211_frame_acked'/>
<use f='linux-5.3.1/net/mac80211/status.c' l='211' u='m' c='ieee80211_frame_acked'/>
<use f='linux-5.3.1/net/mac80211/status.c' l='215' u='m' c='ieee80211_frame_acked'/>
<use f='linux-5.3.1/net/mac80211/tdls.c' l='844' u='m' c='ieee80211_prep_tdls_direct'/>
<use f='linux-5.3.1/net/mac80211/tdls.c' l='845' u='m' c='ieee80211_prep_tdls_direct'/>
<use f='linux-5.3.1/net/mac80211/tdls.c' l='846' u='m' c='ieee80211_prep_tdls_direct'/>
<use f='linux-5.3.1/net/mac80211/tdls.c' l='848' u='m' c='ieee80211_prep_tdls_direct'/>
<use f='linux-5.3.1/net/mac80211/tdls.c' l='850' u='m' c='ieee80211_prep_tdls_direct'/>
<use f='linux-5.3.1/net/mac80211/util.c' l='3398' u='m' c='ieee80211_send_action_csa'/>
<use f='linux-5.3.1/net/mac80211/util.c' l='3426' u='m' c='ieee80211_send_action_csa'/>
<use f='linux-5.3.1/net/mac80211/util.c' l='3427' u='m' c='ieee80211_send_action_csa'/>
<use f='linux-5.3.1/net/mac80211/vht.c' l='554' u='m' c='ieee80211_process_mu_groups'/>
<use f='linux-5.3.1/net/mac80211/vht.c' l='556' u='m' c='ieee80211_process_mu_groups'/>
<use f='linux-5.3.1/net/mac80211/vht.c' l='561' u='m' c='ieee80211_process_mu_groups'/>
<use f='linux-5.3.1/net/mac80211/vht.c' l='564' u='m' c='ieee80211_process_mu_groups'/>
<use f='linux-5.3.1/net/wireless/mlme.c' l='609' u='m' c='cfg80211_mlme_mgmt_tx'/>
<use f='linux-5.3.1/net/wireless/mlme.c' l='681' u='m' c='cfg80211_mlme_mgmt_tx'/>
