<dec f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_dvo_dev.h' l='52' type='bool (*)(struct intel_dvo_device *, struct i2c_adapter *)'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/dvo_ch7017.c' l='407' u='w'/>
<offset>0</offset>
<doc f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_dvo_dev.h' l='48'>/*
	 * Initialize the device at startup time.
	 * Returns NULL if the device does not exist.
	 */</doc>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/dvo_ch7xxx.c' l='359' u='w'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/dvo_ivch.c' l='495' u='w'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/dvo_ns2501.c' l='703' u='w'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/dvo_sil164.c' l='272' u='w'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/dvo_tfp410.c' l='311' u='w'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_dvo.c' l='488' u='r' c='intel_dvo_init'/>
