<dec f='linux-5.3.1/include/linux/interval_tree.h' l='8' type='struct rb_node'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/gem/i915_gem_userptr.c' l='49' u='a' c='add_object'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/gem/i915_gem_userptr.c' l='49' u='a' c='add_object'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/gem/i915_gem_userptr.c' l='55' u='a' c='del_object'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/gem/i915_gem_userptr.c' l='55' u='a' c='del_object'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/gem/i915_gem_userptr.c' l='59' u='a' c='del_object'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/gem/i915_gem_userptr.c' l='59' u='a' c='del_object'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/gem/i915_gem_userptr.c' l='279' u='a' c='i915_gem_userptr_init__mmu_notifier'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/gem/i915_gem_userptr.c' l='279' u='a' c='i915_gem_userptr_init__mmu_notifier'/>
<offset>0</offset>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='m' c='interval_tree_compute_subtree_last'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='m' c='interval_tree_compute_subtree_last'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='m' c='interval_tree_compute_subtree_last'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='r' c='interval_tree_compute_subtree_last'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='m' c='interval_tree_compute_subtree_last'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='m' c='interval_tree_compute_subtree_last'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='m' c='interval_tree_compute_subtree_last'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='m' c='interval_tree_compute_subtree_last'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='r' c='interval_tree_compute_subtree_last'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='m' c='interval_tree_compute_subtree_last'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='r' c='interval_tree_augment_propagate'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='a' c='interval_tree_augment_propagate'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='r' c='interval_tree_augment_copy'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='r' c='interval_tree_augment_copy'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='r' c='interval_tree_augment_rotate'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='r' c='interval_tree_augment_rotate'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='r' c='interval_tree_insert'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='m' c='interval_tree_insert'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='m' c='interval_tree_insert'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='a' c='interval_tree_insert'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='a' c='interval_tree_insert'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='a' c='interval_tree_remove'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='m' c='interval_tree_subtree_search'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='m' c='interval_tree_subtree_search'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='m' c='interval_tree_subtree_search'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='r' c='interval_tree_subtree_search'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='m' c='interval_tree_subtree_search'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='m' c='interval_tree_subtree_search'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='m' c='interval_tree_subtree_search'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='m' c='interval_tree_subtree_search'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='r' c='interval_tree_subtree_search'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='m' c='interval_tree_subtree_search'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='r' c='interval_tree_iter_first'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='r' c='interval_tree_iter_first'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='m' c='interval_tree_iter_next'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='r' c='interval_tree_iter_next'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='a' c='interval_tree_iter_next'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='a' c='interval_tree_iter_next'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='r' c='interval_tree_iter_next'/>
<use f='linux-5.3.1/lib/interval_tree.c' l='10' u='m' c='interval_tree_iter_next'/>
