<dec f='linux-5.3.1/include/net/ip.h' l='122' type='struct sock *'/>
<offset>64</offset>
<use f='linux-5.3.1/net/ipv4/ip_input.c' l='157' u='r' c='ip_call_ra_chain'/>
<use f='linux-5.3.1/net/ipv4/ip_sockglue.c' l='354' u='r' c='ip_ra_control'/>
<use f='linux-5.3.1/net/ipv4/ip_sockglue.c' l='361' u='w' c='ip_ra_control'/>
<use f='linux-5.3.1/net/ipv4/ip_sockglue.c' l='381' u='w' c='ip_ra_control'/>
