<dec f='linux-5.3.1/include/linux/irqdesc.h' l='64' type='struct irqaction *'/>
<use f='linux-5.3.1/include/linux/irqdesc.h' l='186' u='r' c='irq_desc_has_action'/>
<offset>896</offset>
<doc f='linux-5.3.1/include/linux/irqdesc.h' l='64'>/* IRQ action list */</doc>
<use f='linux-5.3.1/kernel/irq/debug.h' l='24' u='r' c='print_irq_desc'/>
<use f='linux-5.3.1/kernel/irq/debug.h' l='25' u='r' c='print_irq_desc'/>
<use f='linux-5.3.1/kernel/irq/debug.h' l='27' u='r' c='print_irq_desc'/>
<use f='linux-5.3.1/kernel/irq/debug.h' l='27' u='r' c='print_irq_desc'/>
<use f='linux-5.3.1/kernel/irq/internals.h' l='271' u='r' c='irq_desc_is_chained'/>
<use f='linux-5.3.1/kernel/irq/internals.h' l='271' u='r' c='irq_desc_is_chained'/>
<use f='linux-5.3.1/kernel/irq/autoprobe.c' l='47' u='r' c='probe_irq_on'/>
<use f='linux-5.3.1/kernel/irq/autoprobe.c' l='70' u='r' c='probe_irq_on'/>
<use f='linux-5.3.1/kernel/irq/chip.c' l='470' u='r' c='handle_nested_irq'/>
<use f='linux-5.3.1/kernel/irq/chip.c' l='481' macro='1' u='r' c='handle_nested_irq'/>
<use f='linux-5.3.1/kernel/irq/chip.c' l='547' u='r' c='handle_simple_irq'/>
<use f='linux-5.3.1/kernel/irq/chip.c' l='584' u='r' c='handle_untracked_irq'/>
<use f='linux-5.3.1/kernel/irq/chip.c' l='644' u='r' c='handle_level_irq'/>
<use f='linux-5.3.1/kernel/irq/chip.c' l='714' u='r' c='handle_fasteoi_irq'/>
<use f='linux-5.3.1/kernel/irq/chip.c' l='753' u='r' c='handle_fasteoi_nmi'/>
<use f='linux-5.3.1/kernel/irq/chip.c' l='802' u='r' c='handle_edge_irq'/>
<use f='linux-5.3.1/kernel/irq/chip.c' l='814' u='r' c='handle_edge_irq'/>
<use f='linux-5.3.1/kernel/irq/chip.c' l='926' u='r' c='handle_percpu_devid_irq'/>
<use f='linux-5.3.1/kernel/irq/chip.c' l='969' u='r' c='handle_percpu_devid_fasteoi_nmi'/>
<use f='linux-5.3.1/kernel/irq/chip.c' l='1023' u='w' c='__irq_do_set_handler'/>
<use f='linux-5.3.1/kernel/irq/chip.c' l='1048' u='w' c='__irq_do_set_handler'/>
<use f='linux-5.3.1/kernel/irq/cpuhotplug.c' l='179' u='r' c='irq_restore_affinity_of_irq'/>
<use f='linux-5.3.1/kernel/irq/handle.c' l='145' macro='1' u='r' c='__handle_irq_event_percpu'/>
<use f='linux-5.3.1/kernel/irq/irqdesc.c' l='254' u='r' c='actions_show'/>
<use f='linux-5.3.1/kernel/irq/irqdomain.c' l='1419' u='r' c='irq_domain_push_irq'/>
<use f='linux-5.3.1/kernel/irq/irqdomain.c' l='1500' u='r' c='irq_domain_pop_irq'/>
<use f='linux-5.3.1/kernel/irq/manage.c' l='192' macro='1' u='r' c='irq_set_thread_affinity'/>
<use f='linux-5.3.1/kernel/irq/manage.c' l='755' u='r' c='can_request_irq'/>
<use f='linux-5.3.1/kernel/irq/manage.c' l='756' u='r' c='can_request_irq'/>
<use f='linux-5.3.1/kernel/irq/manage.c' l='1131' macro='1' u='r' c='irq_wake_thread'/>
<use f='linux-5.3.1/kernel/irq/manage.c' l='1380' u='r' c='__setup_irq'/>
<use f='linux-5.3.1/kernel/irq/manage.c' l='1396' u='a' c='__setup_irq'/>
<use f='linux-5.3.1/kernel/irq/manage.c' l='1629' u='r' c='__setup_irq'/>
<use f='linux-5.3.1/kernel/irq/manage.c' l='1703' u='a' c='__free_irq'/>
<use f='linux-5.3.1/kernel/irq/manage.c' l='1726' u='r' c='__free_irq'/>
<use f='linux-5.3.1/kernel/irq/manage.c' l='1796' u='r' c='__free_irq'/>
<use f='linux-5.3.1/kernel/irq/manage.c' l='1887' u='r' c='__cleanup_nmi'/>
<use f='linux-5.3.1/kernel/irq/manage.c' l='1888' u='r' c='__cleanup_nmi'/>
<use f='linux-5.3.1/kernel/irq/manage.c' l='1889' u='r' c='__cleanup_nmi'/>
<use f='linux-5.3.1/kernel/irq/manage.c' l='1890' u='r' c='__cleanup_nmi'/>
<use f='linux-5.3.1/kernel/irq/manage.c' l='1892' u='r' c='__cleanup_nmi'/>
<use f='linux-5.3.1/kernel/irq/manage.c' l='1893' u='w' c='__cleanup_nmi'/>
<use f='linux-5.3.1/kernel/irq/manage.c' l='2296' u='r' c='__free_percpu_irq'/>
<use f='linux-5.3.1/kernel/irq/manage.c' l='2309' u='w' c='__free_percpu_irq'/>
<use f='linux-5.3.1/kernel/irq/pm.c' l='72' u='r' c='suspend_device_irq'/>
<use f='linux-5.3.1/kernel/irq/pm.c' l='165' u='r' c='resume_irqs'/>
<use f='linux-5.3.1/kernel/irq/pm.c' l='166' u='r' c='resume_irqs'/>
<use f='linux-5.3.1/kernel/irq/proc.c' l='300' macro='1' u='r' c='name_unique'/>
<use f='linux-5.3.1/kernel/irq/proc.c' l='487' u='r' c='show_interrupts'/>
<use f='linux-5.3.1/kernel/irq/proc.c' l='516' u='r' c='show_interrupts'/>
<use f='linux-5.3.1/kernel/irq/spurious.c' l='51' u='r' c='irq_wait_for_poll'/>
<use f='linux-5.3.1/kernel/irq/spurious.c' l='88' u='r' c='try_one_irq'/>
<use f='linux-5.3.1/kernel/irq/spurious.c' l='109' u='r' c='try_one_irq'/>
<use f='linux-5.3.1/kernel/irq/spurious.c' l='214' macro='1' u='r' c='__report_bad_irq'/>
<use f='linux-5.3.1/kernel/irq/spurious.c' l='264' u='r' c='try_misrouted_irq'/>
