<dec f='linux-5.3.1/include/linux/kernfs.h' l='146' type='struct rb_node'/>
<offset>192</offset>
<use f='linux-5.3.1/fs/kernfs/dir.c' l='25' u='r' c='kernfs_link_sibling'/>
<use f='linux-5.3.1/fs/kernfs/dir.c' l='359' u='m' c='kernfs_link_sibling'/>
<use f='linux-5.3.1/fs/kernfs/dir.c' l='361' u='m' c='kernfs_link_sibling'/>
<use f='linux-5.3.1/fs/kernfs/dir.c' l='367' u='a' c='kernfs_link_sibling'/>
<use f='linux-5.3.1/fs/kernfs/dir.c' l='368' u='a' c='kernfs_link_sibling'/>
<use f='linux-5.3.1/fs/kernfs/dir.c' l='390' u='a' c='kernfs_unlink_sibling'/>
<use f='linux-5.3.1/fs/kernfs/dir.c' l='390' u='a' c='kernfs_unlink_sibling'/>
<use f='linux-5.3.1/fs/kernfs/dir.c' l='396' u='a' c='kernfs_unlink_sibling'/>
<use f='linux-5.3.1/fs/kernfs/dir.c' l='397' u='a' c='kernfs_unlink_sibling'/>
<use f='linux-5.3.1/fs/kernfs/dir.c' l='397' u='a' c='kernfs_unlink_sibling'/>
<use f='linux-5.3.1/fs/kernfs/dir.c' l='655' u='a' c='__kernfs_new_node'/>
<use f='linux-5.3.1/fs/kernfs/dir.c' l='655' u='a' c='__kernfs_new_node'/>
<use f='linux-5.3.1/fs/kernfs/dir.c' l='25' u='r' c='kernfs_find_ns'/>
<use f='linux-5.3.1/fs/kernfs/dir.c' l='25' u='r' c='kernfs_leftmost_descendant'/>
<use f='linux-5.3.1/fs/kernfs/dir.c' l='1236' u='a' c='kernfs_next_descendant_post'/>
<use f='linux-5.3.1/fs/kernfs/dir.c' l='25' u='r' c='kernfs_next_descendant_post'/>
<use f='linux-5.3.1/fs/kernfs/dir.c' l='1268' u='a' c='kernfs_activate'/>
<use f='linux-5.3.1/fs/kernfs/dir.c' l='1268' u='a' c='kernfs_activate'/>
<use f='linux-5.3.1/fs/kernfs/dir.c' l='1289' u='a' c='__kernfs_remove'/>
<use f='linux-5.3.1/fs/kernfs/dir.c' l='1289' u='a' c='__kernfs_remove'/>
<use f='linux-5.3.1/fs/kernfs/dir.c' l='1474' u='a' c='kernfs_remove_self'/>
<use f='linux-5.3.1/fs/kernfs/dir.c' l='1474' u='a' c='kernfs_remove_self'/>
<use f='linux-5.3.1/fs/kernfs/dir.c' l='25' u='r' c='kernfs_dir_pos'/>
<use f='linux-5.3.1/fs/kernfs/dir.c' l='1635' u='a' c='kernfs_dir_pos'/>
<use f='linux-5.3.1/fs/kernfs/dir.c' l='25' u='r' c='kernfs_dir_pos'/>
<use f='linux-5.3.1/fs/kernfs/dir.c' l='1650' u='a' c='kernfs_dir_next_pos'/>
<use f='linux-5.3.1/fs/kernfs/dir.c' l='25' u='r' c='kernfs_dir_next_pos'/>
