<dec f='linux-5.3.1/arch/x86/include/asm/i8259.h' l='64' type='void (*)(int)'/>
<offset>384</offset>
<use f='linux-5.3.1/arch/x86/kernel/apic/io_apic.c' l='2153' u='r' c='check_timer'/>
<use f='linux-5.3.1/arch/x86/kernel/apic/io_apic.c' l='2253' u='r' c='check_timer'/>
<use f='linux-5.3.1/arch/x86/kernel/i8259.c' l='404' u='w'/>
<use f='linux-5.3.1/arch/x86/kernel/i8259.c' l='417' u='w'/>
<use f='linux-5.3.1/arch/x86/kernel/irqinit.c' l='73' u='r' c='init_ISA_irqs'/>
