<dec f='linux-5.3.1/include/linux/binfmts.h' l='98' type='struct module *'/>
<offset>128</offset>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='93' u='w'/>
<use f='linux-5.3.1/fs/binfmt_misc.c' l='856' u='w'/>
<use f='linux-5.3.1/fs/binfmt_script.c' l='153' u='w'/>
<use f='linux-5.3.1/fs/exec.c' l='105' u='r' c='put_binfmt'/>
<use f='linux-5.3.1/fs/exec.c' l='159' u='r' c='__do_sys_uselib'/>
<use f='linux-5.3.1/fs/exec.c' l='1653' u='r' c='search_binary_handler'/>
<use f='linux-5.3.1/fs/exec.c' l='1937' u='r' c='set_binfmt'/>
<use f='linux-5.3.1/fs/exec.c' l='1941' u='r' c='set_binfmt'/>
<use f='linux-5.3.1/kernel/fork.c' l='1073' u='r' c='__mmput'/>
<use f='linux-5.3.1/kernel/fork.c' l='1353' u='r' c='dup_mm'/>
