<dec f='linux-5.3.1/include/linux/lsm_hooks.h' l='2102' type='int (*)(void)'/>
<use f='linux-5.3.1/security/commoncap.c' l='1373' u='w'/>
<offset>256</offset>
<doc f='linux-5.3.1/include/linux/lsm_hooks.h' l='2102'>/* Required. */</doc>
<use f='linux-5.3.1/security/integrity/iint.c' l='176' u='w'/>
<use f='linux-5.3.1/security/security.c' l='200' u='r' c='initialize_lsm'/>
<use f='linux-5.3.1/security/selinux/hooks.c' l='7050' u='w'/>
