<dec f='linux-5.3.1/include/linux/lsm_audit.h' l='29' type='struct sock *'/>
<use f='linux-5.3.1/security/lsm_audit.c' l='318' u='r' c='dump_common_audit_data'/>
<use f='linux-5.3.1/security/lsm_audit.c' l='319' u='r' c='dump_common_audit_data'/>
<offset>64</offset>
<use f='linux-5.3.1/security/selinux/hooks.c' l='4433' u='w' c='sock_has_perm'/>
<use f='linux-5.3.1/security/selinux/hooks.c' l='4836' u='w' c='selinux_socket_unix_stream_connect'/>
<use f='linux-5.3.1/security/selinux/hooks.c' l='4868' u='w' c='selinux_socket_unix_may_send'/>
<use f='linux-5.3.1/security/selinux/hooks.c' l='5178' u='w' c='selinux_sctp_assoc_request'/>
