<dec f='linux-5.3.1/drivers/md/md.h' l='551' type='int (*)(struct mddev *)'/>
<offset>384</offset>
<doc f='linux-5.3.1/drivers/md/md.h' l='547'>/*
	 * start up works that do NOT require md_thread. tasks that
	 * requires md_thread should go into start()
	 */</doc>
<use f='linux-5.3.1/drivers/md/md.c' l='3918' u='r' c='level_store'/>
<use f='linux-5.3.1/drivers/md/md.c' l='5645' u='r' c='md_run'/>
