<dec f='linux-5.3.1/include/linux/mempolicy.h' l='53' type='union (anonymous union at /home/woboq/linux-5.3.1/./include/linux/mempolicy.h:49:2)'/>
<offset>64</offset>
<use f='linux-5.3.1/mm/mempolicy.c' l='171' u='m' c='mpol_new_interleave'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='182' u='m' c='mpol_new_preferred'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='190' u='m' c='mpol_new_bind'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='307' u='m' c='mpol_rebind_nodemask'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='315' u='m' c='mpol_rebind_nodemask'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='327' u='m' c='mpol_rebind_preferred'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='333' u='m' c='mpol_rebind_preferred'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='335' u='m' c='mpol_rebind_preferred'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='335' u='m' c='mpol_rebind_preferred'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='841' u='m' c='get_policy_nodemask'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='845' u='m' c='get_policy_nodemask'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='931' u='m' c='do_get_mempolicy'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='1784' u='m' c='apply_policy_zone'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='1799' u='m' c='policy_nodemask'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='1800' u='m' c='policy_nodemask'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='1810' u='m' c='policy_node'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='1829' u='m' c='interleave_nodes'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='1856' u='m' c='mempolicy_slab_node'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='1872' u='m' c='mempolicy_slab_node'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='1888' u='m' c='offset_il_node'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='1896' u='m' c='offset_il_node'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='1898' u='m' c='offset_il_node'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='1954' u='m' c='huge_node'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='1990' u='m' c='init_nodemask_of_mempolicy'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='1997' u='m' c='init_nodemask_of_mempolicy'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='2043' u='m' c='mempolicy_nodemask_intersects'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='2223' u='m' c='__mpol_equal'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='2223' u='m' c='__mpol_equal'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='2228' u='m' c='__mpol_equal'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='2228' u='m' c='__mpol_equal'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='2372' u='m' c='mpol_misplaced'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='2383' u='m' c='mpol_misplaced'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='2388' u='m' c='mpol_misplaced'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='2591' u='m' c='mpol_set_shared_policy'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='2689' u='w' c='numa_policy_init'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='2849' u='m' c='mpol_parse_str'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='2851' u='m' c='mpol_parse_str'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='2904' u='m' c='mpol_to_str'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='2908' u='m' c='mpol_to_str'/>
