<dec f='linux-5.3.1/include/linux/mroute_base.h' l='151' type='struct (anonymous struct at /home/woboq/linux-5.3.1/./include/linux/mroute_base.h:141:3)'/>
<use f='linux-5.3.1/include/linux/mroute_base.h' l='160' u='m' c='mr_cache_put'/>
<use f='linux-5.3.1/include/linux/mroute_base.h' l='166' u='m' c='mr_cache_hold'/>
<offset>0</offset>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='814' u='m' c='ipmr_update_thresholds'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='815' u='m' c='ipmr_update_thresholds'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='816' u='m' c='ipmr_update_thresholds'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='821' u='m' c='ipmr_update_thresholds'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='822' u='m' c='ipmr_update_thresholds'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='823' u='m' c='ipmr_update_thresholds'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='824' u='m' c='ipmr_update_thresholds'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='825' u='m' c='ipmr_update_thresholds'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='828' u='m' c='ipmr_update_thresholds'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='983' u='m' c='ipmr_cache_alloc'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='984' u='m' c='ipmr_cache_alloc'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='986' u='m' c='ipmr_cache_alloc'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='1652' u='m' c='ipmr_ioctl'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='1653' u='m' c='ipmr_ioctl'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='1654' u='m' c='ipmr_ioctl'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='1727' u='m' c='ipmr_compat_ioctl'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='1728' u='m' c='ipmr_compat_ioctl'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='1729' u='m' c='ipmr_compat_ioctl'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='1959' u='m' c='ip_mr_forward'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='1960' u='m' c='ip_mr_forward'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='1961' u='m' c='ip_mr_forward'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='1971' u='m' c='ip_mr_forward'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='1992' u='m' c='ip_mr_forward'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='2001' u='m' c='ip_mr_forward'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='2003' u='m' c='ip_mr_forward'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='2003' u='m' c='ip_mr_forward'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='2005' u='m' c='ip_mr_forward'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='2024' u='m' c='ip_mr_forward'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='2034' u='m' c='ip_mr_forward'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='2035' u='m' c='ip_mr_forward'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='2039' u='m' c='ip_mr_forward'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='2999' u='m' c='ipmr_mfc_seq_show'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='3000' u='m' c='ipmr_mfc_seq_show'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='3001' u='m' c='ipmr_mfc_seq_show'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='3002' u='m' c='ipmr_mfc_seq_show'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='3003' u='m' c='ipmr_mfc_seq_show'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='3005' u='m' c='ipmr_mfc_seq_show'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='3008' u='m' c='ipmr_mfc_seq_show'/>
<use f='linux-5.3.1/net/ipv4/ipmr_base.c' l='86' u='m' c='mr_mfc_find_any_parent'/>
<use f='linux-5.3.1/net/ipv4/ipmr_base.c' l='100' u='m' c='mr_mfc_find_any'/>
<use f='linux-5.3.1/net/ipv4/ipmr_base.c' l='105' u='m' c='mr_mfc_find_any'/>
<use f='linux-5.3.1/net/ipv4/ipmr_base.c' l='235' u='m' c='mr_fill_mroute'/>
<use f='linux-5.3.1/net/ipv4/ipmr_base.c' l='235' u='m' c='mr_fill_mroute'/>
<use f='linux-5.3.1/net/ipv4/ipmr_base.c' l='236' u='m' c='mr_fill_mroute'/>
<use f='linux-5.3.1/net/ipv4/ipmr_base.c' l='246' u='m' c='mr_fill_mroute'/>
<use f='linux-5.3.1/net/ipv4/ipmr_base.c' l='255' u='m' c='mr_fill_mroute'/>
<use f='linux-5.3.1/net/ipv4/ipmr_base.c' l='255' u='m' c='mr_fill_mroute'/>
<use f='linux-5.3.1/net/ipv4/ipmr_base.c' l='255' u='m' c='mr_fill_mroute'/>
<use f='linux-5.3.1/net/ipv4/ipmr_base.c' l='255' u='m' c='mr_fill_mroute'/>
<use f='linux-5.3.1/net/ipv4/ipmr_base.c' l='255' u='m' c='mr_fill_mroute'/>
<use f='linux-5.3.1/net/ipv4/ipmr_base.c' l='258' u='m' c='mr_fill_mroute'/>
<use f='linux-5.3.1/net/ipv4/ipmr_base.c' l='259' u='m' c='mr_fill_mroute'/>
<use f='linux-5.3.1/net/ipv4/ipmr_base.c' l='260' u='m' c='mr_fill_mroute'/>
<use f='linux-5.3.1/net/ipv4/ipmr_base.c' l='277' u='m' c='mr_mfc_uses_dev'/>
<use f='linux-5.3.1/net/ipv4/ipmr_base.c' l='277' u='m' c='mr_mfc_uses_dev'/>
<use f='linux-5.3.1/net/ipv4/ipmr_base.c' l='278' u='m' c='mr_mfc_uses_dev'/>
