<dec f='linux-5.3.1/include/linux/msi.h' l='91' type='struct msi_msg'/>
<offset>256</offset>
<use f='linux-5.3.1/drivers/pci/msi.c' l='151' u='a' c='default_restore_msi_irq'/>
<use f='linux-5.3.1/drivers/pci/msi.c' l='348' u='w' c='__pci_write_msi_msg'/>
<use f='linux-5.3.1/drivers/pci/msi.c' l='601' u='m' c='msi_verify_entries'/>
<use f='linux-5.3.1/kernel/irq/msi.c' l='61' u='r' c='__get_cached_msi_msg'/>
