<dec f='linux-5.3.1/include/net/net_namespace.h' l='129' type='struct netns_nf'/>
<offset>17408</offset>
<use f='linux-5.3.1/include/linux/netfilter.h' l='227' u='m' c='nf_hook'/>
<use f='linux-5.3.1/include/linux/netfilter.h' l='227' u='m' c='nf_hook'/>
<use f='linux-5.3.1/include/linux/netfilter.h' l='227' u='m' c='nf_hook'/>
<use f='linux-5.3.1/include/linux/netfilter.h' l='227' u='m' c='nf_hook'/>
<use f='linux-5.3.1/include/linux/netfilter.h' l='227' u='m' c='nf_hook'/>
<use f='linux-5.3.1/include/linux/netfilter.h' l='227' u='m' c='nf_hook'/>
<use f='linux-5.3.1/include/linux/netfilter.h' l='227' u='m' c='nf_hook'/>
<use f='linux-5.3.1/include/linux/netfilter.h' l='227' u='m' c='nf_hook'/>
<use f='linux-5.3.1/include/linux/netfilter.h' l='230' u='m' c='nf_hook'/>
<use f='linux-5.3.1/include/linux/netfilter.h' l='230' u='m' c='nf_hook'/>
<use f='linux-5.3.1/include/linux/netfilter.h' l='230' u='m' c='nf_hook'/>
<use f='linux-5.3.1/include/linux/netfilter.h' l='230' u='m' c='nf_hook'/>
<use f='linux-5.3.1/include/linux/netfilter.h' l='230' u='m' c='nf_hook'/>
<use f='linux-5.3.1/include/linux/netfilter.h' l='230' u='m' c='nf_hook'/>
<use f='linux-5.3.1/include/linux/netfilter.h' l='230' u='m' c='nf_hook'/>
<use f='linux-5.3.1/include/linux/netfilter.h' l='230' u='m' c='nf_hook'/>
<use f='linux-5.3.1/net/ipv4/netfilter/nf_defrag_ipv4.c' l='109' u='m' c='defrag4_net_exit'/>
<use f='linux-5.3.1/net/ipv4/netfilter/nf_defrag_ipv4.c' l='112' u='m' c='defrag4_net_exit'/>
<use f='linux-5.3.1/net/ipv4/netfilter/nf_defrag_ipv4.c' l='136' u='m' c='nf_defrag_ipv4_enable'/>
<use f='linux-5.3.1/net/ipv4/netfilter/nf_defrag_ipv4.c' l='140' u='m' c='nf_defrag_ipv4_enable'/>
<use f='linux-5.3.1/net/ipv4/netfilter/nf_defrag_ipv4.c' l='146' u='m' c='nf_defrag_ipv4_enable'/>
<use f='linux-5.3.1/net/ipv6/netfilter/nf_defrag_ipv6_hooks.c' l='92' u='m' c='defrag6_net_exit'/>
<use f='linux-5.3.1/net/ipv6/netfilter/nf_defrag_ipv6_hooks.c' l='95' u='m' c='defrag6_net_exit'/>
<use f='linux-5.3.1/net/ipv6/netfilter/nf_defrag_ipv6_hooks.c' l='137' u='m' c='nf_defrag_ipv6_enable'/>
<use f='linux-5.3.1/net/ipv6/netfilter/nf_defrag_ipv6_hooks.c' l='141' u='m' c='nf_defrag_ipv6_enable'/>
<use f='linux-5.3.1/net/ipv6/netfilter/nf_defrag_ipv6_hooks.c' l='147' u='m' c='nf_defrag_ipv6_enable'/>
<use f='linux-5.3.1/net/netfilter/core.c' l='286' u='m' c='nf_hook_entry_head'/>
<use f='linux-5.3.1/net/netfilter/core.c' l='286' u='m' c='nf_hook_entry_head'/>
<use f='linux-5.3.1/net/netfilter/core.c' l='288' u='m' c='nf_hook_entry_head'/>
<use f='linux-5.3.1/net/netfilter/core.c' l='290' u='m' c='nf_hook_entry_head'/>
<use f='linux-5.3.1/net/netfilter/core.c' l='290' u='m' c='nf_hook_entry_head'/>
<use f='linux-5.3.1/net/netfilter/core.c' l='292' u='m' c='nf_hook_entry_head'/>
<use f='linux-5.3.1/net/netfilter/core.c' l='619' u='m' c='netfilter_net_init'/>
<use f='linux-5.3.1/net/netfilter/core.c' l='619' u='m' c='netfilter_net_init'/>
<use f='linux-5.3.1/net/netfilter/core.c' l='619' u='m' c='netfilter_net_init'/>
<use f='linux-5.3.1/net/netfilter/core.c' l='620' u='m' c='netfilter_net_init'/>
<use f='linux-5.3.1/net/netfilter/core.c' l='620' u='m' c='netfilter_net_init'/>
<use f='linux-5.3.1/net/netfilter/core.c' l='620' u='m' c='netfilter_net_init'/>
<use f='linux-5.3.1/net/netfilter/core.c' l='632' u='m' c='netfilter_net_init'/>
<use f='linux-5.3.1/net/netfilter/core.c' l='634' u='m' c='netfilter_net_init'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='49' u='m' c='nf_log_set'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='49' u='m' c='nf_log_set'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='53' u='m' c='nf_log_set'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='53' u='m' c='nf_log_set'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='55' u='m' c='nf_log_set'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='55' u='m' c='nf_log_set'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='55' u='m' c='nf_log_set'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='55' u='m' c='nf_log_set'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='55' u='m' c='nf_log_set'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='55' u='m' c='nf_log_set'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='55' u='m' c='nf_log_set'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='55' u='m' c='nf_log_set'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='55' u='m' c='nf_log_set'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='55' u='m' c='nf_log_set'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='55' u='m' c='nf_log_set'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='55' u='m' c='nf_log_set'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='55' u='m' c='nf_log_set'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='55' u='m' c='nf_log_set'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='55' u='m' c='nf_log_set'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='55' u='m' c='nf_log_set'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='55' u='m' c='nf_log_set'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='55' u='m' c='nf_log_set'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='55' u='m' c='nf_log_set'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='55' u='m' c='nf_log_set'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='70' u='m' c='nf_log_unset'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='70' u='m' c='nf_log_unset'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='72' u='m' c='nf_log_unset'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='72' u='m' c='nf_log_unset'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='72' u='m' c='nf_log_unset'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='72' u='m' c='nf_log_unset'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='72' u='m' c='nf_log_unset'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='84' u='m' c='nf_log_register'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='84' u='m' c='nf_log_register'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='131' u='m' c='nf_log_bind_pf'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='131' u='m' c='nf_log_bind_pf'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='138' u='m' c='nf_log_bind_pf'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='138' u='m' c='nf_log_bind_pf'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='138' u='m' c='nf_log_bind_pf'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='138' u='m' c='nf_log_bind_pf'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='138' u='m' c='nf_log_bind_pf'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='138' u='m' c='nf_log_bind_pf'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='138' u='m' c='nf_log_bind_pf'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='138' u='m' c='nf_log_bind_pf'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='138' u='m' c='nf_log_bind_pf'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='138' u='m' c='nf_log_bind_pf'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='138' u='m' c='nf_log_bind_pf'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='138' u='m' c='nf_log_bind_pf'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='138' u='m' c='nf_log_bind_pf'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='138' u='m' c='nf_log_bind_pf'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='138' u='m' c='nf_log_bind_pf'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='138' u='m' c='nf_log_bind_pf'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='138' u='m' c='nf_log_bind_pf'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='138' u='m' c='nf_log_bind_pf'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='138' u='m' c='nf_log_bind_pf'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='138' u='m' c='nf_log_bind_pf'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='146' u='m' c='nf_log_unbind_pf'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='146' u='m' c='nf_log_unbind_pf'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='149' u='m' c='nf_log_unbind_pf'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='149' u='m' c='nf_log_unbind_pf'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='149' u='m' c='nf_log_unbind_pf'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='149' u='m' c='nf_log_unbind_pf'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='149' u='m' c='nf_log_unbind_pf'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='232' u='m' c='nf_log_packet'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='232' u='m' c='nf_log_packet'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='232' u='m' c='nf_log_packet'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='232' u='m' c='nf_log_packet'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='232' u='m' c='nf_log_packet'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='232' u='m' c='nf_log_packet'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='232' u='m' c='nf_log_packet'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='232' u='m' c='nf_log_packet'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='257' u='m' c='nf_log_trace'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='257' u='m' c='nf_log_trace'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='257' u='m' c='nf_log_trace'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='257' u='m' c='nf_log_trace'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='257' u='m' c='nf_log_trace'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='257' u='m' c='nf_log_trace'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='257' u='m' c='nf_log_trace'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='257' u='m' c='nf_log_trace'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='332' u='m' c='seq_start'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='332' u='m' c='seq_start'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='344' u='m' c='seq_next'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='344' u='m' c='seq_next'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='362' u='m' c='seq_show'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='362' u='m' c='seq_show'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='447' u='m' c='nf_log_proc_dostring'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='447' u='m' c='nf_log_proc_dostring'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='447' u='m' c='nf_log_proc_dostring'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='447' u='m' c='nf_log_proc_dostring'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='447' u='m' c='nf_log_proc_dostring'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='447' u='m' c='nf_log_proc_dostring'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='447' u='m' c='nf_log_proc_dostring'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='447' u='m' c='nf_log_proc_dostring'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='447' u='m' c='nf_log_proc_dostring'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='447' u='m' c='nf_log_proc_dostring'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='447' u='m' c='nf_log_proc_dostring'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='447' u='m' c='nf_log_proc_dostring'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='447' u='m' c='nf_log_proc_dostring'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='447' u='m' c='nf_log_proc_dostring'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='447' u='m' c='nf_log_proc_dostring'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='447' u='m' c='nf_log_proc_dostring'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='447' u='m' c='nf_log_proc_dostring'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='447' u='m' c='nf_log_proc_dostring'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='447' u='m' c='nf_log_proc_dostring'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='447' u='m' c='nf_log_proc_dostring'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='454' u='m' c='nf_log_proc_dostring'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='454' u='m' c='nf_log_proc_dostring'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='500' u='m' c='netfilter_log_sysctl_init'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='503' u='m' c='netfilter_log_sysctl_init'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='522' u='m' c='netfilter_log_sysctl_exit'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='523' u='m' c='netfilter_log_sysctl_exit'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='545' u='m' c='nf_log_net_init'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='557' u='m' c='nf_log_net_init'/>
<use f='linux-5.3.1/net/netfilter/nf_log.c' l='566' u='m' c='nf_log_net_exit'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='37' u='m' c='nf_register_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='37' u='m' c='nf_register_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='37' u='m' c='nf_register_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='37' u='m' c='nf_register_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='37' u='m' c='nf_register_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='37' u='m' c='nf_register_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='37' u='m' c='nf_register_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='37' u='m' c='nf_register_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='38' u='m' c='nf_register_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='38' u='m' c='nf_register_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='38' u='m' c='nf_register_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='38' u='m' c='nf_register_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='38' u='m' c='nf_register_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='38' u='m' c='nf_register_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='38' u='m' c='nf_register_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='38' u='m' c='nf_register_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='38' u='m' c='nf_register_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='38' u='m' c='nf_register_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='38' u='m' c='nf_register_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='38' u='m' c='nf_register_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='38' u='m' c='nf_register_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='38' u='m' c='nf_register_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='38' u='m' c='nf_register_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='38' u='m' c='nf_register_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='38' u='m' c='nf_register_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='38' u='m' c='nf_register_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='38' u='m' c='nf_register_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='38' u='m' c='nf_register_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='45' u='m' c='nf_unregister_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='45' u='m' c='nf_unregister_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='45' u='m' c='nf_unregister_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='45' u='m' c='nf_unregister_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='45' u='m' c='nf_unregister_queue_handler'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='122' u='m' c='nf_queue_nf_hook_drop'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='122' u='m' c='nf_queue_nf_hook_drop'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='122' u='m' c='nf_queue_nf_hook_drop'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='122' u='m' c='nf_queue_nf_hook_drop'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='122' u='m' c='nf_queue_nf_hook_drop'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='122' u='m' c='nf_queue_nf_hook_drop'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='122' u='m' c='nf_queue_nf_hook_drop'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='122' u='m' c='nf_queue_nf_hook_drop'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='168' u='m' c='__nf_queue'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='168' u='m' c='__nf_queue'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='168' u='m' c='__nf_queue'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='168' u='m' c='__nf_queue'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='168' u='m' c='__nf_queue'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='168' u='m' c='__nf_queue'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='168' u='m' c='__nf_queue'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='168' u='m' c='__nf_queue'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='280' u='m' c='nf_hook_entries_head'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='280' u='m' c='nf_hook_entries_head'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='280' u='m' c='nf_hook_entries_head'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='280' u='m' c='nf_hook_entries_head'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='280' u='m' c='nf_hook_entries_head'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='280' u='m' c='nf_hook_entries_head'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='280' u='m' c='nf_hook_entries_head'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='280' u='m' c='nf_hook_entries_head'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='282' u='m' c='nf_hook_entries_head'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='282' u='m' c='nf_hook_entries_head'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='282' u='m' c='nf_hook_entries_head'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='282' u='m' c='nf_hook_entries_head'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='282' u='m' c='nf_hook_entries_head'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='282' u='m' c='nf_hook_entries_head'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='282' u='m' c='nf_hook_entries_head'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='282' u='m' c='nf_hook_entries_head'/>
<use f='linux-5.3.1/net/netfilter/nfnetlink_log.c' l='1061' u='m' c='nfnl_log_net_init'/>
<use f='linux-5.3.1/net/netfilter/nfnetlink_log.c' l='1080' u='m' c='nfnl_log_net_exit'/>
