<dec f='linux-5.3.1/include/linux/netlink.h' l='219' type='struct module *'/>
<use f='linux-5.3.1/include/linux/netlink.h' l='230' u='r' c='netlink_dump_start'/>
<use f='linux-5.3.1/include/linux/netlink.h' l='231' u='w' c='netlink_dump_start'/>
<offset>256</offset>
<use f='linux-5.3.1/net/core/rtnetlink.c' l='5184' u='w' c='rtnetlink_rcv_msg'/>
<use f='linux-5.3.1/net/netlink/af_netlink.c' l='2323' u='r' c='__netlink_dump_start'/>
<use f='linux-5.3.1/net/netlink/af_netlink.c' l='2334' u='r' c='__netlink_dump_start'/>
<use f='linux-5.3.1/net/netlink/af_netlink.c' l='2365' u='r' c='__netlink_dump_start'/>
<use f='linux-5.3.1/net/netlink/genetlink.c' l='563' u='w' c='genl_family_rcv_msg'/>
<use f='linux-5.3.1/net/netlink/genetlink.c' l='577' u='w' c='genl_family_rcv_msg'/>
