<dec f='linux-5.3.1/include/linux/netlink.h' l='188' type='struct module *'/>
<offset>320</offset>
<doc f='linux-5.3.1/include/linux/netlink.h' l='187'>/* the module that dump function belong to */</doc>
<use f='linux-5.3.1/net/netlink/af_netlink.c' l='390' u='r' c='netlink_sock_destruct'/>
<use f='linux-5.3.1/net/netlink/af_netlink.c' l='2285' u='r' c='netlink_dump'/>
<use f='linux-5.3.1/net/netlink/af_netlink.c' l='2334' u='w' c='__netlink_dump_start'/>
