<dec f='linux-5.3.1/net/netlink/af_netlink.h' l='64' type='struct module *'/>
<use f='linux-5.3.1/net/netlink/af_netlink.c' l='680' u='r' c='netlink_create'/>
<use f='linux-5.3.1/net/netlink/af_netlink.c' l='681' u='r' c='netlink_create'/>
<use f='linux-5.3.1/net/netlink/af_netlink.c' l='789' u='w' c='netlink_release'/>
<use f='linux-5.3.1/net/netlink/af_netlink.c' l='2072' u='w' c='__netlink_kernel_create'/>
<use f='linux-5.3.1/net/netlink/af_netlink.c' l='2721' u='w' c='netlink_add_usersock_entry'/>
<offset>1344</offset>
