<dec f='linux-5.3.1/include/net/netfilter/nf_conntrack_helper.h' l='166' type='struct module *'/>
<offset>256</offset>
<doc f='linux-5.3.1/include/net/netfilter/nf_conntrack_helper.h' l='166'>/* pointer to self */</doc>
<use f='linux-5.3.1/net/netfilter/nf_conntrack_helper.c' l='177' u='r' c='nf_nat_helper_try_module_get'/>
<use f='linux-5.3.1/net/netfilter/nf_conntrack_helper.c' l='193' u='r' c='nf_nat_helper_put'/>
<use f='linux-5.3.1/net/netfilter/nf_nat_ftp.c' l='31' macro='1' u='w'/>
<use f='linux-5.3.1/net/netfilter/nf_nat_irc.c' l='30' macro='1' u='w'/>
<use f='linux-5.3.1/net/netfilter/nf_nat_sip.c' l='32' macro='1' u='w'/>
