<dec f='linux-5.3.1/include/linux/netfilter.h' l='72' type='struct sock *'/>
<use f='linux-5.3.1/include/linux/netfilter.h' l='151' u='w' c='nf_hook_state_init'/>
<offset>192</offset>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='76' u='r' c='nf_queue_entry_release_refs'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='77' u='r' c='nf_queue_entry_release_refs'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='110' u='r' c='nf_queue_entry_get_refs'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='111' u='r' c='nf_queue_entry_get_refs'/>
<use f='linux-5.3.1/net/netfilter/nf_queue.c' l='337' u='r' c='nf_reinject'/>
