<dec f='linux-5.3.1/include/uapi/linux/netlink.h' l='111' type='struct nlmsghdr'/>
<offset>32</offset>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='758' u='a' c='ipmr_destroy_unres'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='758' u='r' c='ipmr_destroy_unres'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='1025' u='a' c='ipmr_cache_resolve'/>
<use f='linux-5.3.1/net/ipv4/ipmr.c' l='1025' u='r' c='ipmr_cache_resolve'/>
<use f='linux-5.3.1/net/netlink/af_netlink.c' l='2422' u='a' c='netlink_ack'/>
