<dec f='linux-5.3.1/include/linux/cdrom.h' l='21' type='unsigned char [12]'/>
<offset>0</offset>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='366' u='w' c='cdrom_flush_cache'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='383' u='w' c='cdrom_get_disc_info'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='384' u='w' c='cdrom_get_disc_info'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='400' u='w' c='cdrom_get_disc_info'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='456' u='w' c='cdrom_is_mrw'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='457' u='w' c='cdrom_is_mrw'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='458' u='w' c='cdrom_is_mrw'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='489' u='w' c='cdrom_mrw_bgformat'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='490' u='w' c='cdrom_mrw_bgformat'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='523' u='w' c='cdrom_mrw_bgformat_susp'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='528' u='w' c='cdrom_mrw_bgformat_susp'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='529' u='w' c='cdrom_mrw_bgformat_susp'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='666' u='w' c='cdrom_get_media_event'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='667' u='w' c='cdrom_get_media_event'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='668' u='w' c='cdrom_get_media_event'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='669' u='w' c='cdrom_get_media_event'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='694' u='w' c='cdrom_get_random_writable'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='695' u='w' c='cdrom_get_random_writable'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='696' u='w' c='cdrom_get_random_writable'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='715' u='w' c='cdrom_has_defect_mgt'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='716' u='w' c='cdrom_has_defect_mgt'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='717' u='w' c='cdrom_has_defect_mgt'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='868' u='w' c='cdrom_mmc3_profile'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='869' u='w' c='cdrom_mmc3_profile'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='870' u='w' c='cdrom_mmc3_profile'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='870' u='w' c='cdrom_mmc3_profile'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='871' u='w' c='cdrom_mmc3_profile'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='958' u='w' c='cdrom_dvd_rw_close_write'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='963' u='w' c='cdrom_dvd_rw_close_write'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='969' u='w' c='cdrom_dvd_rw_close_write'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='970' u='w' c='cdrom_dvd_rw_close_write'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1315' u='w' c='cdrom_read_mech_status'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1316' u='w' c='cdrom_read_mech_status'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1317' u='w' c='cdrom_read_mech_status'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1382' u='w' c='cdrom_load_unload'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1383' u='w' c='cdrom_load_unload'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1384' u='w' c='cdrom_load_unload'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1391' u='w' c='cdrom_load_unload'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1392' u='w' c='cdrom_load_unload'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1393' u='w' c='cdrom_load_unload'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1393' u='w' c='cdrom_load_unload'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1595' u='w' c='setup_report_key'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1596' u='w' c='setup_report_key'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1611' u='w' c='setup_report_key'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1617' u='w' c='setup_send_key'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1618' u='w' c='setup_send_key'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1633' u='w' c='setup_send_key'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1689' u='w' c='dvd_do_auth'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1690' u='w' c='dvd_do_auth'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1691' u='w' c='dvd_do_auth'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1692' u='w' c='dvd_do_auth'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1797' u='w' c='dvd_read_physical'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1798' u='w' c='dvd_read_physical'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1799' u='w' c='dvd_read_physical'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1800' u='w' c='dvd_read_physical'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1844' u='w' c='dvd_read_copyright'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1845' u='w' c='dvd_read_copyright'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1846' u='w' c='dvd_read_copyright'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1847' u='w' c='dvd_read_copyright'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1848' u='w' c='dvd_read_copyright'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1874' u='w' c='dvd_read_disckey'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1875' u='w' c='dvd_read_disckey'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1876' u='w' c='dvd_read_disckey'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1877' u='w' c='dvd_read_disckey'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1878' u='w' c='dvd_read_disckey'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1900' u='w' c='dvd_read_bca'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1901' u='w' c='dvd_read_bca'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1902' u='w' c='dvd_read_bca'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1936' u='w' c='dvd_read_manufact'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1937' u='w' c='dvd_read_manufact'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1938' u='w' c='dvd_read_manufact'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1939' u='w' c='dvd_read_manufact'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1996' u='r' c='cdrom_mode_sense'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1996' u='r' c='cdrom_mode_sense'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1998' u='w' c='cdrom_mode_sense'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='1999' u='w' c='cdrom_mode_sense'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2000' u='w' c='cdrom_mode_sense'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2001' u='w' c='cdrom_mode_sense'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2011' u='r' c='cdrom_mode_select'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2011' u='r' c='cdrom_mode_select'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2013' u='w' c='cdrom_mode_select'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2014' u='w' c='cdrom_mode_select'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2015' u='w' c='cdrom_mode_select'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2016' u='w' c='cdrom_mode_select'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2030' u='w' c='cdrom_read_subchannel'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2031' u='w' c='cdrom_read_subchannel'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2032' u='w' c='cdrom_read_subchannel'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2033' u='w' c='cdrom_read_subchannel'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2034' u='w' c='cdrom_read_subchannel'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2074' u='a' c='cdrom_read_cd'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2074' u='r' c='cdrom_read_cd'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2075' u='w' c='cdrom_read_cd'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2076' u='w' c='cdrom_read_cd'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2077' u='w' c='cdrom_read_cd'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2078' u='w' c='cdrom_read_cd'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2079' u='w' c='cdrom_read_cd'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2080' u='w' c='cdrom_read_cd'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2081' u='w' c='cdrom_read_cd'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2082' u='w' c='cdrom_read_cd'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2094' u='a' c='cdrom_read_block'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2094' u='r' c='cdrom_read_block'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2095' u='w' c='cdrom_read_block'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2097' u='w' c='cdrom_read_block'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2099' u='w' c='cdrom_read_block'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2100' u='w' c='cdrom_read_block'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2101' u='w' c='cdrom_read_block'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2102' u='w' c='cdrom_read_block'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2104' u='w' c='cdrom_read_block'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2105' u='w' c='cdrom_read_block'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2106' u='w' c='cdrom_read_block'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2111' u='w' c='cdrom_read_block'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2112' u='w' c='cdrom_read_block'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2113' u='w' c='cdrom_read_block'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2114' u='w' c='cdrom_read_block'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2784' u='w' c='cdrom_switch_blocksize'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2785' u='w' c='cdrom_switch_blocksize'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2786' u='w' c='cdrom_switch_blocksize'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2805' u='w' c='cdrom_get_track_info'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2806' u='w' c='cdrom_get_track_info'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2807' u='w' c='cdrom_get_track_info'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2808' u='w' c='cdrom_get_track_info'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2809' u='w' c='cdrom_get_track_info'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2822' u='w' c='cdrom_get_track_info'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='3064' u='w' c='mmc_ioctl_cdrom_play_msf'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='3065' u='w' c='mmc_ioctl_cdrom_play_msf'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='3066' u='w' c='mmc_ioctl_cdrom_play_msf'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='3067' u='w' c='mmc_ioctl_cdrom_play_msf'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='3068' u='w' c='mmc_ioctl_cdrom_play_msf'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='3069' u='w' c='mmc_ioctl_cdrom_play_msf'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='3070' u='w' c='mmc_ioctl_cdrom_play_msf'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='3084' u='w' c='mmc_ioctl_cdrom_play_blk'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='3085' u='w' c='mmc_ioctl_cdrom_play_blk'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='3086' u='w' c='mmc_ioctl_cdrom_play_blk'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='3087' u='w' c='mmc_ioctl_cdrom_play_blk'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='3088' u='w' c='mmc_ioctl_cdrom_play_blk'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='3089' u='w' c='mmc_ioctl_cdrom_play_blk'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='3090' u='w' c='mmc_ioctl_cdrom_play_blk'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='3176' u='w' c='mmc_ioctl_cdrom_start_stop'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='3177' u='w' c='mmc_ioctl_cdrom_start_stop'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='3178' u='w' c='mmc_ioctl_cdrom_start_stop'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='3189' u='w' c='mmc_ioctl_cdrom_pause_resume'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='3190' u='w' c='mmc_ioctl_cdrom_pause_resume'/>
<use f='linux-5.3.1/drivers/scsi/sr.c' l='978' u='r' c='sr_packet'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='54' u='w' c='sr_read_tochdr'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='55' u='w' c='sr_read_tochdr'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='84' u='w' c='sr_read_tocentry'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='85' u='w' c='sr_read_tocentry'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='86' u='w' c='sr_read_tocentry'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='87' u='w' c='sr_read_tocentry'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='146' u='w' c='sr_fake_playtrkind'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='147' u='w' c='sr_fake_playtrkind'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='148' u='w' c='sr_fake_playtrkind'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='149' u='w' c='sr_fake_playtrkind'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='150' u='w' c='sr_fake_playtrkind'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='151' u='w' c='sr_fake_playtrkind'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='152' u='w' c='sr_fake_playtrkind'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='168' u='w' c='sr_play_trkind'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='169' u='w' c='sr_play_trkind'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='170' u='w' c='sr_play_trkind'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='171' u='w' c='sr_play_trkind'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='172' u='w' c='sr_play_trkind'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='203' u='r' c='sr_do_ioctl'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='269' u='w' c='sr_tray_move'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='270' u='w' c='sr_tray_move'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='394' u='w' c='sr_get_mcn'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='395' u='w' c='sr_get_mcn'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='396' u='w' c='sr_get_mcn'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='397' u='w' c='sr_get_mcn'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='427' u='w' c='sr_select_speed'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='428' u='w' c='sr_select_speed'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='429' u='w' c='sr_select_speed'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='482' u='w' c='sr_read_cd'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='483' u='w' c='sr_read_cd'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='484' u='w' c='sr_read_cd'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='485' u='w' c='sr_read_cd'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='486' u='w' c='sr_read_cd'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='487' u='w' c='sr_read_cd'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='488' u='w' c='sr_read_cd'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='491' u='w' c='sr_read_cd'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='494' u='w' c='sr_read_cd'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='497' u='w' c='sr_read_cd'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='500' u='w' c='sr_read_cd'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='540' u='w' c='sr_read_sector'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='541' u='w' c='sr_read_sector'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='542' u='w' c='sr_read_sector'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='543' u='w' c='sr_read_sector'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='544' u='w' c='sr_read_sector'/>
<use f='linux-5.3.1/drivers/scsi/sr_ioctl.c' l='545' u='w' c='sr_read_sector'/>
<use f='linux-5.3.1/drivers/scsi/sr_vendor.c' l='130' u='w' c='sr_set_blocklength'/>
<use f='linux-5.3.1/drivers/scsi/sr_vendor.c' l='131' u='w' c='sr_set_blocklength'/>
<use f='linux-5.3.1/drivers/scsi/sr_vendor.c' l='132' u='w' c='sr_set_blocklength'/>
<use f='linux-5.3.1/drivers/scsi/sr_vendor.c' l='183' u='w' c='sr_cd_check'/>
<use f='linux-5.3.1/drivers/scsi/sr_vendor.c' l='184' u='w' c='sr_cd_check'/>
<use f='linux-5.3.1/drivers/scsi/sr_vendor.c' l='185' u='w' c='sr_cd_check'/>
<use f='linux-5.3.1/drivers/scsi/sr_vendor.c' l='211' u='w' c='sr_cd_check'/>
<use f='linux-5.3.1/drivers/scsi/sr_vendor.c' l='212' u='w' c='sr_cd_check'/>
<use f='linux-5.3.1/drivers/scsi/sr_vendor.c' l='213' u='w' c='sr_cd_check'/>
<use f='linux-5.3.1/drivers/scsi/sr_vendor.c' l='241' u='w' c='sr_cd_check'/>
<use f='linux-5.3.1/drivers/scsi/sr_vendor.c' l='242' u='w' c='sr_cd_check'/>
<use f='linux-5.3.1/drivers/scsi/sr_vendor.c' l='268' u='w' c='sr_cd_check'/>
<use f='linux-5.3.1/drivers/scsi/sr_vendor.c' l='269' u='w' c='sr_cd_check'/>
<use f='linux-5.3.1/drivers/scsi/sr_vendor.c' l='270' u='w' c='sr_cd_check'/>
<use f='linux-5.3.1/drivers/scsi/sr_vendor.c' l='285' u='w' c='sr_cd_check'/>
<use f='linux-5.3.1/drivers/scsi/sr_vendor.c' l='286' u='w' c='sr_cd_check'/>
<use f='linux-5.3.1/drivers/scsi/sr_vendor.c' l='287' u='w' c='sr_cd_check'/>
<use f='linux-5.3.1/drivers/scsi/sr_vendor.c' l='288' u='w' c='sr_cd_check'/>
