<dec f='linux-5.3.1/include/pcmcia/ss.h' l='122' type='int (*)(struct pcmcia_socket *)'/>
<offset>0</offset>
<use f='linux-5.3.1/drivers/pcmcia/cs.c' l='301' u='r' c='socket_shutdown'/>
<use f='linux-5.3.1/drivers/pcmcia/cs.c' l='474' u='r' c='socket_early_resume'/>
<use f='linux-5.3.1/drivers/pcmcia/cs.c' l='599' u='r' c='pccardd'/>
<use f='linux-5.3.1/drivers/pcmcia/yenta_socket.c' l='817' u='w'/>
