<dec f='linux-5.3.1/drivers/pcmcia/cs_internal.h' l='57' type='int (*)(struct pcmcia_socket *)'/>
<offset>192</offset>
<use f='linux-5.3.1/drivers/pcmcia/cs.c' l='161' u='r' c='pcmcia_register_socket'/>
<use f='linux-5.3.1/drivers/pcmcia/cs.c' l='163' u='r' c='pcmcia_register_socket'/>
<use f='linux-5.3.1/drivers/pcmcia/rsrc_mgr.c' l='62' u='w'/>
<use f='linux-5.3.1/drivers/pcmcia/rsrc_nonstatic.c' l='1057' u='w'/>
