<dec f='linux-5.3.1/arch/x86/include/asm/pci_x86.h' l='144' type='struct resource'/>
<offset>128</offset>
<use f='linux-5.3.1/arch/x86/pci/mmconfig-shared.c' l='37' u='m' c='pci_mmconfig_remove'/>
<use f='linux-5.3.1/arch/x86/pci/mmconfig-shared.c' l='38' u='a' c='pci_mmconfig_remove'/>
<use f='linux-5.3.1/arch/x86/pci/mmconfig-shared.c' l='86' u='a' c='pci_mmconfig_alloc'/>
<use f='linux-5.3.1/arch/x86/pci/mmconfig-shared.c' l='111' u='a' c='pci_mmconfig_add'/>
<use f='linux-5.3.1/arch/x86/pci/mmconfig-shared.c' l='450' u='m' c='is_mmconf_reserved'/>
<use f='linux-5.3.1/arch/x86/pci/mmconfig-shared.c' l='451' u='a' c='is_mmconf_reserved'/>
<use f='linux-5.3.1/arch/x86/pci/mmconfig-shared.c' l='467' u='a' c='is_mmconf_reserved'/>
<use f='linux-5.3.1/arch/x86/pci/mmconfig-shared.c' l='470' u='a' c='is_mmconf_reserved'/>
<use f='linux-5.3.1/arch/x86/pci/mmconfig-shared.c' l='476' u='m' c='is_mmconf_reserved'/>
<use f='linux-5.3.1/arch/x86/pci/mmconfig-shared.c' l='476' u='m' c='is_mmconf_reserved'/>
<use f='linux-5.3.1/arch/x86/pci/mmconfig-shared.c' l='486' u='a' c='is_mmconf_reserved'/>
<use f='linux-5.3.1/arch/x86/pci/mmconfig-shared.c' l='492' u='a' c='is_mmconf_reserved'/>
<use f='linux-5.3.1/arch/x86/pci/mmconfig-shared.c' l='509' u='a' c='pci_mmcfg_check_reserved'/>
<use f='linux-5.3.1/arch/x86/pci/mmconfig-shared.c' l='514' u='a' c='pci_mmcfg_check_reserved'/>
<use f='linux-5.3.1/arch/x86/pci/mmconfig-shared.c' l='706' u='m' c='pci_mmcfg_late_insert_resources'/>
<use f='linux-5.3.1/arch/x86/pci/mmconfig-shared.c' l='707' u='a' c='pci_mmcfg_late_insert_resources'/>
<use f='linux-5.3.1/arch/x86/pci/mmconfig-shared.c' l='758' u='a' c='pci_mmconfig_insert'/>
<use f='linux-5.3.1/arch/x86/pci/mmconfig-shared.c' l='763' u='a' c='pci_mmconfig_insert'/>
<use f='linux-5.3.1/arch/x86/pci/mmconfig-shared.c' l='769' u='a' c='pci_mmconfig_insert'/>
<use f='linux-5.3.1/arch/x86/pci/mmconfig-shared.c' l='772' u='a' c='pci_mmconfig_insert'/>
<use f='linux-5.3.1/arch/x86/pci/mmconfig-shared.c' l='776' u='a' c='pci_mmconfig_insert'/>
<use f='linux-5.3.1/arch/x86/pci/mmconfig-shared.c' l='783' u='m' c='pci_mmconfig_insert'/>
<use f='linux-5.3.1/arch/x86/pci/mmconfig-shared.c' l='784' u='a' c='pci_mmconfig_insert'/>
<use f='linux-5.3.1/arch/x86/pci/mmconfig-shared.c' l='805' u='m' c='pci_mmconfig_delete'/>
<use f='linux-5.3.1/arch/x86/pci/mmconfig-shared.c' l='806' u='a' c='pci_mmconfig_delete'/>
<use f='linux-5.3.1/arch/x86/pci/mmconfig_64.c' l='141' u='a' c='pci_mmcfg_arch_map'/>
