<dec f='linux-5.3.1/include/linux/pci.h' l='377' type='struct resource [11]'/>
<use f='linux-5.3.1/include/linux/pci.h' l='1350' u='a' c='pci_bus_address'/>
<offset>7168</offset>
<doc f='linux-5.3.1/include/linux/pci.h' l='377'>/* I/O and memory regions + expansion ROMs */</doc>
<use f='linux-5.3.1/arch/x86/kernel/pci-calgary_64.c' l='1529' u='a' c='calgary_fixup_one_tce_space'/>
<use f='linux-5.3.1/arch/x86/kernel/sysfb_efi.c' l='125' macro='1' u='m' c='efifb_set_system'/>
<use f='linux-5.3.1/arch/x86/kernel/sysfb_efi.c' l='132' macro='1' u='m' c='efifb_set_system'/>
<use f='linux-5.3.1/arch/x86/kernel/sysfb_efi.c' l='132' macro='1' u='m' c='efifb_set_system'/>
<use f='linux-5.3.1/arch/x86/kernel/sysfb_efi.c' l='132' macro='1' u='m' c='efifb_set_system'/>
<use f='linux-5.3.1/arch/x86/kernel/sysfb_efi.c' l='132' macro='1' u='m' c='efifb_set_system'/>
<use f='linux-5.3.1/arch/x86/kernel/sysfb_efi.c' l='132' macro='1' u='m' c='efifb_set_system'/>
<use f='linux-5.3.1/arch/x86/kernel/sysfb_efi.c' l='135' macro='1' u='m' c='efifb_set_system'/>
<use f='linux-5.3.1/arch/x86/kernel/sysfb_efi.c' l='136' macro='1' u='m' c='efifb_set_system'/>
<use f='linux-5.3.1/arch/x86/pci/common.c' l='128' u='a' c='pcibios_fixup_device_resources'/>
<use f='linux-5.3.1/arch/x86/pci/common.c' l='139' u='a' c='pcibios_fixup_device_resources'/>
<use f='linux-5.3.1/arch/x86/pci/fixup.c' l='62' u='m' c='pci_fixup_umc_ide'/>
<use f='linux-5.3.1/arch/x86/pci/fixup.c' l='341' u='a' c='pci_fixup_video'/>
<use f='linux-5.3.1/arch/x86/pci/fixup.c' l='462' macro='1' u='m' c='pci_post_fixup_toshiba_ohci1394'/>
<use f='linux-5.3.1/arch/x86/pci/fixup.c' l='464' macro='1' u='m' c='pci_post_fixup_toshiba_ohci1394'/>
<use f='linux-5.3.1/arch/x86/pci/fixup.c' l='493' u='m' c='pci_siemens_interrupt_controller'/>
<use f='linux-5.3.1/arch/x86/pci/fixup.c' l='529' u='a' c='sb600_hpet_quirk'/>
<use f='linux-5.3.1/arch/x86/pci/fixup.c' l='640' u='a' c='quirk_intel_th_dnv'/>
<use f='linux-5.3.1/arch/x86/pci/i386.c' l='215' u='a' c='pcibios_allocate_bridge_resources'/>
<use f='linux-5.3.1/arch/x86/pci/i386.c' l='265' u='a' c='pcibios_allocate_dev_resources'/>
<use f='linux-5.3.1/arch/x86/pci/i386.c' l='293' u='a' c='pcibios_allocate_dev_resources'/>
<use f='linux-5.3.1/arch/x86/pci/i386.c' l='330' u='a' c='pcibios_allocate_dev_rom_resource'/>
<use f='linux-5.3.1/arch/x86/video/fbdev.c' l='32' u='r' c='fb_is_primary_device'/>
<use f='linux-5.3.1/drivers/acpi/acpi_processor.c' l='104' macro='1' u='m' c='acpi_processor_errata_piix4'/>
<use f='linux-5.3.1/drivers/acpi/ioapic.c' l='137' macro='1' u='m' c='handle_ioapic_add'/>
<use f='linux-5.3.1/drivers/acpi/ioapic.c' l='137' macro='1' u='m' c='handle_ioapic_add'/>
<use f='linux-5.3.1/drivers/acpi/ioapic.c' l='137' macro='1' u='m' c='handle_ioapic_add'/>
<use f='linux-5.3.1/drivers/acpi/ioapic.c' l='137' macro='1' u='m' c='handle_ioapic_add'/>
<use f='linux-5.3.1/drivers/acpi/ioapic.c' l='137' macro='1' u='m' c='handle_ioapic_add'/>
<use f='linux-5.3.1/drivers/acpi/ioapic.c' l='143' u='a' c='handle_ioapic_add'/>
<use f='linux-5.3.1/drivers/ata/ahci.c' l='1512' macro='1' u='m' c='ahci_remap_check'/>
<use f='linux-5.3.1/drivers/ata/ahci.c' l='1512' macro='1' u='m' c='ahci_remap_check'/>
<use f='linux-5.3.1/drivers/ata/ahci.c' l='1512' macro='1' u='m' c='ahci_remap_check'/>
<use f='linux-5.3.1/drivers/ata/ahci.c' l='1512' macro='1' u='m' c='ahci_remap_check'/>
<use f='linux-5.3.1/drivers/ata/ahci.c' l='1512' macro='1' u='m' c='ahci_remap_check'/>
<use f='linux-5.3.1/drivers/ata/ata_piix.c' l='1281' macro='1' u='m' c='piix_disable_ahci'/>
<use f='linux-5.3.1/drivers/ata/ata_piix.c' l='1282' macro='1' u='m' c='piix_disable_ahci'/>
<use f='linux-5.3.1/drivers/ata/ata_piix.c' l='1282' macro='1' u='m' c='piix_disable_ahci'/>
<use f='linux-5.3.1/drivers/ata/ata_piix.c' l='1282' macro='1' u='m' c='piix_disable_ahci'/>
<use f='linux-5.3.1/drivers/ata/ata_piix.c' l='1282' macro='1' u='m' c='piix_disable_ahci'/>
<use f='linux-5.3.1/drivers/ata/ata_piix.c' l='1282' macro='1' u='m' c='piix_disable_ahci'/>
<use f='linux-5.3.1/drivers/ata/ata_piix.c' l='1454' macro='1' u='m' c='piix_init_sidpr'/>
<use f='linux-5.3.1/drivers/ata/ata_piix.c' l='1455' macro='1' u='m' c='piix_init_sidpr'/>
<use f='linux-5.3.1/drivers/ata/ata_piix.c' l='1455' macro='1' u='m' c='piix_init_sidpr'/>
<use f='linux-5.3.1/drivers/ata/ata_piix.c' l='1455' macro='1' u='m' c='piix_init_sidpr'/>
<use f='linux-5.3.1/drivers/ata/ata_piix.c' l='1455' macro='1' u='m' c='piix_init_sidpr'/>
<use f='linux-5.3.1/drivers/ata/ata_piix.c' l='1455' macro='1' u='m' c='piix_init_sidpr'/>
<use f='linux-5.3.1/drivers/ata/libata-eh.c' l='277' macro='1' u='m' c='ata_port_pbar_desc'/>
<use f='linux-5.3.1/drivers/ata/libata-eh.c' l='279' macro='1' u='m' c='ata_port_pbar_desc'/>
<use f='linux-5.3.1/drivers/ata/libata-eh.c' l='282' macro='1' u='m' c='ata_port_pbar_desc'/>
<use f='linux-5.3.1/drivers/ata/libata-eh.c' l='283' macro='1' u='m' c='ata_port_pbar_desc'/>
<use f='linux-5.3.1/drivers/ata/libata-eh.c' l='283' macro='1' u='m' c='ata_port_pbar_desc'/>
<use f='linux-5.3.1/drivers/ata/libata-eh.c' l='283' macro='1' u='m' c='ata_port_pbar_desc'/>
<use f='linux-5.3.1/drivers/ata/libata-eh.c' l='283' macro='1' u='m' c='ata_port_pbar_desc'/>
<use f='linux-5.3.1/drivers/ata/libata-eh.c' l='283' macro='1' u='m' c='ata_port_pbar_desc'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='2200' macro='1' u='m' c='ata_resources_present'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='2201' macro='1' u='m' c='ata_resources_present'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='2201' macro='1' u='m' c='ata_resources_present'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='2201' macro='1' u='m' c='ata_resources_present'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='2201' macro='1' u='m' c='ata_resources_present'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='2201' macro='1' u='m' c='ata_resources_present'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='2271' macro='1' u='m' c='ata_pci_sff_init_host'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='2272' macro='1' u='m' c='ata_pci_sff_init_host'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='3102' macro='1' u='m' c='ata_pci_bmdma_clear_simplex'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='3145' macro='1' u='m' c='ata_pci_bmdma_init'/>
<use f='linux-5.3.1/drivers/ata/libata-sff.c' l='3187' macro='1' u='m' c='ata_pci_bmdma_init'/>
<use f='linux-5.3.1/drivers/char/agp/intel-agp.c' l='776' u='a' c='agp_intel_probe'/>
<use f='linux-5.3.1/drivers/char/agp/intel-gtt.c' l='184' macro='1' u='m' c='i810_setup'/>
<use f='linux-5.3.1/drivers/char/agp/intel-gtt.c' l='542' macro='1' u='m' c='intel_gtt_mappable_entries'/>
<use f='linux-5.3.1/drivers/char/agp/intel-gtt.c' l='542' macro='1' u='m' c='intel_gtt_mappable_entries'/>
<use f='linux-5.3.1/drivers/char/agp/intel-gtt.c' l='542' macro='1' u='m' c='intel_gtt_mappable_entries'/>
<use f='linux-5.3.1/drivers/char/agp/intel-gtt.c' l='542' macro='1' u='m' c='intel_gtt_mappable_entries'/>
<use f='linux-5.3.1/drivers/char/agp/intel-gtt.c' l='542' macro='1' u='m' c='intel_gtt_mappable_entries'/>
<use f='linux-5.3.1/drivers/char/agp/intel-gtt.c' l='793' macro='1' u='m' c='i830_setup'/>
<use f='linux-5.3.1/drivers/char/agp/intel-gtt.c' l='1132' macro='1' u='m' c='i9xx_setup'/>
<use f='linux-5.3.1/drivers/char/agp/intel-gtt.c' l='1141' macro='1' u='m' c='i9xx_setup'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_lpe_audio.c' l='101' macro='1' u='m' c='lpe_audio_platdev_create'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/display/intel_lpe_audio.c' l='103' macro='1' u='m' c='lpe_audio_platdev_create'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_drv.c' l='785' u='m' c='i915_kick_out_firmware_fb'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='2995' macro='1' u='m' c='ggtt_probe_common'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='2995' macro='1' u='m' c='ggtt_probe_common'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='2995' macro='1' u='m' c='ggtt_probe_common'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='2995' macro='1' u='m' c='ggtt_probe_common'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='2995' macro='1' u='m' c='ggtt_probe_common'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='2995' macro='1' u='m' c='ggtt_probe_common'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='3331' macro='1' u='m' c='gen8_gmch_probe'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='3331' macro='1' u='m' c='gen8_gmch_probe'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='3331' macro='1' u='m' c='gen8_gmch_probe'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='3331' macro='1' u='m' c='gen8_gmch_probe'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='3331' macro='1' u='m' c='gen8_gmch_probe'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='3331' macro='1' u='m' c='gen8_gmch_probe'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='3331' macro='1' u='m' c='gen8_gmch_probe'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='3331' macro='1' u='m' c='gen8_gmch_probe'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='3331' macro='1' u='m' c='gen8_gmch_probe'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='3331' macro='1' u='m' c='gen8_gmch_probe'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='3331' macro='1' u='m' c='gen8_gmch_probe'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='3331' macro='1' u='m' c='gen8_gmch_probe'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='3331' macro='1' u='m' c='gen8_gmch_probe'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='3331' macro='1' u='m' c='gen8_gmch_probe'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='3393' macro='1' u='m' c='gen6_gmch_probe'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='3393' macro='1' u='m' c='gen6_gmch_probe'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='3393' macro='1' u='m' c='gen6_gmch_probe'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='3393' macro='1' u='m' c='gen6_gmch_probe'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='3393' macro='1' u='m' c='gen6_gmch_probe'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='3393' macro='1' u='m' c='gen6_gmch_probe'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='3393' macro='1' u='m' c='gen6_gmch_probe'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='3393' macro='1' u='m' c='gen6_gmch_probe'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='3393' macro='1' u='m' c='gen6_gmch_probe'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='3393' macro='1' u='m' c='gen6_gmch_probe'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='3393' macro='1' u='m' c='gen6_gmch_probe'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='3393' macro='1' u='m' c='gen6_gmch_probe'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='3393' macro='1' u='m' c='gen6_gmch_probe'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/i915_gem_gtt.c' l='3393' macro='1' u='m' c='gen6_gmch_probe'/>
<use f='linux-5.3.1/drivers/gpu/vga/vgaarb.c' l='1485' macro='1' u='m' c='vga_arb_select_default_device'/>
<use f='linux-5.3.1/drivers/gpu/vga/vgaarb.c' l='1490' macro='1' u='m' c='vga_arb_select_default_device'/>
<use f='linux-5.3.1/drivers/gpu/vga/vgaarb.c' l='1491' macro='1' u='m' c='vga_arb_select_default_device'/>
<use f='linux-5.3.1/drivers/i2c/busses/i2c-i801.c' l='1605' macro='1' u='m' c='i801_acpi_is_smbus_ioport'/>
<use f='linux-5.3.1/drivers/i2c/busses/i2c-i801.c' l='1660' u='a' c='i801_acpi_probe'/>
<use f='linux-5.3.1/drivers/i2c/busses/i2c-i801.c' l='1772' macro='1' u='m' c='i801_probe'/>
<use f='linux-5.3.1/drivers/i2c/busses/i2c-i801.c' l='1785' macro='1' u='m' c='i801_probe'/>
<use f='linux-5.3.1/drivers/iommu/amd_iommu.c' l='2791' u='a' c='init_reserved_iova_ranges'/>
<use f='linux-5.3.1/drivers/iommu/intel-iommu.c' l='1802' u='a' c='dmar_init_reserved_ranges'/>
<use f='linux-5.3.1/drivers/net/ethernet/intel/e100.c' l='2849' macro='1' u='m' c='e100_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/intel/e100.c' l='2950' macro='1' u='m' c='e100_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/intel/e1000/e1000_main.c' l='981' macro='1' u='m' c='e1000_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/intel/e1000/e1000_main.c' l='981' macro='1' u='m' c='e1000_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/intel/e1000/e1000_main.c' l='981' macro='1' u='m' c='e1000_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/intel/e1000/e1000_main.c' l='981' macro='1' u='m' c='e1000_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/intel/e1000/e1000_main.c' l='981' macro='1' u='m' c='e1000_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/intel/e1000/e1000_main.c' l='983' macro='1' u='m' c='e1000_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/intel/e1000/e1000_main.c' l='984' macro='1' u='m' c='e1000_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/intel/e1000/e1000_main.c' l='1029' macro='1' u='m' c='e1000_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/intel/e1000/e1000_main.c' l='1030' macro='1' u='m' c='e1000_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/intel/e1000/e1000_main.c' l='1030' macro='1' u='m' c='e1000_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/intel/e1000/e1000_main.c' l='1030' macro='1' u='m' c='e1000_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/intel/e1000/e1000_main.c' l='1030' macro='1' u='m' c='e1000_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/intel/e1000/e1000_main.c' l='1030' macro='1' u='m' c='e1000_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/intel/e1000e/netdev.c' l='7122' macro='1' u='m' c='e1000_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/intel/e1000e/netdev.c' l='7123' macro='1' u='m' c='e1000_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/intel/e1000e/netdev.c' l='7123' macro='1' u='m' c='e1000_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/intel/e1000e/netdev.c' l='7123' macro='1' u='m' c='e1000_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/intel/e1000e/netdev.c' l='7123' macro='1' u='m' c='e1000_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/intel/e1000e/netdev.c' l='7123' macro='1' u='m' c='e1000_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/intel/e1000e/netdev.c' l='7131' macro='1' u='m' c='e1000_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/intel/e1000e/netdev.c' l='7133' macro='1' u='m' c='e1000_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/intel/e1000e/netdev.c' l='7134' macro='1' u='m' c='e1000_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/intel/e1000e/netdev.c' l='7134' macro='1' u='m' c='e1000_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/intel/e1000e/netdev.c' l='7134' macro='1' u='m' c='e1000_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/intel/e1000e/netdev.c' l='7134' macro='1' u='m' c='e1000_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/intel/e1000e/netdev.c' l='7134' macro='1' u='m' c='e1000_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/marvell/sky2.c' l='5025' macro='1' u='m' c='sky2_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/nvidia/forcedeth.c' l='5729' macro='1' u='m' c='nv_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/nvidia/forcedeth.c' l='5730' macro='1' u='m' c='nv_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/nvidia/forcedeth.c' l='5730' macro='1' u='m' c='nv_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/nvidia/forcedeth.c' l='5730' macro='1' u='m' c='nv_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/nvidia/forcedeth.c' l='5730' macro='1' u='m' c='nv_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/nvidia/forcedeth.c' l='5730' macro='1' u='m' c='nv_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/nvidia/forcedeth.c' l='5731' macro='1' u='m' c='nv_probe'/>
<use f='linux-5.3.1/drivers/net/ethernet/realtek/8139too.c' l='804' macro='1' u='m' c='rtl8139_init_board'/>
<use f='linux-5.3.1/drivers/net/ethernet/realtek/8139too.c' l='804' macro='1' u='m' c='rtl8139_init_board'/>
<use f='linux-5.3.1/drivers/net/ethernet/realtek/8139too.c' l='804' macro='1' u='m' c='rtl8139_init_board'/>
<use f='linux-5.3.1/drivers/net/ethernet/realtek/8139too.c' l='804' macro='1' u='m' c='rtl8139_init_board'/>
<use f='linux-5.3.1/drivers/net/ethernet/realtek/8139too.c' l='804' macro='1' u='m' c='rtl8139_init_board'/>
<use f='linux-5.3.1/drivers/net/ethernet/realtek/8139too.c' l='808' macro='1' u='m' c='rtl8139_init_board'/>
<use f='linux-5.3.1/drivers/net/ethernet/realtek/8139too.c' l='1357' macro='1' u='m' c='rtl8139_open'/>
<use f='linux-5.3.1/drivers/net/ethernet/realtek/r8169_main.c' l='6867' macro='1' u='m' c='rtl_init_one'/>
<use f='linux-5.3.1/drivers/net/ethernet/realtek/r8169_main.c' l='6867' macro='1' u='m' c='rtl_init_one'/>
<use f='linux-5.3.1/drivers/net/ethernet/realtek/r8169_main.c' l='6867' macro='1' u='m' c='rtl_init_one'/>
<use f='linux-5.3.1/drivers/net/ethernet/realtek/r8169_main.c' l='6867' macro='1' u='m' c='rtl_init_one'/>
<use f='linux-5.3.1/drivers/net/ethernet/realtek/r8169_main.c' l='6867' macro='1' u='m' c='rtl_init_one'/>
<use f='linux-5.3.1/drivers/pci/bus.c' l='264' u='a' c='pci_bus_clip_resource'/>
<use f='linux-5.3.1/drivers/pci/mmap.c' l='28' u='a' c='pci_mmap_page_range'/>
<use f='linux-5.3.1/drivers/pci/mmap.c' l='50' macro='1' u='m' c='pci_mmap_resource_range'/>
<use f='linux-5.3.1/drivers/pci/mmap.c' l='50' macro='1' u='m' c='pci_mmap_resource_range'/>
<use f='linux-5.3.1/drivers/pci/mmap.c' l='50' macro='1' u='m' c='pci_mmap_resource_range'/>
<use f='linux-5.3.1/drivers/pci/mmap.c' l='50' macro='1' u='m' c='pci_mmap_resource_range'/>
<use f='linux-5.3.1/drivers/pci/mmap.c' l='50' macro='1' u='m' c='pci_mmap_resource_range'/>
<use f='linux-5.3.1/drivers/pci/mmap.c' l='64' macro='1' u='m' c='pci_mmap_resource_range'/>
<use f='linux-5.3.1/drivers/pci/msi.c' l='683' macro='1' u='m' c='msix_map_region'/>
<use f='linux-5.3.1/drivers/pci/msi.c' l='688' macro='1' u='m' c='msix_map_region'/>
<use f='linux-5.3.1/drivers/pci/pci-driver.c' l='1475' u='m' c='pci_dev_driver'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='143' u='a' c='resource_show'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='820' u='m' c='boot_vga_show'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1138' macro='1' u='m' c='pci_mmap_fits'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1138' macro='1' u='m' c='pci_mmap_fits'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1138' macro='1' u='m' c='pci_mmap_fits'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1138' macro='1' u='m' c='pci_mmap_fits'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1138' macro='1' u='m' c='pci_mmap_fits'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1142' macro='1' u='m' c='pci_mmap_fits'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1142' macro='1' u='m' c='pci_mmap_fits'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1142' macro='1' u='m' c='pci_mmap_fits'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1142' macro='1' u='m' c='pci_mmap_fits'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1142' macro='1' u='m' c='pci_mmap_fits'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1144' u='a' c='pci_mmap_fits'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1169' u='a' c='pci_mmap_resource'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1204' macro='1' u='m' c='pci_resource_io'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1206' macro='1' u='m' c='pci_resource_io'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1209' macro='1' u='m' c='pci_resource_io'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1299' macro='1' u='m' c='pci_create_attr'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1310' macro='1' u='m' c='pci_create_attr'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1310' macro='1' u='m' c='pci_create_attr'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1310' macro='1' u='m' c='pci_create_attr'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1310' macro='1' u='m' c='pci_create_attr'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1310' macro='1' u='m' c='pci_create_attr'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1334' macro='1' u='m' c='pci_create_resource_files'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1334' macro='1' u='m' c='pci_create_resource_files'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1334' macro='1' u='m' c='pci_create_resource_files'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1334' macro='1' u='m' c='pci_create_resource_files'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1334' macro='1' u='m' c='pci_create_resource_files'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1340' u='m' c='pci_create_resource_files'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1504' macro='1' u='m' c='pci_create_sysfs_dev_files'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1504' macro='1' u='m' c='pci_create_sysfs_dev_files'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1504' macro='1' u='m' c='pci_create_sysfs_dev_files'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1504' macro='1' u='m' c='pci_create_sysfs_dev_files'/>
<use f='linux-5.3.1/drivers/pci/pci-sysfs.c' l='1504' macro='1' u='m' c='pci_create_sysfs_dev_files'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='170' u='a' c='pci_ioremap_bar'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='188' macro='1' u='m' c='pci_ioremap_wc_bar'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='192' macro='1' u='m' c='pci_ioremap_wc_bar'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='193' macro='1' u='m' c='pci_ioremap_wc_bar'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='193' macro='1' u='m' c='pci_ioremap_wc_bar'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='193' macro='1' u='m' c='pci_ioremap_wc_bar'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='193' macro='1' u='m' c='pci_ioremap_wc_bar'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='193' macro='1' u='m' c='pci_ioremap_wc_bar'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='678' u='a' c='pci_find_resource'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='1445' u='r' c='pci_restore_rebar_state'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='1692' u='m' c='pci_enable_device_flags'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='1695' u='m' c='pci_enable_device_flags'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='2885' u='a' c='pci_ea_get_resource'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='2893' u='a' c='pci_ea_get_resource'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3674' macro='1' u='m' c='pci_release_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3674' macro='1' u='m' c='pci_release_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3674' macro='1' u='m' c='pci_release_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3674' macro='1' u='m' c='pci_release_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3674' macro='1' u='m' c='pci_release_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3676' macro='1' u='m' c='pci_release_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3677' macro='1' u='m' c='pci_release_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3677' macro='1' u='m' c='pci_release_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3677' macro='1' u='m' c='pci_release_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3677' macro='1' u='m' c='pci_release_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3677' macro='1' u='m' c='pci_release_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3677' macro='1' u='m' c='pci_release_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3679' macro='1' u='m' c='pci_release_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3680' macro='1' u='m' c='pci_release_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3680' macro='1' u='m' c='pci_release_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3680' macro='1' u='m' c='pci_release_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3680' macro='1' u='m' c='pci_release_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3680' macro='1' u='m' c='pci_release_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3680' macro='1' u='m' c='pci_release_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3713' macro='1' u='m' c='__pci_request_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3713' macro='1' u='m' c='__pci_request_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3713' macro='1' u='m' c='__pci_request_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3713' macro='1' u='m' c='__pci_request_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3713' macro='1' u='m' c='__pci_request_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3716' macro='1' u='m' c='__pci_request_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3717' macro='1' u='m' c='__pci_request_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3717' macro='1' u='m' c='__pci_request_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3717' macro='1' u='m' c='__pci_request_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3717' macro='1' u='m' c='__pci_request_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3717' macro='1' u='m' c='__pci_request_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3717' macro='1' u='m' c='__pci_request_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3720' macro='1' u='m' c='__pci_request_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3721' macro='1' u='m' c='__pci_request_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3721' macro='1' u='m' c='__pci_request_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3721' macro='1' u='m' c='__pci_request_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3721' macro='1' u='m' c='__pci_request_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3721' macro='1' u='m' c='__pci_request_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3721' macro='1' u='m' c='__pci_request_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='3735' u='a' c='__pci_request_region'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='5783' macro='1' u='m' c='pci_select_bars'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='5993' u='a' c='pci_request_resource_alignment'/>
<use f='linux-5.3.1/drivers/pci/pci.c' l='6101' u='a' c='pci_reassigndev_resource_alignment'/>
<use f='linux-5.3.1/drivers/pci/probe.c' l='337' u='a' c='pci_read_bases'/>
<use f='linux-5.3.1/drivers/pci/probe.c' l='343' u='a' c='pci_read_bases'/>
<use f='linux-5.3.1/drivers/pci/probe.c' l='532' u='a' c='pci_read_bridge_bases'/>
<use f='linux-5.3.1/drivers/pci/probe.c' l='1038' u='a' c='pci_alloc_child_bus'/>
<use f='linux-5.3.1/drivers/pci/probe.c' l='1799' u='a' c='pci_setup_device'/>
<use f='linux-5.3.1/drivers/pci/probe.c' l='1806' u='a' c='pci_setup_device'/>
<use f='linux-5.3.1/drivers/pci/probe.c' l='1815' u='a' c='pci_setup_device'/>
<use f='linux-5.3.1/drivers/pci/probe.c' l='1822' u='a' c='pci_setup_device'/>
<use f='linux-5.3.1/drivers/pci/proc.c' l='252' u='m' c='proc_bus_pci_mmap'/>
<use f='linux-5.3.1/drivers/pci/proc.c' l='262' u='m' c='proc_bus_pci_mmap'/>
<use f='linux-5.3.1/drivers/pci/proc.c' l='366' u='a' c='show_device'/>
<use f='linux-5.3.1/drivers/pci/proc.c' l='369' u='m' c='show_device'/>
<use f='linux-5.3.1/drivers/pci/proc.c' l='373' u='a' c='show_device'/>
<use f='linux-5.3.1/drivers/pci/proc.c' l='375' u='m' c='show_device'/>
<use f='linux-5.3.1/drivers/pci/proc.c' l='375' u='m' c='show_device'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='479' u='a' c='quirk_extend_bar_to_page'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='498' u='a' c='quirk_s3_64M'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='514' u='r' c='quirk_io'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='549' macro='1' u='m' c='quirk_cs5536_vsa'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='549' macro='1' u='m' c='quirk_cs5536_vsa'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='549' macro='1' u='m' c='quirk_cs5536_vsa'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='549' macro='1' u='m' c='quirk_cs5536_vsa'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='549' macro='1' u='m' c='quirk_cs5536_vsa'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='564' u='r' c='quirk_io_region'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='1224' u='a' c='quirk_dunord'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='1806' macro='1' u='m' c='quirk_alder_ioapic'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='1806' macro='1' u='m' c='quirk_alder_ioapic'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='1806' macro='1' u='m' c='quirk_alder_ioapic'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='1806' macro='1' u='m' c='quirk_alder_ioapic'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='1806' macro='1' u='m' c='quirk_alder_ioapic'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='1806' macro='1' u='m' c='quirk_alder_ioapic'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='1807' u='a' c='quirk_alder_ioapic'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='1814' u='a' c='quirk_alder_ioapic'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='1814' u='r' c='quirk_alder_ioapic'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='2069' u='a' c='quirk_tc86c001_ide'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='2096' macro='1' u='m' c='quirk_plx_pci9050'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='2096' macro='1' u='m' c='quirk_plx_pci9050'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='2096' macro='1' u='m' c='quirk_plx_pci9050'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='2096' macro='1' u='m' c='quirk_plx_pci9050'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='2096' macro='1' u='m' c='quirk_plx_pci9050'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='2097' macro='1' u='m' c='quirk_plx_pci9050'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='2098' u='a' c='quirk_plx_pci9050'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='2192' macro='1' u='m' c='quirk_e100_interrupt'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='2206' macro='1' u='m' c='quirk_e100_interrupt'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='3193' u='m' c='quirk_intel_ntb'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='3193' u='m' c='quirk_intel_ntb'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='3199' u='m' c='quirk_intel_ntb'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='3199' u='m' c='quirk_intel_ntb'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='3383' macro='1' u='m' c='mellanox_check_broken_intx_masking'/>
<use f='linux-5.3.1/drivers/pci/quirks.c' l='3746' macro='1' u='m' c='nvme_disable_and_flr'/>
<use f='linux-5.3.1/drivers/pci/remove.c' l='11' u='r' c='pci_free_resources'/>
<use f='linux-5.3.1/drivers/pci/rom.c' l='26' u='a' c='pci_enable_rom'/>
<use f='linux-5.3.1/drivers/pci/rom.c' l='60' u='a' c='pci_disable_rom'/>
<use f='linux-5.3.1/drivers/pci/rom.c' l='138' u='a' c='pci_map_rom'/>
<use f='linux-5.3.1/drivers/pci/rom.c' l='146' macro='1' u='m' c='pci_map_rom'/>
<use f='linux-5.3.1/drivers/pci/rom.c' l='147' macro='1' u='m' c='pci_map_rom'/>
<use f='linux-5.3.1/drivers/pci/rom.c' l='147' macro='1' u='m' c='pci_map_rom'/>
<use f='linux-5.3.1/drivers/pci/rom.c' l='147' macro='1' u='m' c='pci_map_rom'/>
<use f='linux-5.3.1/drivers/pci/rom.c' l='147' macro='1' u='m' c='pci_map_rom'/>
<use f='linux-5.3.1/drivers/pci/rom.c' l='147' macro='1' u='m' c='pci_map_rom'/>
<use f='linux-5.3.1/drivers/pci/rom.c' l='189' u='a' c='pci_unmap_rom'/>
<use f='linux-5.3.1/drivers/pci/setup-bus.c' l='137' u='a' c='pdev_sort_resources'/>
<use f='linux-5.3.1/drivers/pci/setup-bus.c' l='240' u='a' c='reassign_resources_sorted'/>
<use f='linux-5.3.1/drivers/pci/setup-bus.c' l='282' u='a' c='assign_requested_resources_sorted'/>
<use f='linux-5.3.1/drivers/pci/setup-bus.c' l='586' u='a' c='pci_setup_bridge_io'/>
<use f='linux-5.3.1/drivers/pci/setup-bus.c' l='616' u='a' c='pci_setup_bridge_mmio'/>
<use f='linux-5.3.1/drivers/pci/setup-bus.c' l='643' u='a' c='pci_setup_bridge_mmio_pref'/>
<use f='linux-5.3.1/drivers/pci/setup-bus.c' l='738' u='a' c='pci_bridge_check_ranges'/>
<use f='linux-5.3.1/drivers/pci/setup-bus.c' l='883' u='a' c='pbus_size_io'/>
<use f='linux-5.3.1/drivers/pci/setup-bus.c' l='998' u='a' c='pbus_size_mem'/>
<use f='linux-5.3.1/drivers/pci/setup-bus.c' l='1092' u='a' c='pci_bus_size_cardbus'/>
<use f='linux-5.3.1/drivers/pci/setup-bus.c' l='1227' u='a' c='__pci_bus_size_bridges'/>
<use f='linux-5.3.1/drivers/pci/setup-bus.c' l='1327' u='a' c='pdev_assign_fixed_resources'/>
<use f='linux-5.3.1/drivers/pci/setup-bus.c' l='1388' u='a' c='pci_claim_device_resources'/>
<use f='linux-5.3.1/drivers/pci/setup-bus.c' l='1402' u='a' c='pci_claim_bridge_resources'/>
<use f='linux-5.3.1/drivers/pci/setup-bus.c' l='1494' u='a' c='pci_bridge_release_resources'/>
<use f='linux-5.3.1/drivers/pci/setup-bus.c' l='1853' u='a' c='pci_bus_distribute_available_resources'/>
<use f='linux-5.3.1/drivers/pci/setup-bus.c' l='1854' u='a' c='pci_bus_distribute_available_resources'/>
<use f='linux-5.3.1/drivers/pci/setup-bus.c' l='1855' u='a' c='pci_bus_distribute_available_resources'/>
<use f='linux-5.3.1/drivers/pci/setup-bus.c' l='1918' u='a' c='pci_bus_distribute_available_resources'/>
<use f='linux-5.3.1/drivers/pci/setup-bus.c' l='1922' u='a' c='pci_bus_distribute_available_resources'/>
<use f='linux-5.3.1/drivers/pci/setup-bus.c' l='1926' u='a' c='pci_bus_distribute_available_resources'/>
<use f='linux-5.3.1/drivers/pci/setup-bus.c' l='1978' u='a' c='pci_bridge_distribute_available_resources'/>
<use f='linux-5.3.1/drivers/pci/setup-bus.c' l='1980' u='a' c='pci_bridge_distribute_available_resources'/>
<use f='linux-5.3.1/drivers/pci/setup-bus.c' l='1982' u='a' c='pci_bridge_distribute_available_resources'/>
<use f='linux-5.3.1/drivers/pci/setup-bus.c' l='2075' u='a' c='pci_reassign_bridge_resources'/>
<use f='linux-5.3.1/drivers/pci/setup-bus.c' l='2143' u='r' c='pci_reassign_bridge_resources'/>
<use f='linux-5.3.1/drivers/pci/setup-res.c' l='32' u='r' c='pci_std_update_resource'/>
<use f='linux-5.3.1/drivers/pci/setup-res.c' l='132' u='a' c='pci_claim_resource'/>
<use f='linux-5.3.1/drivers/pci/setup-res.c' l='248' u='r' c='__pci_assign_resource'/>
<use f='linux-5.3.1/drivers/pci/setup-res.c' l='311' u='r' c='pci_assign_resource'/>
<use f='linux-5.3.1/drivers/pci/setup-res.c' l='357' u='r' c='pci_reassign_resource'/>
<use f='linux-5.3.1/drivers/pci/setup-res.c' l='395' u='r' c='pci_release_resource'/>
<use f='linux-5.3.1/drivers/pci/setup-res.c' l='411' u='r' c='pci_resize_resource'/>
<use f='linux-5.3.1/drivers/pci/setup-res.c' l='468' u='a' c='pci_enable_resources'/>
<use f='linux-5.3.1/drivers/pcmcia/yenta_socket.c' l='698' u='r' c='yenta_allocate_res'/>
<use f='linux-5.3.1/drivers/pcmcia/yenta_socket.c' l='776' u='r' c='yenta_free_resources'/>
<use f='linux-5.3.1/drivers/pcmcia/yenta_socket.c' l='1036' u='a' c='yenta_config_init'/>
<use f='linux-5.3.1/drivers/pcmcia/yenta_socket.c' l='1190' macro='1' u='m' c='yenta_probe'/>
<use f='linux-5.3.1/drivers/pcmcia/yenta_socket.c' l='1200' macro='1' u='m' c='yenta_probe'/>
<use f='linux-5.3.1/drivers/pnp/quirks.c' l='251' macro='1' u='m' c='quirk_system_pci_resources'/>
<use f='linux-5.3.1/drivers/pnp/quirks.c' l='253' macro='1' u='m' c='quirk_system_pci_resources'/>
<use f='linux-5.3.1/drivers/pnp/quirks.c' l='253' macro='1' u='m' c='quirk_system_pci_resources'/>
<use f='linux-5.3.1/drivers/pnp/quirks.c' l='253' macro='1' u='m' c='quirk_system_pci_resources'/>
<use f='linux-5.3.1/drivers/pnp/quirks.c' l='253' macro='1' u='m' c='quirk_system_pci_resources'/>
<use f='linux-5.3.1/drivers/pnp/quirks.c' l='253' macro='1' u='m' c='quirk_system_pci_resources'/>
<use f='linux-5.3.1/drivers/pnp/quirks.c' l='259' macro='1' u='m' c='quirk_system_pci_resources'/>
<use f='linux-5.3.1/drivers/pnp/quirks.c' l='260' macro='1' u='m' c='quirk_system_pci_resources'/>
<use f='linux-5.3.1/drivers/pnp/quirks.c' l='295' u='a' c='quirk_system_pci_resources'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_exar.c' l='138' macro='1' u='m' c='default_setup'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_exar.c' l='477' macro='1' u='m' c='exar_pci_probe'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_exar.c' l='477' macro='1' u='m' c='exar_pci_probe'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_exar.c' l='477' macro='1' u='m' c='exar_pci_probe'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_exar.c' l='477' macro='1' u='m' c='exar_pci_probe'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_exar.c' l='477' macro='1' u='m' c='exar_pci_probe'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_lpss.c' l='300' macro='1' u='m' c='lpss8250_probe'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_mid.c' l='176' macro='1' u='m' c='dnv_setup'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_mid.c' l='176' macro='1' u='m' c='dnv_setup'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_mid.c' l='176' macro='1' u='m' c='dnv_setup'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_mid.c' l='176' macro='1' u='m' c='dnv_setup'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_mid.c' l='176' macro='1' u='m' c='dnv_setup'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_mid.c' l='310' macro='1' u='m' c='mid8250_probe'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='80' macro='1' u='m' c='setup_port'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='86' macro='1' u='m' c='setup_port'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='91' macro='1' u='m' c='setup_port'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='241' macro='1' u='m' c='pci_plx9050_init'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='265' macro='1' u='m' c='pci_plx9050_init'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='283' macro='1' u='m' c='pci_plx9050_exit'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='289' macro='1' u='m' c='pci_plx9050_exit'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='309' macro='1' u='m' c='pci_ni8420_exit'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='338' macro='1' u='m' c='pci_ni8430_exit'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='465' macro='1' u='m' c='pci_siig10x_init'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='668' macro='1' u='m' c='pci_ni8420_init'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='699' macro='1' u='m' c='pci_ni8430_init'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='713' u='a' c='pci_ni8430_init'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='1278' macro='1' u='m' c='pci_quatech_init'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='1296' macro='1' u='m' c='pci_quatech_setup'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='1321' macro='1' u='m' c='pci_default_setup'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='1321' macro='1' u='m' c='pci_default_setup'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='1321' macro='1' u='m' c='pci_default_setup'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='1321' macro='1' u='m' c='pci_default_setup'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='1321' macro='1' u='m' c='pci_default_setup'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='1372' macro='1' u='m' c='pci_pericom_setup'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='1372' macro='1' u='m' c='pci_pericom_setup'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='1372' macro='1' u='m' c='pci_pericom_setup'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='1372' macro='1' u='m' c='pci_pericom_setup'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='1372' macro='1' u='m' c='pci_pericom_setup'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='1398' macro='1' u='m' c='pci_pericom_setup_four_at_eight'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='1398' macro='1' u='m' c='pci_pericom_setup_four_at_eight'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='1398' macro='1' u='m' c='pci_pericom_setup_four_at_eight'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='1398' macro='1' u='m' c='pci_pericom_setup_four_at_eight'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='1398' macro='1' u='m' c='pci_pericom_setup_four_at_eight'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='1537' macro='1' u='m' c='pci_fintek_init'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='1538' macro='1' u='m' c='pci_fintek_init'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='1539' macro='1' u='m' c='pci_fintek_init'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='1555' macro='1' u='m' c='pci_fintek_init'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='1556' macro='1' u='m' c='pci_fintek_init'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='1557' macro='1' u='m' c='pci_fintek_init'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='3587' macro='1' u='m' c='serial_pci_guess_board'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='3592' macro='1' u='m' c='serial_pci_guess_board'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='3603' macro='1' u='m' c='serial_pci_guess_board'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='3603' macro='1' u='m' c='serial_pci_guess_board'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='3603' macro='1' u='m' c='serial_pci_guess_board'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='3603' macro='1' u='m' c='serial_pci_guess_board'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='3603' macro='1' u='m' c='serial_pci_guess_board'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='3615' macro='1' u='m' c='serial_pci_guess_board'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='3616' macro='1' u='m' c='serial_pci_guess_board'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='3616' macro='1' u='m' c='serial_pci_guess_board'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='3616' macro='1' u='m' c='serial_pci_guess_board'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='3616' macro='1' u='m' c='serial_pci_guess_board'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='3616' macro='1' u='m' c='serial_pci_guess_board'/>
<use f='linux-5.3.1/drivers/usb/core/hcd-pci.c' l='217' macro='1' u='m' c='usb_hcd_pci_probe'/>
<use f='linux-5.3.1/drivers/usb/core/hcd-pci.c' l='218' macro='1' u='m' c='usb_hcd_pci_probe'/>
<use f='linux-5.3.1/drivers/usb/core/hcd-pci.c' l='218' macro='1' u='m' c='usb_hcd_pci_probe'/>
<use f='linux-5.3.1/drivers/usb/core/hcd-pci.c' l='218' macro='1' u='m' c='usb_hcd_pci_probe'/>
<use f='linux-5.3.1/drivers/usb/core/hcd-pci.c' l='218' macro='1' u='m' c='usb_hcd_pci_probe'/>
<use f='linux-5.3.1/drivers/usb/core/hcd-pci.c' l='218' macro='1' u='m' c='usb_hcd_pci_probe'/>
<use f='linux-5.3.1/drivers/usb/core/hcd-pci.c' l='238' macro='1' u='m' c='usb_hcd_pci_probe'/>
<use f='linux-5.3.1/drivers/usb/core/hcd-pci.c' l='242' macro='1' u='m' c='usb_hcd_pci_probe'/>
<use f='linux-5.3.1/drivers/usb/core/hcd-pci.c' l='243' macro='1' u='m' c='usb_hcd_pci_probe'/>
<use f='linux-5.3.1/drivers/usb/core/hcd-pci.c' l='243' macro='1' u='m' c='usb_hcd_pci_probe'/>
<use f='linux-5.3.1/drivers/usb/core/hcd-pci.c' l='243' macro='1' u='m' c='usb_hcd_pci_probe'/>
<use f='linux-5.3.1/drivers/usb/core/hcd-pci.c' l='243' macro='1' u='m' c='usb_hcd_pci_probe'/>
<use f='linux-5.3.1/drivers/usb/core/hcd-pci.c' l='243' macro='1' u='m' c='usb_hcd_pci_probe'/>
<use f='linux-5.3.1/drivers/usb/host/pci-quirks.c' l='732' macro='1' u='m' c='quirk_usb_handoff_uhci'/>
<use f='linux-5.3.1/drivers/usb/host/pci-quirks.c' l='733' macro='1' u='m' c='quirk_usb_handoff_uhci'/>
<use f='linux-5.3.1/drivers/usb/host/pci-quirks.c' l='743' macro='1' u='m' c='mmio_resource_enabled'/>
<use f='linux-5.3.1/drivers/usb/host/pci-quirks.c' l='1148' macro='1' u='m' c='quirk_usb_handoff_xhci'/>
<use f='linux-5.3.1/drivers/usb/host/pci-quirks.c' l='1148' macro='1' u='m' c='quirk_usb_handoff_xhci'/>
<use f='linux-5.3.1/drivers/usb/host/pci-quirks.c' l='1148' macro='1' u='m' c='quirk_usb_handoff_xhci'/>
<use f='linux-5.3.1/drivers/usb/host/pci-quirks.c' l='1148' macro='1' u='m' c='quirk_usb_handoff_xhci'/>
<use f='linux-5.3.1/drivers/usb/host/pci-quirks.c' l='1148' macro='1' u='m' c='quirk_usb_handoff_xhci'/>
<use f='linux-5.3.1/drivers/usb/host/pci-quirks.c' l='1153' macro='1' u='m' c='quirk_usb_handoff_xhci'/>
<use f='linux-5.3.1/drivers/video/fbdev/core/fbmem.c' l='1788' macro='1' u='m' c='remove_conflicting_pci_framebuffers'/>
<use f='linux-5.3.1/drivers/video/fbdev/core/fbmem.c' l='1798' macro='1' u='m' c='remove_conflicting_pci_framebuffers'/>
<use f='linux-5.3.1/drivers/video/fbdev/core/fbmem.c' l='1800' macro='1' u='m' c='remove_conflicting_pci_framebuffers'/>
<use f='linux-5.3.1/drivers/video/fbdev/core/fbmem.c' l='1801' macro='1' u='m' c='remove_conflicting_pci_framebuffers'/>
<use f='linux-5.3.1/drivers/video/fbdev/core/fbmem.c' l='1801' macro='1' u='m' c='remove_conflicting_pci_framebuffers'/>
<use f='linux-5.3.1/drivers/video/fbdev/core/fbmem.c' l='1801' macro='1' u='m' c='remove_conflicting_pci_framebuffers'/>
<use f='linux-5.3.1/drivers/video/fbdev/core/fbmem.c' l='1801' macro='1' u='m' c='remove_conflicting_pci_framebuffers'/>
<use f='linux-5.3.1/drivers/video/fbdev/core/fbmem.c' l='1801' macro='1' u='m' c='remove_conflicting_pci_framebuffers'/>
<use f='linux-5.3.1/drivers/video/fbdev/core/fbmem.c' l='1802' macro='1' u='m' c='remove_conflicting_pci_framebuffers'/>
<use f='linux-5.3.1/drivers/video/fbdev/core/fbmem.c' l='1802' macro='1' u='m' c='remove_conflicting_pci_framebuffers'/>
<use f='linux-5.3.1/drivers/video/fbdev/core/fbmem.c' l='1814' u='m' c='remove_conflicting_pci_framebuffers'/>
<use f='linux-5.3.1/drivers/video/fbdev/efifb.c' l='650' u='a' c='record_efifb_bar_resource'/>
<use f='linux-5.3.1/drivers/video/fbdev/efifb.c' l='672' u='a' c='efifb_fixup_resources'/>
<use f='linux-5.3.1/lib/devres.c' l='385' macro='1' u='m' c='pcim_iomap_regions'/>
<use f='linux-5.3.1/lib/devres.c' l='385' macro='1' u='m' c='pcim_iomap_regions'/>
<use f='linux-5.3.1/lib/devres.c' l='385' macro='1' u='m' c='pcim_iomap_regions'/>
<use f='linux-5.3.1/lib/devres.c' l='385' macro='1' u='m' c='pcim_iomap_regions'/>
<use f='linux-5.3.1/lib/devres.c' l='385' macro='1' u='m' c='pcim_iomap_regions'/>
<use f='linux-5.3.1/lib/pci_iomap.c' l='33' macro='1' u='m' c='pci_iomap_range'/>
<use f='linux-5.3.1/lib/pci_iomap.c' l='34' macro='1' u='m' c='pci_iomap_range'/>
<use f='linux-5.3.1/lib/pci_iomap.c' l='34' macro='1' u='m' c='pci_iomap_range'/>
<use f='linux-5.3.1/lib/pci_iomap.c' l='34' macro='1' u='m' c='pci_iomap_range'/>
<use f='linux-5.3.1/lib/pci_iomap.c' l='34' macro='1' u='m' c='pci_iomap_range'/>
<use f='linux-5.3.1/lib/pci_iomap.c' l='34' macro='1' u='m' c='pci_iomap_range'/>
<use f='linux-5.3.1/lib/pci_iomap.c' l='35' macro='1' u='m' c='pci_iomap_range'/>
<use f='linux-5.3.1/lib/pci_iomap.c' l='73' macro='1' u='m' c='pci_iomap_wc_range'/>
<use f='linux-5.3.1/lib/pci_iomap.c' l='74' macro='1' u='m' c='pci_iomap_wc_range'/>
<use f='linux-5.3.1/lib/pci_iomap.c' l='74' macro='1' u='m' c='pci_iomap_wc_range'/>
<use f='linux-5.3.1/lib/pci_iomap.c' l='74' macro='1' u='m' c='pci_iomap_wc_range'/>
<use f='linux-5.3.1/lib/pci_iomap.c' l='74' macro='1' u='m' c='pci_iomap_wc_range'/>
<use f='linux-5.3.1/lib/pci_iomap.c' l='74' macro='1' u='m' c='pci_iomap_wc_range'/>
<use f='linux-5.3.1/lib/pci_iomap.c' l='75' macro='1' u='m' c='pci_iomap_wc_range'/>
<use f='linux-5.3.1/sound/pci/hda/hda_intel.c' l='1803' macro='1' u='m' c='azx_first_init'/>
