<dec f='linux-5.3.1/include/linux/perf_event.h' l='69' type='u32'/>
<use f='linux-5.3.1/include/linux/perf_event.h' l='1203' u='r' c='perf_callchain_store'/>
<use f='linux-5.3.1/include/linux/perf_event.h' l='1206' u='w' c='perf_callchain_store'/>
<offset>96</offset>
<use f='linux-5.3.1/arch/x86/events/core.c' l='2400' u='r' c='perf_callchain_user32'/>
<use f='linux-5.3.1/arch/x86/events/core.c' l='2457' u='r' c='perf_callchain_user'/>
<use f='linux-5.3.1/kernel/events/callchain.c' l='194' u='w' c='get_perf_callchain'/>
