<dec f='linux-5.3.1/include/linux/perf_event.h' l='62' type='__u64'/>
<use f='linux-5.3.1/include/linux/perf_event.h' l='1192' u='w' c='perf_callchain_store_context'/>
<use f='linux-5.3.1/include/linux/perf_event.h' l='1205' u='w' c='perf_callchain_store'/>
<offset>0</offset>
<use f='linux-5.3.1/kernel/events/callchain.c' l='194' u='w' c='get_perf_callchain'/>
<use f='linux-5.3.1/kernel/events/core.c' l='6280' u='r' c='perf_output_sample'/>
<use f='linux-5.3.1/kernel/events/core.c' l='6435' u='w'/>
<use f='linux-5.3.1/kernel/events/core.c' l='6479' u='r' c='perf_prepare_sample'/>
