<dec f='linux-5.3.1/include/linux/perf_event.h' l='256' type='struct module *'/>
<offset>128</offset>
<use f='linux-5.3.1/arch/x86/events/intel/cstate.c' l='480' u='w'/>
<use f='linux-5.3.1/arch/x86/events/intel/cstate.c' l='495' u='w'/>
<use f='linux-5.3.1/arch/x86/events/intel/rapl.c' l='666' u='w' c='init_rapl_pmus'/>
<use f='linux-5.3.1/arch/x86/events/intel/uncore.c' l='812' u='w' c='uncore_pmu_register'/>
<use f='linux-5.3.1/kernel/events/core.c' l='4489' u='r' c='_free_event'/>
<use f='linux-5.3.1/kernel/events/core.c' l='10081' u='r' c='perf_try_init_event'/>
<use f='linux-5.3.1/kernel/events/core.c' l='10120' u='r' c='perf_try_init_event'/>
<use f='linux-5.3.1/kernel/events/core.c' l='10482' u='r' c='perf_event_alloc'/>
