<dec f='linux-5.3.1/drivers/input/mouse/psmouse.h' l='86' type='int (*)(struct psmouse *)'/>
<offset>256</offset>
<use f='linux-5.3.1/drivers/input/mouse/psmouse-base.c' l='755' u='w'/>
<use f='linux-5.3.1/drivers/input/mouse/psmouse-base.c' l='788' u='w'/>
<use f='linux-5.3.1/drivers/input/mouse/psmouse-base.c' l='795' u='w'/>
<use f='linux-5.3.1/drivers/input/mouse/psmouse-base.c' l='804' u='w'/>
<use f='linux-5.3.1/drivers/input/mouse/psmouse-base.c' l='814' u='w'/>
<use f='linux-5.3.1/drivers/input/mouse/psmouse-base.c' l='823' u='w'/>
<use f='linux-5.3.1/drivers/input/mouse/psmouse-base.c' l='891' u='w'/>
<use f='linux-5.3.1/drivers/input/mouse/psmouse-base.c' l='909' u='w'/>
<use f='linux-5.3.1/drivers/input/mouse/psmouse-base.c' l='755' u='w'/>
<use f='linux-5.3.1/drivers/input/mouse/psmouse-base.c' l='788' u='w'/>
<use f='linux-5.3.1/drivers/input/mouse/psmouse-base.c' l='795' u='w'/>
<use f='linux-5.3.1/drivers/input/mouse/psmouse-base.c' l='804' u='w'/>
<use f='linux-5.3.1/drivers/input/mouse/psmouse-base.c' l='814' u='w'/>
<use f='linux-5.3.1/drivers/input/mouse/psmouse-base.c' l='823' u='w'/>
<use f='linux-5.3.1/drivers/input/mouse/psmouse-base.c' l='891' u='w'/>
<use f='linux-5.3.1/drivers/input/mouse/psmouse-base.c' l='909' u='w'/>
<use f='linux-5.3.1/drivers/input/mouse/psmouse-base.c' l='1027' u='r' c='psmouse_try_protocol'/>
<use f='linux-5.3.1/drivers/input/mouse/psmouse-base.c' l='1028' u='r' c='psmouse_try_protocol'/>
<use f='linux-5.3.1/drivers/input/mouse/psmouse-base.c' l='1531' u='r' c='psmouse_switch_protocol'/>
<use f='linux-5.3.1/drivers/input/mouse/psmouse-base.c' l='1537' u='r' c='psmouse_switch_protocol'/>
<use f='linux-5.3.1/drivers/input/mouse/psmouse-base.c' l='1537' u='r' c='psmouse_switch_protocol'/>
