<dec f='linux-5.3.1/kernel/rcu/tree.h' l='144' type='struct (anonymous struct at /home/woboq/linux-5.3.1/kernel/rcu/tree.h:141:2)'/>
<use f='linux-5.3.1/kernel/rcu/tree.c' l='1372' u='m' c='__note_gp_changes'/>
<use f='linux-5.3.1/kernel/rcu/tree.c' l='1924' u='m' c='rcu_report_qs_rdp'/>
<use f='linux-5.3.1/kernel/rcu/tree.c' l='1933' u='m' c='rcu_report_qs_rdp'/>
<use f='linux-5.3.1/kernel/rcu/tree.c' l='1978' u='m' c='rcu_check_quiescent_state'/>
<use f='linux-5.3.1/kernel/rcu/tree.c' l='2743' u='m' c='rcu_pending'/>
<use f='linux-5.3.1/kernel/rcu/tree.c' l='2991' u='m' c='rcutree_prepare_cpu'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='m' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='m' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='m' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='m' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='m' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='m' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='m' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='m' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='m' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='m' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='m' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='m' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='m' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='m' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='m' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='m' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='m' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='m' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='m' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='m' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='m' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='m' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='m' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='m' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='m' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='m' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='m' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='m' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='m' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='m' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='m' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='m' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='m' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='m' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='m' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='m' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='m' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='m' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='m' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='m' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='m' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='m' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='m' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='m' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='m' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='m' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='m' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='m' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='m' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='m' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='m' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='m' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='m' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='m' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='m' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='m' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='m' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='m' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='m' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='m' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='m' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='m' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='m' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='m' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='m' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='m' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='m' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='m' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='m' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='m' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='m' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='m' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='m' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='m' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='m' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='m' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='m' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='m' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='m' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='m' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='818' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='818' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='818' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='818' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='818' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='818' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='818' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='818' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='818' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='818' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='818' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='818' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='818' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='818' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='818' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='818' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='818' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='818' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='818' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='818' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='818' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='818' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='818' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='818' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='818' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='818' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='m' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='m' c='rcu_qs'/>
<offset>0</offset>
