<dec f='linux-5.3.1/kernel/rcu/tree.h' l='143' type='u8'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='a' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='r' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='r' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='r' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='r' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' u='r' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='704' c='rcu_exp_need_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='a' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='r' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='r' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='r' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='r' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' u='r' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='720' c='rcu_exp_handler'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='a' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='r' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='r' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='r' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='r' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' u='r' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_exp.h' l='743' c='sync_sched_exp_online_cleanup'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='a' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='r' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='r' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='r' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='r' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' u='r' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='819' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='a' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='r' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='r' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='r' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='r' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' u='r' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' c='rcu_qs'/>
<use f='linux-5.3.1/kernel/rcu/tree_plugin.h' l='821' c='rcu_qs'/>
<offset>8</offset>
