<dec f='linux-5.3.1/drivers/base/regmap/internal.h' l='169' type='int (*)(struct regmap *)'/>
<use f='linux-5.3.1/drivers/base/regmap/regcache-flat.c' l='79' u='w'/>
<offset>128</offset>
<use f='linux-5.3.1/drivers/base/regmap/regcache-rbtree.c' l='545' u='w'/>
<use f='linux-5.3.1/drivers/base/regmap/regcache.c' l='189' u='r' c='regcache_init'/>
<use f='linux-5.3.1/drivers/base/regmap/regcache.c' l='192' u='r' c='regcache_init'/>
