<dec f='linux-5.3.1/fs/isofs/rock.h' l='107' type='struct RR_SL_s'/>
<use f='linux-5.3.1/fs/isofs/rock.c' l='454' u='m' c='parse_rock_ridge_inode_internal'/>
<use f='linux-5.3.1/fs/isofs/rock.c' l='483' u='m' c='parse_rock_ridge_inode_internal'/>
<use f='linux-5.3.1/fs/isofs/rock.c' l='610' u='m' c='get_symlink_chunk'/>
<use f='linux-5.3.1/fs/isofs/rock.c' l='650' u='m' c='get_symlink_chunk'/>
<offset>0</offset>
