<dec f='linux-5.3.1/kernel/sched/sched.h' l='911' type='struct root_domain *'/>
<use f='linux-5.3.1/kernel/sched/sched.h' l='1887' u='r' c='add_nr_running'/>
<use f='linux-5.3.1/kernel/sched/sched.h' l='1887' u='r' c='add_nr_running'/>
<use f='linux-5.3.1/kernel/sched/sched.h' l='1887' u='r' c='add_nr_running'/>
<use f='linux-5.3.1/kernel/sched/sched.h' l='1887' u='r' c='add_nr_running'/>
<use f='linux-5.3.1/kernel/sched/sched.h' l='1887' u='r' c='add_nr_running'/>
<use f='linux-5.3.1/kernel/sched/sched.h' l='1888' u='r' c='add_nr_running'/>
<use f='linux-5.3.1/kernel/sched/sched.h' l='1888' u='r' c='add_nr_running'/>
<use f='linux-5.3.1/kernel/sched/sched.h' l='1888' u='r' c='add_nr_running'/>
<use f='linux-5.3.1/kernel/sched/sched.h' l='1888' u='r' c='add_nr_running'/>
<use f='linux-5.3.1/kernel/sched/sched.h' l='1888' u='r' c='add_nr_running'/>
<offset>19200</offset>
<use f='linux-5.3.1/kernel/sched/core.c' l='4717' u='r' c='__sched_setscheduler'/>
<use f='linux-5.3.1/kernel/sched/core.c' l='4725' u='r' c='__sched_setscheduler'/>
<use f='linux-5.3.1/kernel/sched/core.c' l='5256' u='r' c='sched_setaffinity'/>
<use f='linux-5.3.1/kernel/sched/core.c' l='5925' u='r' c='task_can_attach'/>
<use f='linux-5.3.1/kernel/sched/core.c' l='6126' u='r' c='set_rq_online'/>
<use f='linux-5.3.1/kernel/sched/core.c' l='6146' u='r' c='set_rq_offline'/>
<use f='linux-5.3.1/kernel/sched/core.c' l='6228' u='r' c='sched_cpu_activate'/>
<use f='linux-5.3.1/kernel/sched/core.c' l='6229' u='r' c='sched_cpu_activate'/>
<use f='linux-5.3.1/kernel/sched/core.c' l='6299' u='r' c='sched_cpu_dying'/>
<use f='linux-5.3.1/kernel/sched/core.c' l='6300' u='r' c='sched_cpu_dying'/>
<use f='linux-5.3.1/kernel/sched/core.c' l='6482' u='w' c='sched_init'/>
<use f='linux-5.3.1/kernel/sched/deadline.c' l='51' u='r' c='dl_bw_of'/>
<use f='linux-5.3.1/kernel/sched/deadline.c' l='56' u='r' c='dl_bw_cpus'/>
<use f='linux-5.3.1/kernel/sched/deadline.c' l='380' u='r' c='dl_overloaded'/>
<use f='linux-5.3.1/kernel/sched/deadline.c' l='388' u='r' c='dl_set_overload'/>
<use f='linux-5.3.1/kernel/sched/deadline.c' l='396' u='r' c='dl_set_overload'/>
<use f='linux-5.3.1/kernel/sched/deadline.c' l='404' u='r' c='dl_clear_overload'/>
<use f='linux-5.3.1/kernel/sched/deadline.c' l='405' u='r' c='dl_clear_overload'/>
<use f='linux-5.3.1/kernel/sched/deadline.c' l='1308' u='r' c='inc_dl_deadline'/>
<use f='linux-5.3.1/kernel/sched/deadline.c' l='1323' u='r' c='dec_dl_deadline'/>
<use f='linux-5.3.1/kernel/sched/deadline.c' l='1330' u='r' c='dec_dl_deadline'/>
<use f='linux-5.3.1/kernel/sched/deadline.c' l='1647' u='r' c='check_preempt_equal_dl'/>
<use f='linux-5.3.1/kernel/sched/deadline.c' l='1655' u='r' c='check_preempt_equal_dl'/>
<use f='linux-5.3.1/kernel/sched/deadline.c' l='1878' u='r' c='find_later_rq'/>
<use f='linux-5.3.1/kernel/sched/deadline.c' l='2135' u='r' c='pull_dl_task'/>
<use f='linux-5.3.1/kernel/sched/deadline.c' l='2224' u='r' c='set_cpus_allowed_dl'/>
<use f='linux-5.3.1/kernel/sched/deadline.c' l='2254' u='r' c='rq_online_dl'/>
<use f='linux-5.3.1/kernel/sched/deadline.c' l='2256' u='r' c='rq_online_dl'/>
<use f='linux-5.3.1/kernel/sched/deadline.c' l='2265' u='r' c='rq_offline_dl'/>
<use f='linux-5.3.1/kernel/sched/deadline.c' l='2266' u='r' c='rq_offline_dl'/>
<use f='linux-5.3.1/kernel/sched/fair.c' l='5243' u='r' c='update_overutilized_status'/>
<use f='linux-5.3.1/kernel/sched/fair.c' l='5243' u='r' c='update_overutilized_status'/>
<use f='linux-5.3.1/kernel/sched/fair.c' l='5243' u='r' c='update_overutilized_status'/>
<use f='linux-5.3.1/kernel/sched/fair.c' l='5243' u='r' c='update_overutilized_status'/>
<use f='linux-5.3.1/kernel/sched/fair.c' l='5243' u='r' c='update_overutilized_status'/>
<use f='linux-5.3.1/kernel/sched/fair.c' l='5244' u='r' c='update_overutilized_status'/>
<use f='linux-5.3.1/kernel/sched/fair.c' l='5244' u='r' c='update_overutilized_status'/>
<use f='linux-5.3.1/kernel/sched/fair.c' l='5244' u='r' c='update_overutilized_status'/>
<use f='linux-5.3.1/kernel/sched/fair.c' l='5244' u='r' c='update_overutilized_status'/>
<use f='linux-5.3.1/kernel/sched/fair.c' l='5244' u='r' c='update_overutilized_status'/>
<use f='linux-5.3.1/kernel/sched/fair.c' l='5245' u='r' c='update_overutilized_status'/>
<use f='linux-5.3.1/kernel/sched/fair.c' l='6234' u='r' c='wake_cap'/>
<use f='linux-5.3.1/kernel/sched/fair.c' l='6393' u='r' c='find_energy_efficient_cpu'/>
<use f='linux-5.3.1/kernel/sched/fair.c' l='7894' u='r' c='check_misfit_status'/>
<use f='linux-5.3.1/kernel/sched/fair.c' l='8300' u='r' c='update_sd_lb_stats'/>
<use f='linux-5.3.1/kernel/sched/fair.c' l='8309' u='r' c='update_sd_lb_stats'/>
<use f='linux-5.3.1/kernel/sched/fair.c' l='8539' u='r' c='find_busiest_group'/>
<use f='linux-5.3.1/kernel/sched/fair.c' l='9820' u='r' c='idle_balance'/>
<use f='linux-5.3.1/kernel/sched/fair.c' l='9820' u='r' c='idle_balance'/>
<use f='linux-5.3.1/kernel/sched/fair.c' l='9820' u='r' c='idle_balance'/>
<use f='linux-5.3.1/kernel/sched/fair.c' l='9820' u='r' c='idle_balance'/>
<use f='linux-5.3.1/kernel/sched/fair.c' l='9820' u='r' c='idle_balance'/>
<use f='linux-5.3.1/kernel/sched/rt.c' l='270' u='r' c='rt_overloaded'/>
<use f='linux-5.3.1/kernel/sched/rt.c' l='278' u='r' c='rt_set_overload'/>
<use f='linux-5.3.1/kernel/sched/rt.c' l='289' u='r' c='rt_set_overload'/>
<use f='linux-5.3.1/kernel/sched/rt.c' l='298' u='r' c='rt_clear_overload'/>
<use f='linux-5.3.1/kernel/sched/rt.c' l='299' u='r' c='rt_clear_overload'/>
<use f='linux-5.3.1/kernel/sched/rt.c' l='641' u='r' c='do_balance_runtime'/>
<use f='linux-5.3.1/kernel/sched/rt.c' l='692' u='r' c='__disable_runtime'/>
<use f='linux-5.3.1/kernel/sched/rt.c' l='1048' u='r' c='inc_rt_prio_smp'/>
<use f='linux-5.3.1/kernel/sched/rt.c' l='1064' u='r' c='dec_rt_prio_smp'/>
<use f='linux-5.3.1/kernel/sched/rt.c' l='1451' u='r' c='check_preempt_equal_prio'/>
<use f='linux-5.3.1/kernel/sched/rt.c' l='1459' u='r' c='check_preempt_equal_prio'/>
<use f='linux-5.3.1/kernel/sched/rt.c' l='1659' u='r' c='find_lowest_rq'/>
<use f='linux-5.3.1/kernel/sched/rt.c' l='1994' u='r' c='tell_cpu_to_push'/>
<use f='linux-5.3.1/kernel/sched/rt.c' l='1997' u='r' c='tell_cpu_to_push'/>
<use f='linux-5.3.1/kernel/sched/rt.c' l='2000' u='r' c='tell_cpu_to_push'/>
<use f='linux-5.3.1/kernel/sched/rt.c' l='2008' u='r' c='tell_cpu_to_push'/>
<use f='linux-5.3.1/kernel/sched/rt.c' l='2009' u='r' c='tell_cpu_to_push'/>
<use f='linux-5.3.1/kernel/sched/rt.c' l='2011' u='r' c='tell_cpu_to_push'/>
<use f='linux-5.3.1/kernel/sched/rt.c' l='2013' u='r' c='tell_cpu_to_push'/>
<use f='linux-5.3.1/kernel/sched/rt.c' l='2017' u='r' c='tell_cpu_to_push'/>
<use f='linux-5.3.1/kernel/sched/rt.c' l='2018' u='r' c='tell_cpu_to_push'/>
<use f='linux-5.3.1/kernel/sched/rt.c' l='2078' u='r' c='pull_rt_task'/>
<use f='linux-5.3.1/kernel/sched/rt.c' l='2088' u='r' c='pull_rt_task'/>
<use f='linux-5.3.1/kernel/sched/rt.c' l='2180' u='r' c='rq_online_rt'/>
<use f='linux-5.3.1/kernel/sched/rt.c' l='2191' u='r' c='rq_offline_rt'/>
<use f='linux-5.3.1/kernel/sched/topology.c' l='447' u='r' c='rq_attach_root'/>
<use f='linux-5.3.1/kernel/sched/topology.c' l='448' u='r' c='rq_attach_root'/>
<use f='linux-5.3.1/kernel/sched/topology.c' l='465' u='w' c='rq_attach_root'/>
<use f='linux-5.3.1/kernel/sched/topology.c' l='2012' u='r' c='build_sched_domains'/>
