<dec f='linux-5.3.1/include/scsi/scsi_request.h' l='11' type='unsigned char *'/>
<use f='linux-5.3.1/include/scsi/scsi_request.h' l='27' u='r' c='scsi_req_free_cmd'/>
<use f='linux-5.3.1/include/scsi/scsi_request.h' l='28' u='r' c='scsi_req_free_cmd'/>
<use f='linux-5.3.1/block/bsg.c' l='77' u='w' c='bsg_scsi_fill_hdr'/>
<use f='linux-5.3.1/block/bsg.c' l='78' u='r' c='bsg_scsi_fill_hdr'/>
<use f='linux-5.3.1/block/bsg.c' l='82' u='r' c='bsg_scsi_fill_hdr'/>
<use f='linux-5.3.1/block/bsg.c' l='84' u='r' c='bsg_scsi_fill_hdr'/>
<offset>128</offset>
<use f='linux-5.3.1/block/scsi_ioctl.c' l='221' u='r' c='blk_fill_sghdr_rq'/>
<use f='linux-5.3.1/block/scsi_ioctl.c' l='223' u='r' c='blk_fill_sghdr_rq'/>
<use f='linux-5.3.1/block/scsi_ioctl.c' l='316' u='w' c='sg_io'/>
<use f='linux-5.3.1/block/scsi_ioctl.c' l='317' u='r' c='sg_io'/>
<use f='linux-5.3.1/block/scsi_ioctl.c' l='451' u='r' c='sg_scsi_ioctl'/>
<use f='linux-5.3.1/block/scsi_ioctl.c' l='457' u='r' c='sg_scsi_ioctl'/>
<use f='linux-5.3.1/block/scsi_ioctl.c' l='529' u='r' c='__blk_send_generic'/>
<use f='linux-5.3.1/block/scsi_ioctl.c' l='530' u='r' c='__blk_send_generic'/>
<use f='linux-5.3.1/block/scsi_ioctl.c' l='709' u='w' c='scsi_req_init'/>
<use f='linux-5.3.1/drivers/ata/libata-scsi.c' l='1246' u='r' c='atapi_drain_needed'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2209' u='r' c='cdrom_read_cdda_bpc'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2210' u='r' c='cdrom_read_cdda_bpc'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2211' u='r' c='cdrom_read_cdda_bpc'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2212' u='r' c='cdrom_read_cdda_bpc'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2213' u='r' c='cdrom_read_cdda_bpc'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2214' u='r' c='cdrom_read_cdda_bpc'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2215' u='r' c='cdrom_read_cdda_bpc'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2216' u='r' c='cdrom_read_cdda_bpc'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2217' u='r' c='cdrom_read_cdda_bpc'/>
<use f='linux-5.3.1/drivers/cdrom/cdrom.c' l='2218' u='r' c='cdrom_read_cdda_bpc'/>
<use f='linux-5.3.1/drivers/scsi/scsi_error.c' l='1979' u='r' c='scsi_eh_lock_door'/>
<use f='linux-5.3.1/drivers/scsi/scsi_error.c' l='1980' u='r' c='scsi_eh_lock_door'/>
<use f='linux-5.3.1/drivers/scsi/scsi_error.c' l='1981' u='r' c='scsi_eh_lock_door'/>
<use f='linux-5.3.1/drivers/scsi/scsi_error.c' l='1982' u='r' c='scsi_eh_lock_door'/>
<use f='linux-5.3.1/drivers/scsi/scsi_error.c' l='1983' u='r' c='scsi_eh_lock_door'/>
<use f='linux-5.3.1/drivers/scsi/scsi_error.c' l='1984' u='r' c='scsi_eh_lock_door'/>
<use f='linux-5.3.1/drivers/scsi/scsi_error.c' l='1985' u='r' c='scsi_eh_lock_door'/>
<use f='linux-5.3.1/drivers/scsi/scsi_error.c' l='2353' u='r' c='scsi_ioctl_reset'/>
<use f='linux-5.3.1/drivers/scsi/scsi_lib.c' l='270' u='r' c='__scsi_execute'/>
<use f='linux-5.3.1/drivers/scsi/scsi_lib.c' l='1175' u='r' c='scsi_setup_scsi_cmnd'/>
<use f='linux-5.3.1/drivers/scsi/scsi_lib.c' l='1196' u='w' c='scsi_setup_fs_cmnd'/>
<use f='linux-5.3.1/drivers/scsi/sd.c' l='1311' u='r' c='sd_uninit_command'/>
<use f='linux-5.3.1/drivers/scsi/sg.c' l='1745' u='w' c='sg_start_req'/>
<use f='linux-5.3.1/drivers/scsi/sg.c' l='1746' u='r' c='sg_start_req'/>
