<dec f='linux-5.3.1/include/scsi/scsi_host.h' l='46' type='struct module *'/>
<use f='linux-5.3.1/drivers/ata/ahci.c' l='95' macro='1' u='w'/>
<offset>0</offset>
<use f='linux-5.3.1/drivers/ata/ata_piix.c' l='1062' macro='1' u='w'/>
<use f='linux-5.3.1/drivers/ata/ata_piix.c' l='1096' macro='1' u='w'/>
<use f='linux-5.3.1/drivers/ata/pata_amd.c' l='392' macro='1' u='w'/>
<use f='linux-5.3.1/drivers/ata/pata_oldpiix.c' l='208' macro='1' u='w'/>
<use f='linux-5.3.1/drivers/ata/pata_sch.c' l='61' macro='1' u='w'/>
<use f='linux-5.3.1/drivers/scsi/scsi.c' l='537' u='r' c='scsi_device_get'/>
<use f='linux-5.3.1/drivers/scsi/scsi.c' l='558' u='r' c='scsi_device_put'/>
<use f='linux-5.3.1/drivers/usb/storage/scsiglue.c' l='668' u='w'/>
<use f='linux-5.3.1/drivers/usb/storage/scsiglue.c' l='677' u='w' c='usb_stor_host_template_init'/>
