<dec f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='50' type='unsigned int'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='3710' u='w' c='pciserial_init_ports'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='3727' u='r' c='pciserial_detach_ports'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='3749' u='r' c='pciserial_suspend_ports'/>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_pci.c' l='3771' u='r' c='pciserial_resume_ports'/>
<offset>64</offset>
