<dec f='linux-5.3.1/include/crypto/skcipher.h' l='116' type='int (*)(struct crypto_skcipher *)'/>
<offset>192</offset>
<use f='linux-5.3.1/crypto/ctr.c' l='339' u='w' c='crypto_rfc3686_create'/>
<use f='linux-5.3.1/crypto/skcipher.c' l='904' u='r' c='crypto_skcipher_init_tfm'/>
<use f='linux-5.3.1/crypto/skcipher.c' l='905' u='r' c='crypto_skcipher_init_tfm'/>
<use f='linux-5.3.1/crypto/skcipher.c' l='1221' u='w' c='skcipher_alloc_instance_simple'/>
