<dec f='linux-5.3.1/include/sound/info.h' l='70' type='struct module *'/>
<offset>448</offset>
<use f='linux-5.3.1/sound/core/info.c' l='81' u='r' c='alloc_info_private'/>
<use f='linux-5.3.1/sound/core/info.c' l='85' u='r' c='alloc_info_private'/>
<use f='linux-5.3.1/sound/core/info.c' l='266' u='r' c='snd_info_entry_open'/>
<use f='linux-5.3.1/sound/core/info.c' l='280' u='r' c='snd_info_entry_release'/>
<use f='linux-5.3.1/sound/core/info.c' l='397' u='r' c='snd_info_text_entry_open'/>
<use f='linux-5.3.1/sound/core/info.c' l='419' u='r' c='snd_info_text_entry_release'/>
<use f='linux-5.3.1/sound/core/info.c' l='700' u='w' c='snd_info_create_entry'/>
