<dec f='linux-5.3.1/include/sound/core.h' l='91' type='struct module *'/>
<use f='linux-5.3.1/sound/core/control.c' l='56' u='r' c='snd_ctl_open'/>
<use f='linux-5.3.1/sound/core/control.c' l='80' u='r' c='snd_ctl_open'/>
<use f='linux-5.3.1/sound/core/control.c' l='126' u='r' c='snd_ctl_release'/>
<offset>3136</offset>
<doc f='linux-5.3.1/include/sound/core.h' l='91'>/* top-level module */</doc>
<use f='linux-5.3.1/sound/core/hwdep.c' l='88' u='r' c='snd_hwdep_open'/>
<use f='linux-5.3.1/sound/core/hwdep.c' l='141' u='r' c='snd_hwdep_open'/>
<use f='linux-5.3.1/sound/core/hwdep.c' l='150' u='r' c='snd_hwdep_release'/>
<use f='linux-5.3.1/sound/core/info.c' l='513' u='r' c='snd_info_card_create'/>
<use f='linux-5.3.1/sound/core/info.c' l='745' u='r' c='snd_info_create_card_entry'/>
<use f='linux-5.3.1/sound/core/init.c' l='206' u='w' c='snd_card_new'/>
<use f='linux-5.3.1/sound/core/pcm_native.c' l='2546' u='r' c='snd_pcm_open'/>
<use f='linux-5.3.1/sound/core/pcm_native.c' l='2584' u='r' c='snd_pcm_open'/>
<use f='linux-5.3.1/sound/core/pcm_native.c' l='2607' u='r' c='snd_pcm_release'/>
<use f='linux-5.3.1/sound/core/timer.c' l='925' u='r' c='snd_timer_new'/>
