<dec f='linux-5.3.1/include/sound/timer.h' l='60' type='struct module *'/>
<use f='linux-5.3.1/sound/core/hrtimer.c' l='143' u='w' c='snd_hrtimer_init'/>
<offset>128</offset>
<use f='linux-5.3.1/sound/core/timer.c' l='109' u='r' c='snd_timer_instance_new'/>
<use f='linux-5.3.1/sound/core/timer.c' l='317' u='r' c='snd_timer_open'/>
<use f='linux-5.3.1/sound/core/timer.c' l='399' u='r' c='snd_timer_close_locked'/>
<use f='linux-5.3.1/sound/core/timer.c' l='925' u='w' c='snd_timer_new'/>
