<dec f='linux-5.3.1/include/linux/interrupt.h' l='538' type='void (*)(struct softirq_action *)'/>
<offset>0</offset>
<use f='linux-5.3.1/kernel/softirq.c' l='292' u='r' c='__do_softirq'/>
<use f='linux-5.3.1/kernel/softirq.c' l='296' u='r' c='__do_softirq'/>
<use f='linux-5.3.1/kernel/softirq.c' l='457' u='w' c='open_softirq'/>
