<dec f='linux-5.3.1/include/linux/umh.h' l='29' type='int (*)(struct subprocess_info *, struct cred *)'/>
<offset>704</offset>
<use f='linux-5.3.1/kernel/umh.c' l='95' u='r' c='call_usermodehelper_exec_async'/>
<use f='linux-5.3.1/kernel/umh.c' l='96' u='r' c='call_usermodehelper_exec_async'/>
<use f='linux-5.3.1/kernel/umh.c' l='401' u='w' c='call_usermodehelper_setup'/>
<use f='linux-5.3.1/kernel/umh.c' l='429' u='w' c='call_usermodehelper_setup_file'/>
