<dec f='linux-5.3.1/scripts/mod/modpost.c' l='164' type='struct module *'/>
<use f='linux-5.3.1/scripts/mod/modpost.c' l='216' u='w' c='new_symbol'/>
<use f='linux-5.3.1/scripts/mod/modpost.c' l='330' u='r' c='sym_add_exported'/>
<use f='linux-5.3.1/scripts/mod/modpost.c' l='331' u='r' c='sym_add_exported'/>
<use f='linux-5.3.1/scripts/mod/modpost.c' l='334' u='w' c='sym_add_exported'/>
<use f='linux-5.3.1/scripts/mod/modpost.c' l='2103' u='r' c='check_exports'/>
<use f='linux-5.3.1/scripts/mod/modpost.c' l='2204' u='r' c='add_versions'/>
<use f='linux-5.3.1/scripts/mod/modpost.c' l='2206' u='w' c='add_versions'/>
<use f='linux-5.3.1/scripts/mod/modpost.c' l='2206' u='r' c='add_versions'/>
<use f='linux-5.3.1/scripts/mod/modpost.c' l='2220' u='r' c='add_versions'/>
<use f='linux-5.3.1/scripts/mod/modpost.c' l='2249' u='r' c='add_depends'/>
<use f='linux-5.3.1/scripts/mod/modpost.c' l='2250' u='r' c='add_depends'/>
<use f='linux-5.3.1/scripts/mod/modpost.c' l='2250' u='r' c='add_depends'/>
<use f='linux-5.3.1/scripts/mod/modpost.c' l='2259' u='r' c='add_depends'/>
<use f='linux-5.3.1/scripts/mod/modpost.c' l='2262' u='r' c='add_depends'/>
<use f='linux-5.3.1/scripts/mod/modpost.c' l='2265' u='r' c='add_depends'/>
<use f='linux-5.3.1/scripts/mod/modpost.c' l='2266' u='r' c='add_depends'/>
<use f='linux-5.3.1/scripts/mod/modpost.c' l='2270' u='r' c='add_depends'/>
<use f='linux-5.3.1/scripts/mod/modpost.c' l='2406' u='r' c='write_dump'/>
<offset>64</offset>
