<dec f='linux-5.3.1/include/linux/device-mapper.h' l='171' type='struct module *'/>
<offset>128</offset>
<use f='linux-5.3.1/drivers/md/dm-linear.c' l='225' u='w'/>
<use f='linux-5.3.1/drivers/md/dm-raid1.c' l='1461' u='w'/>
<use f='linux-5.3.1/drivers/md/dm-stripe.c' l='491' u='w'/>
<use f='linux-5.3.1/drivers/md/dm-target.c' l='37' u='r' c='get_target_type'/>
<use f='linux-5.3.1/drivers/md/dm-target.c' l='64' u='r' c='dm_put_target_type'/>
<use f='linux-5.3.1/drivers/md/dm-zero.c' l='62' u='w'/>
