<dec f='linux-5.3.1/include/linux/sched.h' l='740' type='struct mm_struct *'/>
<use f='linux-5.3.1/arch/x86/include/asm/tlbflush.h' l='255' u='r' c='nmi_uaccess_okay'/>
<use f='linux-5.3.1/arch/x86/include/asm/mmu_context.h' l='316' u='r' c='vma_is_foreign'/>
<use f='linux-5.3.1/arch/x86/include/asm/mmu_context.h' l='323' u='r' c='vma_is_foreign'/>
<offset>7936</offset>
<use f='linux-5.3.1/arch/x86/entry/common.c' l='366' u='r' c='do_fast_syscall_32'/>
<use f='linux-5.3.1/arch/x86/entry/vdso/vma.c' l='63' u='r' c='vdso_fix_landing'/>
<use f='linux-5.3.1/arch/x86/entry/vdso/vma.c' l='76' u='r' c='vdso_mremap'/>
<use f='linux-5.3.1/arch/x86/entry/vdso/vma.c' l='82' u='r' c='vdso_mremap'/>
<use f='linux-5.3.1/arch/x86/entry/vdso/vma.c' l='148' u='r' c='map_vdso'/>
<use f='linux-5.3.1/arch/x86/entry/vdso/vma.c' l='191' u='r' c='map_vdso'/>
<use f='linux-5.3.1/arch/x86/entry/vdso/vma.c' l='192' u='r' c='map_vdso'/>
<use f='linux-5.3.1/arch/x86/entry/vdso/vma.c' l='247' u='r' c='map_vdso_randomized'/>
<use f='linux-5.3.1/arch/x86/entry/vdso/vma.c' l='255' u='r' c='map_vdso_once'/>
<use f='linux-5.3.1/include/linux/sched/mm.h' l='166' u='r' c='in_vfork'/>
<use f='linux-5.3.1/include/linux/sched/mm.h' l='166' u='r' c='in_vfork'/>
<use f='linux-5.3.1/include/linux/sched/mm.h' l='373' u='r' c='membarrier_execve'/>
<use f='linux-5.3.1/arch/x86/events/intel/lbr.c' l='860' u='r' c='branch_type'/>
<use f='linux-5.3.1/arch/x86/include/asm/fpu/internal.h' l='610' u='r' c='switch_fpu_finish'/>
<use f='linux-5.3.1/arch/x86/ia32/ia32_signal.c' l='291' u='r' c='ia32_setup_frame'/>
<use f='linux-5.3.1/arch/x86/ia32/ia32_signal.c' l='292' u='r' c='ia32_setup_frame'/>
<use f='linux-5.3.1/arch/x86/ia32/ia32_signal.c' l='371' u='r' c='ia32_setup_rt_frame'/>
<use f='linux-5.3.1/arch/x86/kernel/cpu/common.c' l='1849' u='r' c='cpu_init'/>
<use f='linux-5.3.1/arch/x86/kernel/ldt.c' l='412' u='r' c='read_ldt'/>
<use f='linux-5.3.1/arch/x86/kernel/ldt.c' l='466' u='r' c='write_ldt'/>
<use f='linux-5.3.1/arch/x86/kernel/process_64.c' l='146' u='r' c='release_thread'/>
<use f='linux-5.3.1/arch/x86/kernel/process_64.c' l='317' u='r' c='x86_fsgsbase_read_task'/>
<use f='linux-5.3.1/arch/x86/kernel/process_64.c' l='318' u='r' c='x86_fsgsbase_read_task'/>
<use f='linux-5.3.1/arch/x86/kernel/process_64.c' l='323' u='r' c='x86_fsgsbase_read_task'/>
<use f='linux-5.3.1/arch/x86/kernel/process_64.c' l='633' u='r' c='set_personality_64bit'/>
<use f='linux-5.3.1/arch/x86/kernel/process_64.c' l='634' u='r' c='set_personality_64bit'/>
<use f='linux-5.3.1/arch/x86/kernel/process_64.c' l='669' u='r' c='__set_personality_ia32'/>
<use f='linux-5.3.1/arch/x86/kernel/process_64.c' l='670' u='r' c='__set_personality_ia32'/>
<use f='linux-5.3.1/arch/x86/kernel/step.c' l='36' u='r' c='convert_ip_to_linear'/>
<use f='linux-5.3.1/arch/x86/kernel/step.c' l='37' u='r' c='convert_ip_to_linear'/>
<use f='linux-5.3.1/arch/x86/kernel/step.c' l='38' u='r' c='convert_ip_to_linear'/>
<use f='linux-5.3.1/arch/x86/kernel/step.c' l='41' u='r' c='convert_ip_to_linear'/>
<use f='linux-5.3.1/arch/x86/kernel/step.c' l='49' u='r' c='convert_ip_to_linear'/>
<use f='linux-5.3.1/arch/x86/kernel/sys_x86_64.c' l='135' u='r' c='arch_get_unmapped_area'/>
<use f='linux-5.3.1/arch/x86/kernel/sys_x86_64.c' l='179' u='r' c='arch_get_unmapped_area_topdown'/>
<use f='linux-5.3.1/arch/x86/mm/fault.c' l='926' u='r' c='__bad_area'/>
<use f='linux-5.3.1/arch/x86/mm/fault.c' l='1293' u='r' c='do_user_addr_fault'/>
<use f='linux-5.3.1/arch/x86/mm/fault.c' l='1497' u='r' c='__do_page_fault'/>
<use f='linux-5.3.1/arch/x86/mm/hugetlbpage.c' l='148' u='r' c='hugetlb_get_unmapped_area'/>
<use f='linux-5.3.1/arch/x86/mm/mmap.c' l='153' u='r' c='get_mmap_base'/>
<use f='linux-5.3.1/arch/x86/mm/tlb.c' l='197' u='r' c='mm_mangle_tif_spec_ib'/>
<use f='linux-5.3.1/arch/x86/mm/tlb.c' l='202' u='r' c='cond_ibpb'/>
<use f='linux-5.3.1/arch/x86/mm/tlb.c' l='268' u='r' c='cond_ibpb'/>
<use f='linux-5.3.1/arch/x86/mm/tlb.c' l='270' u='r' c='cond_ibpb'/>
<use f='linux-5.3.1/arch/x86/mm/tlb.c' l='270' u='r' c='cond_ibpb'/>
<use f='linux-5.3.1/arch/x86/mm/tlb.c' l='270' u='r' c='cond_ibpb'/>
<use f='linux-5.3.1/arch/x86/mm/tlb.c' l='270' u='r' c='cond_ibpb'/>
<use f='linux-5.3.1/arch/x86/mm/tlb.c' l='270' u='r' c='cond_ibpb'/>
<use f='linux-5.3.1/arch/x86/mm/tlb.c' l='270' u='r' c='cond_ibpb'/>
<use f='linux-5.3.1/arch/x86/mm/tlb.c' l='270' u='r' c='cond_ibpb'/>
<use f='linux-5.3.1/arch/x86/mm/tlb.c' l='270' u='r' c='cond_ibpb'/>
<use f='linux-5.3.1/arch/x86/mm/tlb.c' l='270' u='r' c='cond_ibpb'/>
<use f='linux-5.3.1/arch/x86/mm/tlb.c' l='270' u='r' c='cond_ibpb'/>
<use f='linux-5.3.1/arch/x86/mm/tlb.c' l='270' u='r' c='cond_ibpb'/>
<use f='linux-5.3.1/arch/x86/mm/tlb.c' l='270' u='r' c='cond_ibpb'/>
<use f='linux-5.3.1/arch/x86/mm/tlb.c' l='270' u='r' c='cond_ibpb'/>
<use f='linux-5.3.1/arch/x86/mm/tlb.c' l='270' u='r' c='cond_ibpb'/>
<use f='linux-5.3.1/arch/x86/mm/tlb.c' l='270' u='r' c='cond_ibpb'/>
<use f='linux-5.3.1/arch/x86/mm/tlb.c' l='270' u='r' c='cond_ibpb'/>
<use f='linux-5.3.1/arch/x86/mm/tlb.c' l='270' u='r' c='cond_ibpb'/>
<use f='linux-5.3.1/arch/x86/mm/tlb.c' l='270' u='r' c='cond_ibpb'/>
<use f='linux-5.3.1/arch/x86/mm/tlb.c' l='270' u='r' c='cond_ibpb'/>
<use f='linux-5.3.1/arch/x86/mm/tlb.c' l='270' u='r' c='cond_ibpb'/>
<use f='linux-5.3.1/block/bio.c' l='1211' u='r' c='bio_uncopy_user'/>
<use f='linux-5.3.1/drivers/char/mem.c' l='731' u='r' c='get_unmapped_area_zero'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/gem/i915_gem_mman.c' l='86' u='r' c='i915_gem_mmap_ioctl'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/gem/i915_gem_userptr.c' l='360' u='r' c='i915_gem_userptr_init__mm_struct'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/gem/i915_gem_userptr.c' l='371' u='r' c='i915_gem_userptr_init__mm_struct'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/gem/i915_gem_userptr.c' l='372' u='r' c='i915_gem_userptr_init__mm_struct'/>
<use f='linux-5.3.1/drivers/gpu/drm/i915/gem/i915_gem_userptr.c' l='616' u='r' c='i915_gem_userptr_get_pages'/>
<use f='linux-5.3.1/fs/aio.c' l='463' u='r' c='aio_setup_ring'/>
<use f='linux-5.3.1/fs/aio.c' l='703' u='r' c='ioctx_alloc'/>
<use f='linux-5.3.1/fs/aio.c' l='1050' u='r' c='lookup_ioctx'/>
<use f='linux-5.3.1/fs/aio.c' l='1334' u='r' c='__do_sys_io_setup'/>
<use f='linux-5.3.1/fs/aio.c' l='1366' u='r' c='__do_compat_sys_io_setup'/>
<use f='linux-5.3.1/fs/aio.c' l='1395' u='r' c='__do_sys_io_destroy'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='117' u='r' c='set_brk'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='117' u='r' c='set_brk'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='229' u='r' c='create_elf_tables'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='244' macro='1' u='r' c='create_elf_tables'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='279' u='r' c='create_elf_tables'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='302' u='r' c='create_elf_tables'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='311' u='r' c='create_elf_tables'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='311' u='r' c='create_elf_tables'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='323' u='r' c='create_elf_tables'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='326' u='r' c='create_elf_tables'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='326' u='r' c='create_elf_tables'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='338' u='r' c='create_elf_tables'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='1130' u='r' c='load_elf_binary'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='1131' u='r' c='load_elf_binary'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='1132' u='r' c='load_elf_binary'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='1133' u='r' c='load_elf_binary'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='1134' u='r' c='load_elf_binary'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='1145' u='r' c='load_elf_binary'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='1145' u='r' c='load_elf_binary'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='1148' u='r' c='load_elf_binary'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='1148' u='r' c='load_elf_binary'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='1149' u='r' c='load_elf_binary'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='1616' u='r' c='fill_files_note'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='1634' u='r' c='fill_files_note'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='1671' u='r' c='fill_files_note'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='1835' u='r' c='fill_note_info'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='1866' u='r' c='fill_note_info'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='1872' u='r' c='fill_note_info'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='2164' u='r' c='first_vma'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='2246' u='r' c='elf_core_dump'/>
<use f='linux-5.3.1/fs/binfmt_elf.c' l='2249' u='r' c='elf_core_dump'/>
<use f='linux-5.3.1/fs/coredump.c' l='162' u='r' c='cn_print_exe_file'/>
<use f='linux-5.3.1/fs/coredump.c' l='350' u='r' c='zap_process'/>
<use f='linux-5.3.1/fs/coredump.c' l='419' u='r' c='zap_threads'/>
<use f='linux-5.3.1/fs/coredump.c' l='421' u='r' c='zap_threads'/>
<use f='linux-5.3.1/fs/coredump.c' l='439' u='r' c='coredump_wait'/>
<use f='linux-5.3.1/fs/coredump.c' l='569' u='r' c='do_coredump'/>
<use f='linux-5.3.1/fs/exec.c' l='185' u='r' c='acct_arg_size'/>
<use f='linux-5.3.1/fs/exec.c' l='697' u='r' c='setup_arg_pages'/>
<use f='linux-5.3.1/fs/exec.c' l='793' u='r' c='setup_arg_pages'/>
<use f='linux-5.3.1/fs/exec.c' l='1017' u='r' c='exec_mmap'/>
<use f='linux-5.3.1/fs/exec.c' l='1036' u='w' c='exec_mmap'/>
<use f='linux-5.3.1/fs/exec.c' l='1039' u='r' c='exec_mmap'/>
<use f='linux-5.3.1/fs/exec.c' l='1357' u='r' c='setup_new_exec'/>
<use f='linux-5.3.1/fs/exec.c' l='1369' u='r' c='setup_new_exec'/>
<use f='linux-5.3.1/fs/exec.c' l='1371' u='r' c='setup_new_exec'/>
<use f='linux-5.3.1/fs/exec.c' l='1381' u='r' c='setup_new_exec'/>
<use f='linux-5.3.1/fs/exec.c' l='1464' u='r' c='install_exec_creds'/>
<use f='linux-5.3.1/fs/exec.c' l='1934' u='r' c='set_binfmt'/>
<use f='linux-5.3.1/fs/hugetlbfs/inode.c' l='427' u='r' c='remove_inode_hugepages'/>
<use f='linux-5.3.1/fs/hugetlbfs/inode.c' l='578' u='r' c='hugetlbfs_fallocate'/>
<use f='linux-5.3.1/fs/io_uring.c' l='2725' u='r' c='io_sq_offload_start'/>
<use f='linux-5.3.1/fs/io_uring.c' l='2726' u='r' c='io_sq_offload_start'/>
<use f='linux-5.3.1/fs/io_uring.c' l='2968' u='r' c='io_sqe_buffer_register'/>
<use f='linux-5.3.1/fs/io_uring.c' l='2986' u='r' c='io_sqe_buffer_register'/>
<use f='linux-5.3.1/fs/notify/inotify/inotify_user.c' l='636' u='r' c='inotify_new_group'/>
<use f='linux-5.3.1/fs/proc/base.c' l='1079' u='r' c='__set_oom_adj'/>
<use f='linux-5.3.1/fs/proc/base.c' l='1080' u='r' c='__set_oom_adj'/>
<use f='linux-5.3.1/fs/proc/base.c' l='1722' u='r' c='task_dump_owner'/>
<use f='linux-5.3.1/fs/proc/inode.c' l='320' u='r' c='proc_reg_get_unmapped_area'/>
<use f='linux-5.3.1/fs/ramfs/file-mmu.c' l='38' u='r' c='ramfs_mmu_get_unmapped_area'/>
<use f='linux-5.3.1/init/init_task.c' l='78' u='w'/>
<use f='linux-5.3.1/ipc/shm.c' l='1547' u='r' c='do_shmat'/>
<use f='linux-5.3.1/ipc/shm.c' l='1557' u='r' c='do_shmat'/>
<use f='linux-5.3.1/ipc/shm.c' l='1567' u='r' c='do_shmat'/>
<use f='linux-5.3.1/ipc/shm.c' l='1628' u='r' c='ksys_shmdt'/>
<use f='linux-5.3.1/kernel/acct.c' l='539' u='r' c='acct_collect'/>
<use f='linux-5.3.1/kernel/acct.c' l='542' u='r' c='acct_collect'/>
<use f='linux-5.3.1/kernel/acct.c' l='543' u='r' c='acct_collect'/>
<use f='linux-5.3.1/kernel/acct.c' l='548' u='r' c='acct_collect'/>
<use f='linux-5.3.1/kernel/audit.c' l='2152' u='r' c='audit_log_task_info'/>
<use f='linux-5.3.1/kernel/auditsc.c' l='1002' u='r' c='audit_log_execve_info'/>
<use f='linux-5.3.1/kernel/auditsc.c' l='2567' u='r' c='audit_log_task'/>
<use f='linux-5.3.1/kernel/cpu.c' l='828' u='r' c='clear_tasks_mm_cpumask'/>
<use f='linux-5.3.1/kernel/cred.c' l='459' u='r' c='commit_creds'/>
<use f='linux-5.3.1/kernel/cred.c' l='460' u='r' c='commit_creds'/>
<use f='linux-5.3.1/kernel/events/callchain.c' l='206' u='r' c='get_perf_callchain'/>
<use f='linux-5.3.1/kernel/events/core.c' l='6424' u='r' c='perf_virt_to_phys'/>
<use f='linux-5.3.1/kernel/events/uprobes.c' l='1433' u='r' c='__create_xol_area'/>
<use f='linux-5.3.1/kernel/events/uprobes.c' l='1481' u='r' c='get_xol_area'/>
<use f='linux-5.3.1/kernel/events/uprobes.c' l='1590' u='r' c='xol_free_insn_slot'/>
<use f='linux-5.3.1/kernel/events/uprobes.c' l='1590' u='r' c='xol_free_insn_slot'/>
<use f='linux-5.3.1/kernel/events/uprobes.c' l='1597' u='r' c='xol_free_insn_slot'/>
<use f='linux-5.3.1/kernel/events/uprobes.c' l='1751' u='r' c='uprobe_copy_process'/>
<use f='linux-5.3.1/kernel/events/uprobes.c' l='1759' u='r' c='uprobe_copy_process'/>
<use f='linux-5.3.1/kernel/events/uprobes.c' l='1770' u='r' c='uprobe_copy_process'/>
<use f='linux-5.3.1/kernel/events/uprobes.c' l='1790' u='r' c='get_trampoline_vaddr'/>
<use f='linux-5.3.1/kernel/events/uprobes.c' l='1790' u='r' c='get_trampoline_vaddr'/>
<use f='linux-5.3.1/kernel/events/uprobes.c' l='1790' u='r' c='get_trampoline_vaddr'/>
<use f='linux-5.3.1/kernel/events/uprobes.c' l='1790' u='r' c='get_trampoline_vaddr'/>
<use f='linux-5.3.1/kernel/events/uprobes.c' l='1790' u='r' c='get_trampoline_vaddr'/>
<use f='linux-5.3.1/kernel/events/uprobes.c' l='1992' u='r' c='find_active_uprobe'/>
<use f='linux-5.3.1/kernel/events/uprobes.c' l='2046' u='r' c='handler_chain'/>
<use f='linux-5.3.1/kernel/events/uprobes.c' l='2265' u='r' c='uprobe_pre_sstep_notifier'/>
<use f='linux-5.3.1/kernel/events/uprobes.c' l='2268' u='r' c='uprobe_pre_sstep_notifier'/>
<use f='linux-5.3.1/kernel/events/uprobes.c' l='2284' u='r' c='uprobe_post_sstep_notifier'/>
<use f='linux-5.3.1/kernel/exit.c' l='499' u='r' c='exit_mm'/>
<use f='linux-5.3.1/kernel/exit.c' l='542' u='w' c='exit_mm'/>
<use f='linux-5.3.1/kernel/exit.c' l='846' u='r' c='do_exit'/>
<use f='linux-5.3.1/kernel/exit.c' l='847' u='r' c='do_exit'/>
<use f='linux-5.3.1/kernel/exit.c' l='855' u='r' c='do_exit'/>
<use f='linux-5.3.1/kernel/exit.c' l='856' u='r' c='do_exit'/>
<use f='linux-5.3.1/kernel/fork.c' l='676' u='r' c='__mmdrop'/>
<use f='linux-5.3.1/kernel/fork.c' l='1017' u='r' c='mm_init'/>
<use f='linux-5.3.1/kernel/fork.c' l='1018' u='r' c='mm_init'/>
<use f='linux-5.3.1/kernel/fork.c' l='1019' u='r' c='mm_init'/>
<use f='linux-5.3.1/kernel/fork.c' l='1168' u='r' c='get_task_exe_file'/>
<use f='linux-5.3.1/kernel/fork.c' l='1192' u='r' c='get_task_mm'/>
<use f='linux-5.3.1/kernel/fork.c' l='1214' u='r' c='mm_access'/>
<use f='linux-5.3.1/kernel/fork.c' l='1380' u='w' c='copy_mm'/>
<use f='linux-5.3.1/kernel/fork.c' l='1388' u='r' c='copy_mm'/>
<use f='linux-5.3.1/kernel/fork.c' l='1402' u='r' c='copy_mm'/>
<use f='linux-5.3.1/kernel/fork.c' l='1407' u='w' c='copy_mm'/>
<use f='linux-5.3.1/kernel/fork.c' l='2263' u='r' c='copy_process'/>
<use f='linux-5.3.1/kernel/fork.c' l='2264' u='r' c='copy_process'/>
<use f='linux-5.3.1/kernel/fork.c' l='2265' u='r' c='copy_process'/>
<use f='linux-5.3.1/kernel/futex.c' l='526' u='r' c='get_futex_key'/>
<use f='linux-5.3.1/kernel/futex.c' l='749' u='r' c='fault_in_user_writeable'/>
<use f='linux-5.3.1/kernel/ptrace.c' l='340' u='r' c='__ptrace_may_access'/>
<use f='linux-5.3.1/kernel/sched/core.c' l='1971' u='r' c='select_fallback_rq'/>
<use f='linux-5.3.1/kernel/sched/core.c' l='3221' u='r' c='context_switch'/>
<use f='linux-5.3.1/kernel/sched/core.c' l='3244' u='r' c='context_switch'/>
<use f='linux-5.3.1/kernel/sched/core.c' l='4589' u='r' c='__sched_setscheduler'/>
<use f='linux-5.3.1/kernel/sched/core.c' l='4590' u='r' c='__sched_setscheduler'/>
<use f='linux-5.3.1/kernel/sched/membarrier.c' l='75' u='r' c='membarrier_global_expedited'/>
<use f='linux-5.3.1/kernel/sched/membarrier.c' l='75' u='r' c='membarrier_global_expedited'/>
<use f='linux-5.3.1/kernel/sched/membarrier.c' l='110' u='r' c='membarrier_private_expedited'/>
<use f='linux-5.3.1/kernel/sched/membarrier.c' l='114' u='r' c='membarrier_private_expedited'/>
<use f='linux-5.3.1/kernel/sched/membarrier.c' l='154' u='r' c='membarrier_private_expedited'/>
<use f='linux-5.3.1/kernel/sched/membarrier.c' l='154' u='r' c='membarrier_private_expedited'/>
<use f='linux-5.3.1/kernel/sched/membarrier.c' l='183' u='r' c='membarrier_register_global_expedited'/>
<use f='linux-5.3.1/kernel/sched/membarrier.c' l='215' u='r' c='membarrier_register_private_expedited'/>
<use f='linux-5.3.1/kernel/signal.c' l='2087' u='r' c='may_ptrace_stop'/>
<use f='linux-5.3.1/kernel/signal.c' l='2088' u='r' c='may_ptrace_stop'/>
<use f='linux-5.3.1/kernel/signal.c' l='2088' u='r' c='may_ptrace_stop'/>
<use f='linux-5.3.1/kernel/sys.c' l='2097' u='r' c='prctl_set_mm'/>
<use f='linux-5.3.1/kernel/sys.c' l='2296' u='r' c='__do_sys_prctl'/>
<use f='linux-5.3.1/kernel/sys.c' l='2303' u='r' c='__do_sys_prctl'/>
<use f='linux-5.3.1/kernel/sys.c' l='2445' u='r' c='__do_sys_prctl'/>
<use f='linux-5.3.1/kernel/sys.c' l='2450' u='r' c='__do_sys_prctl'/>
<use f='linux-5.3.1/kernel/sys.c' l='2453' u='r' c='__do_sys_prctl'/>
<use f='linux-5.3.1/kernel/sys.c' l='2455' u='r' c='__do_sys_prctl'/>
<use f='linux-5.3.1/kernel/sys.c' l='2456' u='r' c='__do_sys_prctl'/>
<use f='linux-5.3.1/kernel/trace/ring_buffer.c' l='1191' u='r' c='__rb_allocate_pages'/>
<use f='linux-5.3.1/kernel/trace/trace_uprobe.c' l='1034' u='r' c='__uprobe_perf_filter'/>
<use f='linux-5.3.1/kernel/trace/trace_uprobe.c' l='1044' u='r' c='uprobe_filter_event'/>
<use f='linux-5.3.1/kernel/trace/trace_uprobe.c' l='1174' u='r' c='uprobe_perf_func'/>
<use f='linux-5.3.1/kernel/tsacct.c' l='121' u='r' c='__acct_update_integrals'/>
<use f='linux-5.3.1/kernel/tsacct.c' l='136' u='r' c='__acct_update_integrals'/>
<use f='linux-5.3.1/kernel/tsacct.c' l='137' u='r' c='__acct_update_integrals'/>
<use f='linux-5.3.1/lib/is_single_threaded.c' l='18' u='r' c='current_is_single_threaded'/>
<use f='linux-5.3.1/lib/is_single_threaded.c' l='37' u='r' c='current_is_single_threaded'/>
<use f='linux-5.3.1/lib/is_single_threaded.c' l='39' u='r' c='current_is_single_threaded'/>
<use f='linux-5.3.1/mm/filemap.c' l='857' u='r' c='__add_to_page_cache_locked'/>
<use f='linux-5.3.1/mm/gup.c' l='1243' u='r' c='__mm_populate'/>
<use f='linux-5.3.1/mm/gup.c' l='1314' u='r' c='get_dump_page'/>
<use f='linux-5.3.1/mm/gup.c' l='1618' u='r' c='get_user_pages'/>
<use f='linux-5.3.1/mm/gup.c' l='1657' u='r' c='get_user_pages_locked'/>
<use f='linux-5.3.1/mm/gup.c' l='1681' u='r' c='get_user_pages_unlocked'/>
<use f='linux-5.3.1/mm/gup.c' l='2279' u='r' c='gup_pgd_range'/>
<use f='linux-5.3.1/mm/gup.c' l='2374' u='r' c='__gup_longterm_unlocked'/>
<use f='linux-5.3.1/mm/gup.c' l='2375' u='r' c='__gup_longterm_unlocked'/>
<use f='linux-5.3.1/mm/gup.c' l='2378' u='r' c='__gup_longterm_unlocked'/>
<use f='linux-5.3.1/mm/madvise.c' l='431' u='r' c='madvise_free_pte_range'/>
<use f='linux-5.3.1/mm/madvise.c' l='528' u='r' c='madvise_dontneed_free'/>
<use f='linux-5.3.1/mm/madvise.c' l='529' u='r' c='madvise_dontneed_free'/>
<use f='linux-5.3.1/mm/madvise.c' l='610' u='r' c='madvise_remove'/>
<use f='linux-5.3.1/mm/madvise.c' l='616' u='r' c='madvise_remove'/>
<use f='linux-5.3.1/mm/madvise.c' l='839' u='r' c='__do_sys_madvise'/>
<use f='linux-5.3.1/mm/madvise.c' l='842' u='r' c='__do_sys_madvise'/>
<use f='linux-5.3.1/mm/madvise.c' l='850' u='r' c='__do_sys_madvise'/>
<use f='linux-5.3.1/mm/madvise.c' l='887' u='r' c='__do_sys_madvise'/>
<use f='linux-5.3.1/mm/madvise.c' l='892' u='r' c='__do_sys_madvise'/>
<use f='linux-5.3.1/mm/madvise.c' l='894' u='r' c='__do_sys_madvise'/>
<use f='linux-5.3.1/mm/memory.c' l='163' u='r' c='add_mm_counter_fast'/>
<use f='linux-5.3.1/mm/memory.c' l='178' u='r' c='check_sync_rss_stat'/>
<use f='linux-5.3.1/mm/memory.c' l='467' u='r' c='add_mm_rss_vec'/>
<use f='linux-5.3.1/mm/memory.c' l='4397' u='r' c='print_vma_addr'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='874' u='r' c='do_get_mempolicy'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='1169' u='r' c='new_page'/>
<use f='linux-5.3.1/mm/mempolicy.c' l='1220' u='r' c='do_mbind'/>
<use f='linux-5.3.1/mm/mincore.c' l='213' u='r' c='do_mincore'/>
<use f='linux-5.3.1/mm/mincore.c' l='285' u='r' c='__do_sys_mincore'/>
<use f='linux-5.3.1/mm/mincore.c' l='287' u='r' c='__do_sys_mincore'/>
<use f='linux-5.3.1/mm/mlock.c' l='530' u='r' c='mlock_fixup'/>
<use f='linux-5.3.1/mm/mlock.c' l='597' u='r' c='apply_vma_lock_flags'/>
<use f='linux-5.3.1/mm/mlock.c' l='646' u='r' c='count_mm_mlocked_page_nr'/>
<use f='linux-5.3.1/mm/mlock.c' l='687' u='r' c='do_mlock'/>
<use f='linux-5.3.1/mm/mlock.c' l='690' u='r' c='do_mlock'/>
<use f='linux-5.3.1/mm/mlock.c' l='698' u='r' c='do_mlock'/>
<use f='linux-5.3.1/mm/mlock.c' l='706' u='r' c='do_mlock'/>
<use f='linux-5.3.1/mm/mlock.c' l='741' u='r' c='__do_sys_munlock'/>
<use f='linux-5.3.1/mm/mlock.c' l='744' u='r' c='__do_sys_munlock'/>
<use f='linux-5.3.1/mm/mlock.c' l='764' u='r' c='apply_mlockall_flags'/>
<use f='linux-5.3.1/mm/mlock.c' l='766' u='r' c='apply_mlockall_flags'/>
<use f='linux-5.3.1/mm/mlock.c' l='769' u='r' c='apply_mlockall_flags'/>
<use f='linux-5.3.1/mm/mlock.c' l='781' u='r' c='apply_mlockall_flags'/>
<use f='linux-5.3.1/mm/mlock.c' l='810' u='r' c='__do_sys_mlockall'/>
<use f='linux-5.3.1/mm/mlock.c' l='814' u='r' c='__do_sys_mlockall'/>
<use f='linux-5.3.1/mm/mlock.c' l='817' u='r' c='__do_sys_mlockall'/>
<use f='linux-5.3.1/mm/mlock.c' l='828' u='r' c='__x64_sys_munlockall'/>
<use f='linux-5.3.1/mm/mlock.c' l='831' u='r' c='__x64_sys_munlockall'/>
<use f='linux-5.3.1/mm/mmap.c' l='197' u='r' c='__do_sys_brk'/>
<use f='linux-5.3.1/mm/mmap.c' l='1391' u='r' c='do_mmap'/>
<use f='linux-5.3.1/mm/mmap.c' l='1707' u='r' c='mmap_region'/>
<use f='linux-5.3.1/mm/mmap.c' l='1827' u='r' c='mmap_region'/>
<use f='linux-5.3.1/mm/mmap.c' l='1879' u='r' c='unmapped_area'/>
<use f='linux-5.3.1/mm/mmap.c' l='1974' u='r' c='unmapped_area_topdown'/>
<use f='linux-5.3.1/mm/mmap.c' l='2197' u='r' c='get_unmapped_area'/>
<use f='linux-5.3.1/mm/mmap.c' l='2847' u='r' c='__vm_munmap'/>
<use f='linux-5.3.1/mm/mmap.c' l='2889' u='r' c='__do_sys_remap_file_pages'/>
<use f='linux-5.3.1/mm/mmap.c' l='2988' u='r' c='do_brk_flags'/>
<use f='linux-5.3.1/mm/mmap.c' l='3060' u='r' c='vm_brk_flags'/>
<use f='linux-5.3.1/mm/mmap.c' l='3336' u='r' c='special_mapping_mremap'/>
<use f='linux-5.3.1/mm/mmu_context.c' l='33' u='w' c='use_mm'/>
<use f='linux-5.3.1/mm/mmu_context.c' l='59' u='w' c='unuse_mm'/>
<use f='linux-5.3.1/mm/mprotect.c' l='340' u='r' c='prot_none_walk'/>
<use f='linux-5.3.1/mm/mprotect.c' l='340' u='r' c='prot_none_walk'/>
<use f='linux-5.3.1/mm/mprotect.c' l='485' u='r' c='do_mprotect_pkey'/>
<use f='linux-5.3.1/mm/mprotect.c' l='493' u='r' c='do_mprotect_pkey'/>
<use f='linux-5.3.1/mm/mprotect.c' l='496' u='r' c='do_mprotect_pkey'/>
<use f='linux-5.3.1/mm/mprotect.c' l='575' u='r' c='do_mprotect_pkey'/>
<use f='linux-5.3.1/mm/mprotect.c' l='605' u='r' c='__do_sys_pkey_alloc'/>
<use f='linux-5.3.1/mm/mprotect.c' l='606' u='r' c='__do_sys_pkey_alloc'/>
<use f='linux-5.3.1/mm/mprotect.c' l='614' u='r' c='__do_sys_pkey_alloc'/>
<use f='linux-5.3.1/mm/mprotect.c' l='619' u='r' c='__do_sys_pkey_alloc'/>
<use f='linux-5.3.1/mm/mprotect.c' l='627' u='r' c='__do_sys_pkey_free'/>
<use f='linux-5.3.1/mm/mprotect.c' l='628' u='r' c='__do_sys_pkey_free'/>
<use f='linux-5.3.1/mm/mprotect.c' l='629' u='r' c='__do_sys_pkey_free'/>
<use f='linux-5.3.1/mm/mremap.c' l='436' u='r' c='vma_to_resize'/>
<use f='linux-5.3.1/mm/mremap.c' l='504' u='r' c='mremap_to'/>
<use f='linux-5.3.1/mm/mremap.c' l='599' u='r' c='__do_sys_mremap'/>
<use f='linux-5.3.1/mm/mremap.c' l='629' u='r' c='__do_sys_mremap'/>
<use f='linux-5.3.1/mm/mremap.c' l='720' u='r' c='__do_sys_mremap'/>
<use f='linux-5.3.1/mm/mremap.c' l='722' u='r' c='__do_sys_mremap'/>
<use f='linux-5.3.1/mm/msync.c' l='35' u='r' c='__do_sys_msync'/>
<use f='linux-5.3.1/mm/oom_kill.c' l='140' u='r' c='find_lock_task_mm'/>
<use f='linux-5.3.1/mm/oom_kill.c' l='217' u='r' c='oom_badness'/>
<use f='linux-5.3.1/mm/oom_kill.c' l='227' u='r' c='oom_badness'/>
<use f='linux-5.3.1/mm/oom_kill.c' l='227' u='r' c='oom_badness'/>
<use f='linux-5.3.1/mm/oom_kill.c' l='228' u='r' c='oom_badness'/>
<use f='linux-5.3.1/mm/oom_kill.c' l='404' u='r' c='dump_task'/>
<use f='linux-5.3.1/mm/oom_kill.c' l='404' u='r' c='dump_task'/>
<use f='linux-5.3.1/mm/oom_kill.c' l='405' u='r' c='dump_task'/>
<use f='linux-5.3.1/mm/oom_kill.c' l='406' u='r' c='dump_task'/>
<use f='linux-5.3.1/mm/oom_kill.c' l='495' c='process_shares_mm'/>
<use f='linux-5.3.1/mm/oom_kill.c' l='495' u='a' c='process_shares_mm'/>
<use f='linux-5.3.1/mm/oom_kill.c' l='495' u='r' c='process_shares_mm'/>
<use f='linux-5.3.1/mm/oom_kill.c' l='495' u='a' c='process_shares_mm'/>
<use f='linux-5.3.1/mm/oom_kill.c' l='495' u='r' c='process_shares_mm'/>
<use f='linux-5.3.1/mm/oom_kill.c' l='698' u='r' c='mark_oom_victim'/>
<use f='linux-5.3.1/mm/oom_kill.c' l='811' u='r' c='task_will_free_mem'/>
<use f='linux-5.3.1/mm/oom_kill.c' l='873' u='r' c='__oom_kill_process'/>
<use f='linux-5.3.1/mm/oom_kill.c' l='889' u='r' c='__oom_kill_process'/>
<use f='linux-5.3.1/mm/oom_kill.c' l='890' u='r' c='__oom_kill_process'/>
<use f='linux-5.3.1/mm/oom_kill.c' l='891' u='r' c='__oom_kill_process'/>
<use f='linux-5.3.1/mm/oom_kill.c' l='892' u='r' c='__oom_kill_process'/>
<use f='linux-5.3.1/mm/oom_kill.c' l='1086' u='r' c='out_of_memory'/>
<use f='linux-5.3.1/mm/shmem.c' l='157' u='r' c='shmem_acct_size'/>
<use f='linux-5.3.1/mm/shmem.c' l='171' u='r' c='shmem_reacct_size'/>
<use f='linux-5.3.1/mm/shmem.c' l='190' u='r' c='shmem_acct_block'/>
<use f='linux-5.3.1/mm/shmem.c' l='1618' u='r' c='shmem_swapin_page'/>
<use f='linux-5.3.1/mm/shmem.c' l='1753' u='r' c='shmem_getpage_gfp'/>
<use f='linux-5.3.1/mm/shmem.c' l='2072' u='r' c='shmem_get_unmapped_area'/>
<use f='linux-5.3.1/mm/swapfile.c' l='2532' u='r' c='__do_sys_swapoff'/>
<use f='linux-5.3.1/mm/swapfile.c' l='2558' u='r' c='__do_sys_swapoff'/>
<use f='linux-5.3.1/mm/util.c' l='383' u='r' c='vm_mmap_pgoff'/>
<use f='linux-5.3.1/mm/vmacache.c' l='33' u='r' c='vmacache_valid_mm'/>
<use f='linux-5.3.1/net/ipv4/tcp.c' l='1757' u='r' c='tcp_zerocopy_receive'/>
<use f='linux-5.3.1/net/ipv4/tcp.c' l='1760' u='r' c='tcp_zerocopy_receive'/>
<use f='linux-5.3.1/net/ipv4/tcp.c' l='1819' u='r' c='tcp_zerocopy_receive'/>
<use f='linux-5.3.1/security/keys/keyctl.c' l='1587' u='r' c='keyctl_session_to_parent'/>
