<dec f='linux-5.3.1/include/net/act_api.h' l='92' type='int (*)(struct net *, struct nlattr *, struct nlattr *, struct tc_action **, int, int, bool, struct tcf_proto *, struct netlink_ext_ack *)'/>
<offset>704</offset>
<use f='linux-5.3.1/net/sched/act_api.c' l='560' u='r' c='tcf_register_action'/>
<use f='linux-5.3.1/net/sched/act_api.c' l='915' u='r' c='tcf_action_init_1'/>
<use f='linux-5.3.1/net/sched/act_api.c' l='918' u='r' c='tcf_action_init_1'/>
