<dec f='linux-5.3.1/include/net/tcp.h' l='1022' type='void (*)(struct sock *)'/>
<offset>192</offset>
<doc f='linux-5.3.1/include/net/tcp.h' l='1021'>/* initialize private data (optional) */</doc>
<use f='linux-5.3.1/net/ipv4/tcp_cong.c' l='182' u='r' c='tcp_init_congestion_control'/>
<use f='linux-5.3.1/net/ipv4/tcp_cong.c' l='183' u='r' c='tcp_init_congestion_control'/>
<use f='linux-5.3.1/net/ipv4/tcp_cubic.c' l='459' u='w'/>
