<dec f='linux-5.3.1/include/linux/tty_driver.h' l='257' type='int (*)(struct tty_driver *, struct tty_struct *)'/>
<offset>64</offset>
<use f='linux-5.3.1/drivers/tty/pty.c' l='766' u='w'/>
<use f='linux-5.3.1/drivers/tty/pty.c' l='784' u='w'/>
<use f='linux-5.3.1/drivers/tty/serial/serial_core.c' l='2457' u='w'/>
<use f='linux-5.3.1/drivers/tty/tty_io.c' l='1227' u='r' c='tty_driver_install_tty'/>
<use f='linux-5.3.1/drivers/tty/tty_io.c' l='1227' u='r' c='tty_driver_install_tty'/>
<use f='linux-5.3.1/drivers/tty/vt/vt.c' l='3389' u='w'/>
