<dec f='linux-5.3.1/include/linux/serial_core.h' l='309' type='int'/>
<offset>256</offset>
<use f='linux-5.3.1/drivers/tty/serial/8250/8250_core.c' l='1162' u='w' c='serial8250_init'/>
<use f='linux-5.3.1/drivers/tty/serial/serial_core.c' l='1900' u='r' c='uart_proc_show'/>
<use f='linux-5.3.1/drivers/tty/serial/serial_core.c' l='2523' u='r' c='uart_register_driver'/>
<use f='linux-5.3.1/drivers/tty/serial/serial_core.c' l='2527' u='r' c='uart_register_driver'/>
<use f='linux-5.3.1/drivers/tty/serial/serial_core.c' l='2549' u='r' c='uart_register_driver'/>
<use f='linux-5.3.1/drivers/tty/serial/serial_core.c' l='2561' u='r' c='uart_register_driver'/>
<use f='linux-5.3.1/drivers/tty/serial/serial_core.c' l='2586' u='r' c='uart_unregister_driver'/>
<use f='linux-5.3.1/drivers/tty/serial/serial_core.c' l='2790' u='r' c='uart_add_one_port'/>
