<dec f='linux-5.3.1/include/net/af_unix.h' l='55' type='struct sock'/>
<offset>0</offset>
<doc f='linux-5.3.1/include/net/af_unix.h' l='54'>/* WARNING: sk has to be the first member */</doc>
<use f='linux-5.3.1/net/unix/af_unix.c' l='367' u='a' c='unix_dgram_peer_wake_relay'/>
<use f='linux-5.3.1/net/unix/garbage.c' l='161' u='a' c='scan_children'/>
<use f='linux-5.3.1/net/unix/garbage.c' l='236' u='m' c='unix_gc'/>
<use f='linux-5.3.1/net/unix/garbage.c' l='252' u='a' c='unix_gc'/>
<use f='linux-5.3.1/net/unix/garbage.c' l='271' u='a' c='unix_gc'/>
<use f='linux-5.3.1/net/unix/garbage.c' l='282' u='a' c='unix_gc'/>
