<dec f='linux-5.3.1/include/linux/mm_types.h' l='318' type='struct rb_node'/>
<offset>0</offset>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='m' c='vma_interval_tree_compute_subtree_last'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='m' c='vma_interval_tree_compute_subtree_last'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='m' c='vma_interval_tree_compute_subtree_last'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='r' c='vma_interval_tree_compute_subtree_last'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='m' c='vma_interval_tree_compute_subtree_last'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='m' c='vma_interval_tree_compute_subtree_last'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='m' c='vma_interval_tree_compute_subtree_last'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='m' c='vma_interval_tree_compute_subtree_last'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='r' c='vma_interval_tree_compute_subtree_last'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='m' c='vma_interval_tree_compute_subtree_last'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='r' c='vma_interval_tree_augment_propagate'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='a' c='vma_interval_tree_augment_propagate'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='r' c='vma_interval_tree_augment_copy'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='r' c='vma_interval_tree_augment_copy'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='r' c='vma_interval_tree_augment_rotate'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='r' c='vma_interval_tree_augment_rotate'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='r' c='vma_interval_tree_insert'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='m' c='vma_interval_tree_insert'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='m' c='vma_interval_tree_insert'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='a' c='vma_interval_tree_insert'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='a' c='vma_interval_tree_insert'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='a' c='vma_interval_tree_remove'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='m' c='vma_interval_tree_subtree_search'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='m' c='vma_interval_tree_subtree_search'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='m' c='vma_interval_tree_subtree_search'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='r' c='vma_interval_tree_subtree_search'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='m' c='vma_interval_tree_subtree_search'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='m' c='vma_interval_tree_subtree_search'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='m' c='vma_interval_tree_subtree_search'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='m' c='vma_interval_tree_subtree_search'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='r' c='vma_interval_tree_subtree_search'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='m' c='vma_interval_tree_subtree_search'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='r' c='vma_interval_tree_iter_first'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='r' c='vma_interval_tree_iter_first'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='m' c='vma_interval_tree_iter_next'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='r' c='vma_interval_tree_iter_next'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='a' c='vma_interval_tree_iter_next'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='a' c='vma_interval_tree_iter_next'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='r' c='vma_interval_tree_iter_next'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='23' u='m' c='vma_interval_tree_iter_next'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='38' u='m' c='vma_interval_tree_insert_after'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='40' u='m' c='vma_interval_tree_insert_after'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='42' u='m' c='vma_interval_tree_insert_after'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='42' u='m' c='vma_interval_tree_insert_after'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='43' u='r' c='vma_interval_tree_insert_after'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='42' u='m' c='vma_interval_tree_insert_after'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='46' u='m' c='vma_interval_tree_insert_after'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='47' u='m' c='vma_interval_tree_insert_after'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='47' u='m' c='vma_interval_tree_insert_after'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='48' u='r' c='vma_interval_tree_insert_after'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='47' u='m' c='vma_interval_tree_insert_after'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='52' u='m' c='vma_interval_tree_insert_after'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='56' u='a' c='vma_interval_tree_insert_after'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='56' u='a' c='vma_interval_tree_insert_after'/>
<use f='linux-5.3.1/mm/interval_tree.c' l='57' u='a' c='vma_interval_tree_insert_after'/>
