<dec f='linux-5.3.1/include/linux/sunrpc/xdr.h' l='230' type='__be32 *'/>
<offset>0</offset>
<doc f='linux-5.3.1/include/linux/sunrpc/xdr.h' l='230'>/* start of available buffer */</doc>
<use f='linux-5.3.1/fs/nfs/callback_xdr.c' l='710' u='r' c='encode_getattr_res'/>
<use f='linux-5.3.1/fs/nfs/callback_xdr.c' l='710' u='r' c='encode_getattr_res'/>
<use f='linux-5.3.1/fs/nfs/callback_xdr.c' l='710' u='r' c='encode_getattr_res'/>
<use f='linux-5.3.1/fs/nfs/callback_xdr.c' l='710' u='r' c='encode_getattr_res'/>
<use f='linux-5.3.1/fs/nfs/callback_xdr.c' l='710' u='r' c='encode_getattr_res'/>
<use f='linux-5.3.1/fs/nfs/callback_xdr.c' l='710' u='r' c='encode_getattr_res'/>
<use f='linux-5.3.1/fs/nfs/callback_xdr.c' l='904' u='r' c='process_op'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='533' u='w' c='xdr_init_encode'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='537' u='r' c='xdr_init_encode'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='540' u='r' c='xdr_init_encode'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='541' u='r' c='xdr_init_encode'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='542' u='w' c='xdr_init_encode'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='572' u='r' c='xdr_commit_encode'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='588' u='r' c='xdr_get_next_encode_buffer'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='603' u='r' c='xdr_get_next_encode_buffer'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='610' u='w' c='xdr_get_next_encode_buffer'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='632' u='r' c='xdr_reserve_space'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='642' u='w' c='xdr_reserve_space'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='689' u='w' c='xdr_truncate_encode'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='704' u='w' c='xdr_truncate_encode'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='705' u='r' c='xdr_truncate_encode'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='706' u='w' c='xdr_truncate_encode'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='706' u='r' c='xdr_truncate_encode'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='716' u='w' c='xdr_truncate_encode'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='736' u='r' c='xdr_restrict_buflen'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='767' u='r' c='xdr_write_pages'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='774' u='r' c='xdr_write_pages'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='775' u='r' c='xdr_write_pages'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='778' u='w' c='xdr_write_pages'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='790' u='w' c='xdr_set_iov'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='819' u='w' c='xdr_set_page_base'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='848' u='r' c='xdr_set_next_buffer'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='871' u='r' c='xdr_init_decode'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='872' u='r' c='xdr_init_decode'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='873' u='w' c='xdr_init_decode'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='901' u='r' c='__xdr_inline_decode'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='906' u='w' c='__xdr_inline_decode'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='933' u='r' c='xdr_copy_to_scratch'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='970' u='r' c='xdr_inline_decode'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='971' u='r' c='xdr_inline_decode'/>
<use f='linux-5.3.1/net/sunrpc/xdr.c' l='1053' u='w' c='xdr_read_pages'/>
