<dec f='linux-5.3.1/include/uapi/linux/xfrm.h' l='318' type='__u32'/>
<offset>0</offset>
<doc f='linux-5.3.1/include/uapi/linux/xfrm.h' l='318'>/* value */</doc>
<use f='linux-5.3.1/include/net/xfrm.h' l='1948' u='w' c='xfrm_mark_get'/>
<use f='linux-5.3.1/include/net/xfrm.h' l='1950' u='r' c='xfrm_mark_get'/>
<use f='linux-5.3.1/include/net/xfrm.h' l='1957' u='r' c='xfrm_mark_put'/>
<use f='linux-5.3.1/include/net/xfrm.h' l='1966' u='r' c='xfrm_smark_get'/>
<use f='linux-5.3.1/net/xfrm/xfrm_policy.c' l='1434' u='r' c='xfrm_policy_mark_match'/>
<use f='linux-5.3.1/net/xfrm/xfrm_policy.c' l='1436' u='r' c='xfrm_policy_mark_match'/>
<use f='linux-5.3.1/net/xfrm/xfrm_policy.c' l='1436' u='r' c='xfrm_policy_mark_match'/>
<use f='linux-5.3.1/net/xfrm/xfrm_policy.c' l='1439' u='r' c='xfrm_policy_mark_match'/>
<use f='linux-5.3.1/net/xfrm/xfrm_policy.c' l='1626' u='r' c='__xfrm_policy_bysel_ctx'/>
<use f='linux-5.3.1/net/xfrm/xfrm_policy.c' l='1724' u='r' c='xfrm_policy_byid'/>
<use f='linux-5.3.1/net/xfrm/xfrm_policy.c' l='1896' u='r' c='xfrm_policy_match'/>
<use f='linux-5.3.1/net/xfrm/xfrm_policy.c' l='2175' u='r' c='xfrm_sk_policy_lookup'/>
<use f='linux-5.3.1/net/xfrm/xfrm_policy.c' l='2597' u='r' c='xfrm_bundle_create'/>
<use f='linux-5.3.1/net/xfrm/xfrm_state.c' l='940' u='r' c='__xfrm_state_lookup'/>
<use f='linux-5.3.1/net/xfrm/xfrm_state.c' l='965' u='r' c='__xfrm_state_lookup_byaddr'/>
<use f='linux-5.3.1/net/xfrm/xfrm_state.c' l='979' u='r' c='__xfrm_state_locate'/>
<use f='linux-5.3.1/net/xfrm/xfrm_state.c' l='1049' u='r' c='xfrm_state_find'/>
<use f='linux-5.3.1/net/xfrm/xfrm_state.c' l='1063' u='r' c='xfrm_state_find'/>
<use f='linux-5.3.1/net/xfrm/xfrm_state.c' l='1080' u='r' c='xfrm_state_find'/>
<use f='linux-5.3.1/net/xfrm/xfrm_state.c' l='1193' u='r' c='xfrm_stateonly_find'/>
<use f='linux-5.3.1/net/xfrm/xfrm_state.c' l='1274' u='r' c='__xfrm_state_bump_genids'/>
<use f='linux-5.3.1/net/xfrm/xfrm_state.c' l='1282' u='r' c='__xfrm_state_bump_genids'/>
<use f='linux-5.3.1/net/xfrm/xfrm_state.c' l='1311' u='r' c='__find_acq_core'/>
<use f='linux-5.3.1/net/xfrm/xfrm_state.c' l='1320' u='r' c='__find_acq_core'/>
<use f='linux-5.3.1/net/xfrm/xfrm_state.c' l='1360' u='w' c='__find_acq_core'/>
<use f='linux-5.3.1/net/xfrm/xfrm_state.c' l='1360' u='r' c='__find_acq_core'/>
<use f='linux-5.3.1/net/xfrm/xfrm_state.c' l='1388' u='r' c='xfrm_state_add'/>
<use f='linux-5.3.1/net/xfrm/xfrm_state.c' l='1676' u='r' c='xfrm_state_update'/>
<use f='linux-5.3.1/net/xfrm/xfrm_state.c' l='1679' u='r' c='xfrm_state_update'/>
<use f='linux-5.3.1/net/xfrm/xfrm_state.c' l='1904' u='r' c='__xfrm_find_acq_byseq'/>
<use f='linux-5.3.1/net/xfrm/xfrm_state.c' l='1970' u='r' c='xfrm_alloc_spi'/>
<use f='linux-5.3.1/net/xfrm/xfrm_user.c' l='559' u='w' c='xfrm_smark_init'/>
<use f='linux-5.3.1/net/xfrm/xfrm_user.c' l='565' u='w' c='xfrm_smark_init'/>
<use f='linux-5.3.1/net/xfrm/xfrm_user.c' l='872' u='r' c='xfrm_smark_put'/>
<use f='linux-5.3.1/net/xfrm/xfrm_user.c' l='873' u='r' c='xfrm_smark_put'/>
<use f='linux-5.3.1/net/xfrm/xfrm_user.c' l='2288' u='w' c='xfrm_add_acquire'/>
<use f='linux-5.3.1/net/xfrm/xfrm_user.c' l='2288' u='w' c='xfrm_add_acquire'/>
<use f='linux-5.3.1/net/xfrm/xfrm_user.c' l='2288' u='r' c='xfrm_add_acquire'/>
<use f='linux-5.3.1/net/xfrm/xfrm_user.c' l='2812' u='r' c='xfrm_sa_len'/>
<use f='linux-5.3.1/net/xfrm/xfrm_user.c' l='2813' u='r' c='xfrm_sa_len'/>
