<dec f='linux-5.3.1/include/uapi/linux/xfrm.h' l='418' type='__u8'/>
<offset>1288</offset>
<use f='linux-5.3.1/net/xfrm/xfrm_user.c' l='1414' u='r' c='verify_newpolicy_info'/>
<use f='linux-5.3.1/net/xfrm/xfrm_user.c' l='1589' u='r' c='copy_from_user_policy'/>
<use f='linux-5.3.1/net/xfrm/xfrm_user.c' l='1605' u='w' c='copy_to_user_policy'/>
