<dec f='linux-5.3.1/include/linux/zlib.h' l='93' type='char *'/>
<use f='linux-5.3.1/lib/zlib_inflate/inffast.c' l='204' u='w' c='inflate_fast'/>
<use f='linux-5.3.1/lib/zlib_inflate/inffast.c' l='312' u='w' c='inflate_fast'/>
<use f='linux-5.3.1/lib/zlib_inflate/inffast.c' l='326' u='w' c='inflate_fast'/>
<use f='linux-5.3.1/lib/zlib_inflate/inflate.c' l='30' u='w' c='zlib_inflateReset'/>
<use f='linux-5.3.1/lib/zlib_inflate/inflate.c' l='53' u='w' c='zlib_inflateInit2'/>
<use f='linux-5.3.1/lib/zlib_inflate/inflate.c' l='359' u='w' c='zlib_inflate'/>
<use f='linux-5.3.1/lib/zlib_inflate/inflate.c' l='364' u='w' c='zlib_inflate'/>
<use f='linux-5.3.1/lib/zlib_inflate/inflate.c' l='371' u='w' c='zlib_inflate'/>
<use f='linux-5.3.1/lib/zlib_inflate/inflate.c' l='418' u='w' c='zlib_inflate'/>
<use f='linux-5.3.1/lib/zlib_inflate/inflate.c' l='427' u='w' c='zlib_inflate'/>
<use f='linux-5.3.1/lib/zlib_inflate/inflate.c' l='461' u='w' c='zlib_inflate'/>
<use f='linux-5.3.1/lib/zlib_inflate/inflate.c' l='483' u='w' c='zlib_inflate'/>
<use f='linux-5.3.1/lib/zlib_inflate/inflate.c' l='507' u='w' c='zlib_inflate'/>
<use f='linux-5.3.1/lib/zlib_inflate/inflate.c' l='530' u='w' c='zlib_inflate'/>
<use f='linux-5.3.1/lib/zlib_inflate/inflate.c' l='549' u='w' c='zlib_inflate'/>
<use f='linux-5.3.1/lib/zlib_inflate/inflate.c' l='558' u='w' c='zlib_inflate'/>
<use f='linux-5.3.1/lib/zlib_inflate/inflate.c' l='597' u='w' c='zlib_inflate'/>
<use f='linux-5.3.1/lib/zlib_inflate/inflate.c' l='630' u='w' c='zlib_inflate'/>
<use f='linux-5.3.1/lib/zlib_inflate/inflate.c' l='652' u='w' c='zlib_inflate'/>
<use f='linux-5.3.1/lib/zlib_inflate/inflate.c' l='701' u='w' c='zlib_inflate'/>
<offset>384</offset>
<doc f='linux-5.3.1/include/linux/zlib.h' l='93'>/* last error message, NULL if no error */</doc>
<use f='linux-5.3.1/lib/zlib_deflate/deflate.c' l='188' u='w' c='zlib_deflateInit2'/>
<use f='linux-5.3.1/lib/zlib_deflate/deflate.c' l='263' u='w' c='zlib_deflateReset'/>
